### ISSUE TITLE
expiresIn* doesn't work on string payloads

### ISSUE THREAD

**Issue by osuushi** [auth0/node-jsonwebtoken#101]
The problem appears to be that the expiration is getting attached to the payload, but if the payload is a string, the expiration is lost during encoding.

The workaround I found is instead of doing

```js
jwt.sign('foo', 'bar')
````

 to do 

```js
jwt.sign({data: 'foo'}, 'bar')
```

**Comment by breaklee** [comment]
did u have used latest version?

**Comment by MariusRumpf** [comment]
This was reported in #64. You must provide an object as first parameter to `jwt.sign()`. Had the same issue a while back http://stackoverflow.com/questions/23626823/json-web-token-does-not-expire/29778750#29778750

**Comment by jfromaniello** [comment]
@osuushi there is no way to have expiration if the payload is an string, @MariusRumpf is right.

**Comment by osuushi** [comment]
That makes sense. Weird that the spec allows for string payloads at all, but having it explained in the docs helps.
