### ISSUE TITLE
How to generate private key and public key 

### ISSUE THREAD

**Issue by programming-kid** [auth0/node-jsonwebtoken#108]
How to generate private and public key to be used in here
 https://github.com/auth0/node-jsonwebtoken#jwtsignpayload-secretorprivatekey-options

**Comment by eugeniop** [comment]
You can use `openssl` to create them (or any other method): https://www.openssl.org/docs/HOWTO/keys.txt

**Comment by MarkHerhold** [comment]
Just for the record, I was wondering if this library required the 
```
-----BEGIN RSA PRIVATE KEY-----
```
and
```
-----END RSA PRIVATE KEY-----
```

bits and it appears that these are required parts of the key file for this module.
