### ISSUE TITLE
Destroy token

### ISSUE THREAD

**Issue by furyscript** [auth0/node-jsonwebtoken#113]
I need to destroy or set expiry to now to token when it's be used, so I invalidate it manually.
How can I make it?

**Comment by jfromaniello** [comment]
This library support expiration:
https://github.com/auth0/node-jsonwebtoken#jwtsignpayload-secretorprivatekey-options
You can also blacklist tokens:
https://auth0.com/blog/2015/03/10/blacklist-json-web-token-api-keys/

**Comment by abhinav76** [comment]
Hey @jfromaniello I am using jsonwebtokens in my node project. So what I want is when the user logs-out of the system I need the token to be invalidated. I don't want to use exp because that would forcefully expire my session. Is there any way?

**Comment by blueror815** [comment]
Hi @jfromaniello 
I am using jsonwebtoken for my node project, and I have one problem for using it.
So, when user log out and his token should be destroyed.
How can I solve this problem?
I am waiting for your reply.
Cheers

**Comment by RahulSaini202** [comment]
@blueror815 
first you can set expiry time in jsonwebtoken.
second thing to remove cache data of browser.
