### ISSUE TITLE
Feature Request: Support for Ed25519?

### ISSUE THREAD

**Issue by jedd-ahyoung** [auth0/node-jsonwebtoken#115]
Would it be possible to support this algorithm? I don't know whether the library doesn't support it or whether it's simply not part of the JWT spec. It would be nice to be able to use Ed25519 keys, though.

**Comment by omsmith** [comment]
Ed25519 isn't part of JWA (unfortunately). The specs allow use non-standard algs, you just can't expect interoperability, and this library doesn't support such a set up (as is).

**Comment by MichielDeMey** [comment]
You can check out all support algorithms in the JWS spec:
https://tools.ietf.org/html/rfc7518#section-3.1

**Comment by ozomer** [comment]
Check out my fork: [jsonwebtoken-ed25519](https://www.npmjs.com/package/jsonwebtoken-ed25519)

**Comment by StevenACoffman** [comment]
@omsmith Edwards-curve cryptography was defined for JOSE in RFC 8037, the last specification to come out of the working group.  Is that not sufficient? https://tools.ietf.org/html/rfc8037

**Comment by panva** [comment]
@StevenACoffman this wasn't possible with node's `crypto` until very recently. I expect @omsmith to add the support for Ed25519 and Ed448 JWA eventually, until then - you can use my [implementation](https://github.com/panva/jose), with the added benefit of supporting more various key formats such as JWK, JWE encryption and all the bells and whistles of the JOSE specifications.
