### ISSUE TITLE
iat and exp not present in token

### ISSUE THREAD

**Issue by abhinav76** [auth0/node-jsonwebtoken#119]
@jfromaniello I generate a token from the data retrieved form database and it does not have exp and iat fields, due to this it is not checking expiration time and always verify token. and also when i decoded the token on jwt.io it says invalid token.
can you tell me the way to solve this? Here's my code
<code>
var token=jwt.sign(members,app.get('superSecret'),{
					expiresInMinutes:40
				});
</code>

**Comment by jfromaniello** [comment]
@abhinav76 As I mention in the comments of another issue, you should provide me a token. 

It is impossible to me to know from that line of code what's the content of the `members` variable.

Please paste here a generated token or provide a failing use case

**Comment by abhinav76** [comment]
this is the token
<code>eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InJhY2hpdDlAZ21haWwuY29tIiwidXNlcm5hbWUiOiJSYWNoaXQ5IiwicGFzc3dvcmQiOiI3YzRhOGQwOWNhMzc2MmFmNjFlNTk1MjA5NDNkYzI2NDk0Zjg5NDFiIiwiZ2VuZGVyIjoiTWFsZSIsImZfbmFtZSI6IlJhY2hpdCIsImxfbmFtZSI6IkdpcmRoYXIiLCJzdGF0dXMiOiIiLCJkb2IiOjAsImNvdW50cnkiOiJpbmQiLCJpYXQiOjE0NDAxMzY2MTEsImV4cCI6MTQ0MDE0MDIxMX0.RiAWIax7fvGhKIjKiJkt7LYQn633GM0_kAs192-RD5g</code>
It has eat now but still jwt.io shows it invalid

**Comment by jfromaniello** [comment]
This token has iat.

JWT.io says invalid because it is not valid with the secret there, you can put your secret to check if is valid.

![](https://dl.dropbox.com/s/yrzn4nrs1weogu8/ss-2015-08-21T12-10-23.png?dl=0)

**Comment by abhinav76** [comment]
yeah i found that,thanks
