### ISSUE TITLE
Invalid token error 

### ISSUE THREAD

**Issue by solshark** [auth0/node-jsonwebtoken#123]
Hi,

Having issues verifying token 
`eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ==.eyJtb2JpbGUiOnRydWUsIm9zIjoiaU9TIiwibGFuZyI6InN2X1NFIiwiYnJvd3Nlck5hbWUiOiJBcHBsaWNhdGlvbiIsImJyb3dzZXJWZXJzaW9uIjoiNDAiLCJjZGF0ZSI6MTQ0MDM5ODE1OS45OTg5NTgsInNvdXJjZUlkOiI6InVzYWdlU2Vzc2lvbjQ2MjA5MDk1OTYyNDAwMCIsInNjcmVlblJlc29sdXRpb24iOiIyMDQ4eDE1MzYifQ==.UHRwOSf31KKhgByiJlMhfjib9qUKKU8Ic3VXES6OFc+ck9iX75Qr3/wEC/z8ldyOYkB44rZoAYWPeR2UQkhTLQ==`

Secret key is `prezentor`.

It's decoded correctly here: http://jwt.io

**Comment by solshark** [comment]
https://github.com/brianloveswords/node-jws/issues/22 - isn't that related?

**Comment by omsmith** [comment]
@solshark Yes, likely related. Your token is not url-safe base64, and thus against -spec/invalid.
