### ISSUE TITLE
ASN1_CHECK_TLEN error when using jwt.sign with nodejs v4.1.0

### ISSUE THREAD

**Issue by olivier-squid** [auth0/node-jsonwebtoken#126]
The error :  
```
Error: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag
```

If I switch to node v0.12.7 it works fine.

**Comment by jfromaniello** [comment]
This is probably a new validation or some change in openssl on node 4.

Verify this:
https://www.ssl247.com/kb/ssl-certificates/troubleshooting/apache/errors-asn1-encoding-routine-apache

**Comment by leggetter** [comment]
I had this problem and it was down to there being something wrong with the private key. I ran the following to fix the key:

```sh
openssl rsa -in key.txt -out key.txt
```

Where `key.txt` was my private key.
