### ISSUE TITLE
Install instructions are incorrect

### ISSUE THREAD

**Issue by todbookless** [auth0/node-jsonwebtoken#130]
The instructions say to install using this command:

$ npm install jsonwebtoken

Observed: 

Using that command generates this error:

tbookles667151:TAGScript tbookles$ npm install jsonwebtokn
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "jsonwebtokn"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/jsonwebtokn
npm ERR! 404 
npm ERR! 404 'jsonwebtokn' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tbookles/testautomation/TAGScript/npm-debug.log

Expected:

Working install

**Comment by jfromaniello** [comment]
The readme looks okay but from the command output I see a typo, you are missing the e from token. Did you type this manually?
