### ISSUE TITLE
Providing registered claims via payload versus options in sign()

### ISSUE THREAD

**Issue by harriha** [auth0/node-jsonwebtoken#131]
If I interpret the `options` for `sign()` correctly, they offer mostly a convenient way for defining the registered claims and the user doesn't have to know the official claim names (e.g., one can define `audience` instead of more cryptic `aud`). However, one *can* define these claims straight via `payload` as well.

I assume this is by design and everything user passes in via `payload` is meant to be preserved as-is (unless overriding options are provided). And this is fine - as long as it is acknowledged that users *may* define registered claims via the `payload`, too. 

The thing I'm worried is that this method of defining these claims is not well-defined in the docs or in the tests. Thus, defining `payload.exp` directly feels a bit like using a private API (if seeing the `options.expiresIn` as the public one) and a simple, unintentional error in this library wiping the raw `exp` value might go unnoticed to production, making generated tokens valid forever.

I'd propose clarifying this way of defining the registered claims in the documentation and adding tests for them. If this sounds like the way to go, I can create a PR for getting this forward. 

If, however, the user is **not** supposed to define registered claims via `payload`, I'd propose adding strict validation for this and throwing an error if this is tried. 

In my opinion, in general regarding the configuration options and the registered claims, the stricter the validation the better, misunderstandings with configuring a security-related lib such as this can lead to unpleasant end results. FWIW, I'm liking the way [hapi](https://github.com/hapijs/hapi) uses the excellent [Joi](https://github.com/hapijs/joi) library for validating its configuration options [everywhere](https://github.com/hapijs/hapi/blob/master/lib/schema.js), gives a nice warm feeling for the developer when you know that simple configuration mistakes lead to immediate exceptions (and the schemas act as up-to-date docs for the options, too).

**Comment by jfromaniello** [comment]
Sorry for the big delay! 

I agree with everything you said. I will think this a little bit, we should change it for the next major version

**Comment by jfromaniello** [comment]
Fixed in v6. Have a look to changelog/readme

**Comment by harriha** [comment]
Hey, thanks, looks great!
