### ISSUE TITLE
Fails when empty string provided as secret

### ISSUE THREAD

**Issue by adambuczynski** [auth0/node-jsonwebtoken#134]
Not sure if intentional, but it caused me some headaches that the jwt.sign() call fails when the string I pass it is empty. It fails by throwing an error which says that the secret must be a string or a buffer, rather than returning a rejected promise.

Is it possible to reject the promise with the error rather than throwing, so that it can be handled gracefully in the app elsewhere without having to surround the sign call by a try block?

**Comment by jfromaniello** [comment]
I think this is related to #169

**Comment by jfromaniello** [comment]
I will handle this on next major version

**Comment by adambuczynski** [comment]
@jfromaniello thank you

**Comment by jfromaniello** [comment]
fixed in v6.
