### ISSUE TITLE
Max Length of Token

### ISSUE THREAD

**Issue by jdvs1** [auth0/node-jsonwebtoken#137]
Is there a maximum string size for tokens generated with jsonwebtoken?

I've been checking for it myself in case the string size is ludicrously large, but I'm not sure if this appropriate. Will the verify method error if the token size is, say, one million characters long?

**Comment by jfromaniello** [comment]
There isn't a limit on this library per se and I am not aware of a limit like this on JWS.

But I will encourage against it, JWT is not intended for such things.
