### ISSUE TITLE
How to use when private key was created with a password?

### ISSUE THREAD

**Issue by rightaway** [auth0/node-jsonwebtoken#139]
Is it recommended to create private keys with a password, for added security? If the private key was created with a password, how can it be used with `jwt.sign`? I can't get it to work.

Also, in the README in the section for `jwt.verify(token, secretOrPublicKey, [options, callback])`, it should be documented that the secret or public *or private* key can be used to verify. The private key can be used for both signing and verifying.

**Comment by peek4y** [comment]
```javascript
var cert = fs.readFileSync('privatekey'));
jwt.sign({ foo: 'bar' }, { key: cert, passphrase: 'yourpassword' }, { algorithm: 'RS256'});
```

**Comment by LuckyArd110** [comment]
I get an error:

```
             throw err
            ^

TypeError [ERR_INVALID_ARG_VALUE]: The property 'options.passphrase' is invalid. Received 12345
    at new NodeError (node:internal/errors:372:5)
    at parseKeyEncoding (node:internal/crypto/keys:343:13)
    at prepareAsymmetricKey (node:internal/crypto/keys:548:10)
    at preparePrivateKey (node:internal/crypto/keys:558:10)
    at Sign.sign (node:internal/crypto/sig:122:46)
```
