### ISSUE TITLE
Add clock drift tolerance to the verify method

### ISSUE THREAD

**Issue by jacopofar** [auth0/node-jsonwebtoken#141]
I use JWT to implement a single sign-on, but recently one of the applications which validates the token was on a different machine than the signing one, with a system clock 6 seconds behind.

It would be nice to have the possibility to backdate the iat field a few seconds to tolerate clock skew, without having to remove the iat as some implementations (e.g. Oracle Fusion OAuth) do.

I've implemented the necessary code changes, docs and tests and could do a PR if you are fine with that.

**Comment by eskatos** [comment]
:+1:  a configurable `clock-skew` would be nice!

**Comment by jacopofar** [comment]
Made a PR for that, the parameter is called `clockTolerance`

**Comment by cvillerm** [comment]
+1

**Comment by lmillott** [comment]
+1

**Comment by MarkHerhold** [comment]
Why not just fix the machine with the skewed clock?

**Comment by cvillerm** [comment]
If the token is issued by a server you don't fully control, this isn't possible. Think also that even a 1 or 2s clock drfit can impact the `nbf` claim as a token just issued and consumed on another server with a clock 1 or 2s behind could have its validation fail.
Anyway, there is now a `clockTolerance` option that can be used and I think that this issue should be considered as resolved.

**Comment by TechyTimo** [comment]
Just so you know, This cracked my head over several days. Maybe make it more prominent in the documentation

**Comment by jacopofar** [comment]
@MarkHerhold because the machine was not under my control :)
