### ISSUE TITLE
Is it possible to set tokens invalid ?

### ISSUE THREAD

**Issue by igor-yamshchykov** [auth0/node-jsonwebtoken#143]
For instance someone steals user token (no matter how) and user requests to set those invalid. 

the tokens are always created with users id, is it possible to set the tokens created previously invalid according to specific user id ?

**Comment by willfarrell** [comment]
a) If you're using a different private key for each user, then yes. Just create a new key.
b) If you're using one key for the server then you would have to have a check in your code to compare the user and exp in the token to a table where you store the user and expire timestamp. You'll need to use your expiresInSeconds config if you'd prefer to store the create timestamp.

**Comment by igor-yamshchykov** [comment]
Thanks, but tracking is not a problem actually, is there a function or something to set the token expired ? 
Something like jwt.setExpired(token, secretOrPublicKey) ?

**Comment by willfarrell** [comment]
Not possible doing it how you envision it working. The token has the expiry date encrypted inside of it. Since you can't force the client to replace their token, using something like ` jwt.setExpired(token, secretOrPublicKey) ` will not work. That is why tracking when users has expired tokens or replacing their secret key are the two main options you have for expiring a token early.

**Comment by igor-yamshchykov** [comment]
Thanks, I think I'll use the approach with user secret keys for token.

**Comment by akshath4u** [comment]
Hi, I have to logout the session while user click 'logout' link. In this case i need to expire the token so what would be the solution for this?

**Comment by jfromaniello** [comment]
The solution is to keep a blacklist where the key is either the full token or the JTI (json webtoken id).

The blacklist can have a TTL (time-to-live) based on the exp field. (Once the token is expired it can be removed from the blacklist.)

More details in this blogpost:

https://auth0.com/blog/2015/03/10/blacklist-json-web-token-api-keys/
