### ISSUE TITLE
Question about expiration period

### ISSUE THREAD

**Issue by drasko** [auth0/node-jsonwebtoken#145]
What happends if `expiresIn` options is ommitted in `jwt.sign()` function? Is there some default expiration period that is set?

I need to create a token that never expires.

**Comment by jacopofar** [comment]
No, if no `expiresIn`is specified the token has no expiration date, so it will never expire. It still has the `iat` field to mark the issue time.

**Comment by drasko** [comment]
Thanks! Closing the issue...

**Comment by gijo-varghese** [comment]
but I got a warning saying the token got expired. I'vent put any `expiresIn` https://github.com/auth0/node-jsonwebtoken/issues/425
