### ISSUE TITLE
Couldn't verify token generated by php library 

### ISSUE THREAD

**Issue by pavankumarkatakam** [auth0/node-jsonwebtoken#149]
Hi, im using laravel framework and creating tokens based on this package https://github.com/namshi/jose, but for websockets i want to verify the token  in nodejs, the token generated by php (namshi/jose adapter) is correct since im checking it in jwt.io, but this package giving the error 
{ [JsonWebTokenError: invalid token] name: 'JsonWebTokenError', message: 'invalid token' }

Please help me.

**Comment by pavankumarkatakam** [comment]
Decoding also not working...

**Comment by pavankumarkatakam** [comment]
is there any one here?

**Comment by jfromaniello** [comment]
Can you provide a token with the secret generated by that library?

**Comment by pavankumarkatakam** [comment]
Token is 

    eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvbG9naW4iLCJpYXQiOjE0NTA1ODcyNjksImV4cCI6MTQ1MDU5MDg2OSwibmJmIjoxNDUwNTg3MjY5LCJqdGkiOiI1MGIxNGQ4MTU3N2U5ZDYwZTMyNmY3NTIzMDQxM2YwMiIsInN1YiI6NSwicmVsYXRpb24iOiJ1c2VyIiwiYWNjZXNzIjpudWxsfQ.qxO8rXFNLW5lwoqCcHPFODPeqjenoJJIYZG1z_ww880


secrete `veryverysecret`


Here you go...

**Comment by pavankumarkatakam** [comment]
Hi @jfromaniello , Did you find why it is not verified.

**Comment by jfromaniello** [comment]
@pavankumarkatakam besides being expired it worked for me:

```javascript
var token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvbG9naW4iLCJpYXQiOjE0NTA1ODcyNjksImV4cCI6MTQ1MDU5MDg2OSwibmJmIjoxNDUwNTg3MjY5LCJqdGkiOiI1MGIxNGQ4MTU3N2U5ZDYwZTMyNmY3NTIzMDQxM2YwMiIsInN1YiI6NSwicmVsYXRpb24iOiJ1c2VyIiwiYWNjZXNzIjpudWxsfQ.qxO8rXFNLW5lwoqCcHPFODPeqjenoJJIYZG1z_ww880';
var secret = 'veryverysecret';
jwt.verify(token, secret, { ignoreExpiration: true }, function(err, decoded) {
  console.dir(arguments);
});
```

shows this:

```
{ '0': null,
  '1':
   { iss: 'http://localhost:8000/login',
     iat: 1450587269,
     exp: 1450590869,
     nbf: 1450587269,
     jti: '50b14d81577e9d60e326f75230413f02',
     sub: 5,
     relation: 'user',
     access: null } }
```

**Comment by pavankumarkatakam** [comment]
ok, i will check it.

**Comment by pavankumarkatakam** [comment]
Hi , I figured it out it not the problem with `ignoreExpiration`, from web page the token is returning like "blahblahblah..."  instead of 'blahblahblah...' , problem solved.
