### ISSUE TITLE
Invalid directory  /node_modules/stream

### ISSUE THREAD

**Issue by Casy** [auth0/node-jsonwebtoken#150]
Hi, i am tryng JWT in a react-native app, but i have this error:

![captura-de-pantalla-2015-12-22-a-las-2 27 32-a m](https://cloud.githubusercontent.com/assets/1847940/11948622/84903126-a854-11e5-9711-2869491f3a28.png)

i install via NPM:

```npm install jsonwebtoken```

and just try the example:
```
var jwt = require('jsonwebtoken');
var token = jwt.sign({ foo: 'bar' }, 'shhhhh');
```

**Comment by omsmith** [comment]
_stream_ is a core node.js module. If your build environment isn't providing it, not much to be done.

In browsers, this would usually be provided by the bundler, (for example, browserify provides https://github.com/substack/stream-browserify)

**Comment by shauns** [comment]
@Casy You might have more luck using something that's pure JS like https://www.npmjs.com/package/jsrsasign

**Comment by jfromaniello** [comment]
Closing this issue, @omsmith answer is spot on.
