### ISSUE TITLE
nbf check is incorrectly implemented

### ISSUE THREAD

**Issue by mediamonks-arjan** [auth0/node-jsonwebtoken#152]
I'm getting this error:

    1451384603 '>=' 1451384603
    NotBeforeError: jwt not active

From this line:
https://github.com/auth0/node-jsonwebtoken/blob/f1fb176a1599a6fed82c9ffcf7517c295c5c0541/index.js#L213

The spec states:
https://tools.ietf.org/html/rfc7519#section-4.1.5

    The processing of the "nbf"
    claim requires that the current date/time MUST be after or equal to
    the not-before date/time listed in the "nbf" claim

In the example above, the current date/time is equal to the not-before date/time, so it shouldn't give an error.
I think the `>=` should be changed to `>`, because when equal the nbf should be valid.

**Comment by jfromaniello** [comment]
Thanks, fixed in v5.5.1

**Comment by mediamonks-arjan** [comment]
Awesome, thanks!
