### ISSUE TITLE
"expiresIn" doesn't work with string or number

### ISSUE THREAD

**Issue by salali** [auth0/node-jsonwebtoken#153]
Getting the error

```"expiresIn" should be a number of seconds or string representing a timespan eg: "1d", "20h", 60```

I looked at where the error was being thrown in index.js line 86:

```payload.exp = timespan(options.expiresIn);```

I stepped through the timespan function and everything looks good there if I pass in either string or number. However the function always returns undefined?

**Comment by salali** [comment]
I should have read the documentation better:

```payload could be an object literal, buffer or string. Please note that exp is only set if the payload is an object literal.```

I was sending in a string.

Closing as non-issue.

**Comment by jgentes** [comment]
After updating to 5.5, I started seeing this error, whereas I wasn't seeing it before.

I am also passing a string in rather than an object literal, so I went ahead and removed the expiration since it's not being used and it cleared the error up.

However, this error message is incorrect - the format of "expiresIn" was correct, so this is an open bug in my opinion.

**Comment by jgentes** [comment]
Please re-open

**Comment by jfromaniello** [comment]
Notice that it will be silently ignored now when the payload doesn't support expiration. I plan to fail explicitly in the next major version.

**Comment by MeRahulAhire** [comment]
Out of nowhere I'm facing exact same issue. First it was working fine and now its giving me this error 
**invalid expiresIn option for string payload**
```
const accessToken = jwt.sign(phone, JWT_AUTH_TOKEN, { expiresIn: '30s' });
const refreshToken = jwt.sign(phone, JWT_REFRESH_TOKEN, { expiresIn: '1y' });
```

**Comment by skibaalex** [comment]
@MeRahulAhire 
any solutions? I am facing the same issue

**Comment by MeRahulAhire** [comment]
@skibaalex it's easy https://github.com/MeRahulAhire/React-Node-Passwordless-Auth/blob/a251fcc21b76d4136ad62ac8430077240c5b3b7f/server.js#L68

**Comment by nayabahmad** [comment]
Facing the same issue

**Comment by xinthose** [comment]
Just make the payload an object.
Wrong: `sign({ data.username, ...`
Right: `sign({ "username": data.username }, ...`

**Comment by kirilritobis** [comment]
> Just make the payload an object: Wrong: `sign(data.username, ...` Right: `sign({ "username": data.username }, ...`

That solved the problem. Thank you

**Comment by juannguyenicd** [comment]
The type of payload to sign should be: `'object'`

ref: https://github.com/auth0/node-jsonwebtoken/blob/master/sign.js#L90

**Comment by hungify** [comment]
**You can only set expiresIn when that payload is an object.**

Ref: https://community.auth0.com/t/i-need-some-help-with-jwt-expiresin-syntax/47333
