### ISSUE TITLE
How to revoke exited token

### ISSUE THREAD

**Issue by ngminhduong** [auth0/node-jsonwebtoken#158]
Any ideas of how to implement revoke token?

Seems nobody has written nothing

**Comment by jfromaniello** [comment]
we did write about this:

https://auth0.com/blog/2015/03/10/blacklist-json-web-token-api-keys/

**Comment by ngminhduong** [comment]
Yes. Thanks for your help

**Comment by apedyashev** [comment]
Just wondering, why don't you implement token invalidation? It would save us resources that we have to allocate for blacklist (for example redis memory)  and API would be more nice/consistent, e.g:

`jwToken.destroy(token)`
