### ISSUE TITLE
Matching jwt token against a regex

### ISSUE THREAD

**Issue by sohailalam2** [auth0/node-jsonwebtoken#162]
Hey Guys,

We are facing some issues with the jsonwebtoken library when we create our own token following the JWT standards (using C language). Unfortunately the official C library doesnt compile well in our Windows environment. 

After debugging for days we came to the conclusion that the regex used in the **jws** library **verify-stream.js** file does not allow for equals sign (=), hence the regex validation fails.

Currently the regex looks like as follow - 

```js
const JWS_REGEX = /^[a-zA-Z0-9\-_]+?\.[a-zA-Z0-9\-_]+?\.([a-zA-Z0-9\-_]+)?$/;
```

Suggested change is to include the (=) sign as well - 

```js
const JWS_REGEX = "^[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*$";
```

Thanks

**Comment by jfromaniello** [comment]
It can't have a `=` because the JWT should be base64 *url encoded*. If it has an `=` it might be bas64 but is not properly url encoded.

Is on the spec: https://tools.ietf.org/html/rfc7519

Maybe there is an issue in the c library that you are using

**Comment by omsmith** [comment]
https://github.com/brianloveswords/node-jws/issues/38

**Comment by sohailalam2** [comment]
@jfromaniello, @omsmith Thank you for the quick response. We will make the required chanes as suggested.

**Comment by NBardelot** [comment]
I've opened ticket #541 because in my opinion the response isn't correct. The RFC does not state that the base64url-encoded header *must not* include `=` padding. It just mentions that you *can* omit them.
