### ISSUE TITLE
payload not modified, ever

### ISSUE THREAD

**Issue by mitom** [auth0/node-jsonwebtoken#167]
Since 5.5.2 (?) that introduced using `extend` the payload is never modified, at least not if it's an object. Couldn't it be an option? Or introduce a JWT object that would `toString` to the token itself and have getters for the headers of the token, like expiration date and such.

My application relied on the `iat` for some functionality that broke with this update (which IMO should have been a major).

**Comment by jfromaniello** [comment]
decoding the JWT should be cheap:

```
var token = jwt.sign({ foo: 'bar' }, 'shhhhh');
var decoded = jwt.decode(token);
console.dir(decoded)
```

I am very sorry for breaking your application, it was never the expected behaviour. I agree, it should have been a major version.

**Comment by jfromaniello** [comment]
it should be done like this:

- get the kid (using jwt.decode)
- validate with the proper validator

**Comment by jfromaniello** [comment]
Just let me know if this works for you or not and I will reopen and look an alternative solution. Thanks

**Comment by mitom** [comment]
Your workaround works, but I'll just keep it version locked to a previous version instead.
