### ISSUE TITLE
TypeError: Converting circular structure to JSON upgrading from 5.5.0 to 5.5.4

### ISSUE THREAD

**Issue by MtDalPizzol** [auth0/node-jsonwebtoken#168]
Getting a ```TypeError: Converting circular structure to JSON``` after upgraded from 5.5.0 to 5.5.4.

Aprently it ocours when using the ```.sign()``` method, which internally uses ```JSON.stringify()``` and should use a custom replacer.

**Comment by jfromaniello** [comment]
I just tried this on 5.5.0 (git checkout v5.5.0) and it doesn't work either with circular references.

It was never supported and I am not planning to support this.
