### ISSUE TITLE
Sign callback function is called with successful result as a first argument

### ISSUE THREAD

**Issue by jeanadrien** [auth0/node-jsonwebtoken#169]
But, as a node.js developer I would conventionally expect an error as a first argument, and a success as a second argument.

**Comment by jfromaniello** [comment]
I plan to address this on next major version

**Comment by Deadarius** [comment]
:+1: this one, I am using promisify-node library to make it return promise and it actually took me awhile to realise what is going on :laughing:

**Comment by pioneerroad** [comment]
+1 I'm also using a promise library and took me ages to work out why the promise was resolving as an error.

**Comment by jfromaniello** [comment]
fixed in v6
