### ISSUE TITLE
Consider use node-jose instead of node-jws

### ISSUE THREAD

**Issue by gut4** [auth0/node-jsonwebtoken#171]
https://github.com/cisco/node-jose library implements all algorithms, formats, and options in JWS, JWE, JWK, and JWA.
Maybe it makes sense to switch jsonwebtoken to node-jose?

**Comment by charandas** [comment]
All algorithms really? What about the HMAC family algorithms such as HS512 and the rest. `node-jws` implements them, while `node-jose` linked above does not.

**Comment by firefoxNX** [comment]
@gut4 @charandas Any reason to choose node-jose over jws?

**Comment by ziluvatar** [comment]
I think the consideration should start in the other way around, once we consider to implement features that JWS does not support we will need to see what other options are there to use or to implement.
