### ISSUE TITLE
Subject claim is not verified

### ISSUE THREAD

**Issue by BigAB** [auth0/node-jsonwebtoken#173]
Hi all, 

I am totally new to the JWT world, so this may be my misunderstanding, but if you add the subject option when you sign a JWT, shouldn't the sub be verified?

This gist runs successfully, but should it not error?
https://gist.github.com/BigAB/3854cd17a3b6072e7c5b

Is this a bug, or my misunderstanding of how it works?

**Comment by jfromaniello** [comment]
We have a test for this:

https://github.com/auth0/node-jsonwebtoken/blob/e403a66bee5f1aaabe974a7862cc6eaf0b926d57/test/jwt.rs.tests.js#L302-L309

I am not sure why it doesn't work for you

**Comment by BigAB** [comment]
Looks like that test tests issuer not subject

**Comment by BigAB** [comment]
In fact, it appears to me, many of those tests were not running properly and giving false positives.
Here is a PR with async fixes, and the issue with subject
#175

**Comment by jfromaniello** [comment]
You were right! :( 

Fixed in v5.6.0

**Comment by jfromaniello** [comment]
Thanks a lot for taking care of the tests.
