### ISSUE TITLE
Nested JWT

### ISSUE THREAD

**Issue by itamarwe** [auth0/node-jsonwebtoken#174]
Are nested JWT supported? (to allow sending the content securely)
As in this example:
https://self-issued.info/docs/draft-ietf-oauth-json-web-token.html#NestedJWTExample

**Comment by jfromaniello** [comment]
no

**Comment by grimurd** [comment]
Any info on if/when this might be implemented?

**Comment by panva** [comment]
No plans to support JWE at the moment.

**Comment by traviscollins** [comment]
For future readers, while the RFC example A.2 includes a JWE payload - it does not restrict this to only JWE.

Implementing validation of nested JWTs (where the header "cty": "JWT") would be valuable for this project. It would allow use cases with multiple signing entities in a chain.
