### ISSUE TITLE
No luck making this work with google json file

### ISSUE THREAD

**Issue by dukedougal** [auth0/node-jsonwebtoken#176]
I am using a Google Service Account, and when I use Python it returns the access token fine.
https://developers.google.com/identity/protocols/OAuth2ServiceAccount#makingrequest

```
oauth_fields = {
        "type": "service_account",
        "project_id": "blah",
        "private_key_id": "blah",
        "private_key": "-----BEGIN PRIVATE KEY-----blah-----END PRIVATE KEY-----\n",
        "client_email": "blah@",
        "client_id": "blah",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://accounts.google.com/o/oauth2/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_x509_cert_url": "blah"
        }
        credentials = ServiceAccountCredentials.from_json_keyfile_dict(self.oauth_fields, scopes=['https://www.googleapis.com/auth/compute'])
        print(credentials.get_access_token())
```

However after spending about 12 hours on it I can't get this library to generate a token that Google will accept.

Has anyone managed to make this this library get an access token from Google?

If yes any examples that I can copy?

thanks!

**Comment by csaroff** [comment]
Presumably you don't have google's private key and cannot sign tokens.  You probably need to make a request to google's authentication server using some client credentials and google will issue you an oauth token.

From the [documentation](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#overview):
> Then, your application prepares to make authorized API calls by using the service account's credentials to request an access token from the OAuth 2.0 auth server.

I think this issue can be closed.
