### ISSUE TITLE
Throw or return errors via callback

### ISSUE THREAD

**Issue by simon-p-r** [auth0/node-jsonwebtoken#180]
Error on this [line](https://github.com/auth0/node-jsonwebtoken/blob/master/index.js#L65) should be returned via callback or thrown if called sync.  Will you accept a PR to fix this?

**Comment by jfromaniello** [comment]
I am planning to change the interface a little bit in the next major version

**Comment by LinusU** [comment]
@jfromaniello Since nothing really is asynchronously at all, why is there callbacks at all? Is you plan to remove them?
