### ISSUE TITLE
expiresIn with a duration 1 second results in an exp 3.6 seconds after the iat

### ISSUE THREAD

**Issue by victusfate** [auth0/node-jsonwebtoken#181]
let jwt = require('jsonwebtoken');
let sToken = jwt.sign({foo: 'bar'}, 'secret', { expiresIn: 1 });
let oToken = tokenToObject(sToken);
console.log(oToken.claims);

   { foo: 'bar',
     iat: 1457450740,
     exp: 1457454340 } }

// the token to object code

    var tokenToObject = (sToken) => {
      if (util.exists(sToken)) {
        var oOutput = {};
        var aParts = sToken.split('.');
        aParts.pop();
        for (var i in aParts) {
          var part = aParts[i];
          var name = i == 0 ? 'header' : 'claims';
          oOutput[name] = JSON.parse(new Buffer(part, 'base64').toString('ascii'));
        }
        return oOutput;    
      }
      else {
        console.log('tokenToObject.error received null or undefined argument',sToken);
      }
      return {};
    }

**Comment by jfromaniello** [comment]
I can't reproduce this neither with 5.7.0 nor the just released v6.

This is from repl:

```javascript
> let jwt = require('./')
undefined
> let sToken = jwt.sign({foo: 'bar'}, 'secret', { expiresIn: 1 });
undefined
> decoded = jwt.decode(sToken)
{ foo: 'bar', iat: 1461773840, exp: 1461773841 }
> decoded.exp - decoded.iat
1
>
```

**Comment by jfromaniello** [comment]
BTW, iat and exp are in seconds since UNIX epoch.. so If you get 3600, that means somehow you end up with  **1 hour** expiration

**Comment by victusfate** [comment]
@jfromaniello that's exactly what happened, I had overwritten that expiresIn in the func I was calling

right those units are seconds not ms

1457454340  - 1457450740  = 3600

thanks for the sanity check @jfromaniello
