### ISSUE TITLE
FEATURE: "options" to support property names as described in the JWT standard

### ISSUE THREAD

**Issue by tiblu** [auth0/node-jsonwebtoken#184]
Please support property names as they are defined in standard (https://tools.ietf.org/html/rfc7519#section-4.1.1) in the ``options`` object.

For example ``options.iss`` (currently ``options.issuer``), ``options.sub`` (currently ``options.subject``) and so on. 

What is the benefit of using non-standard naming and converting between non-standard and standard names?

For backward compatibility, the fallback mechanism has to be non-standard naming support has to work as well.

**Comment by jfromaniello** [comment]
Since v6 you can do this:

```javascript
jwt.sign({iss: 'issuer', 'aud': 'dassd'}, secret, {algorhitm: 'HS256', header: { kid: '123' }});
```

or

```javascript
jwt.sign(payload, secret, {
  algorhitm: 'HS256',
  header: { kid: '123' }
  issuer: 'issuer',
  audience: 'dassd'
});
```

*and it throws if you provide both* example:  `payload.aud` and `payload.audience`

**Comment by tiblu** [comment]
Super! Thanks a lot!
