### ISSUE TITLE
Not possible to verify unsigned token (signed with alg none)

### ISSUE THREAD

**Issue by jonekdahl** [auth0/node-jsonwebtoken#185]
Is it possible to verify (as in `jwt.verify()`) a token that was signed with algorithm `none`?

```javascript
var payload =  {
    iss: 'https://example.com'
    aud: 'test.client.id'
};
var signedToken = jwt.sign(payload, null, { algorithm: 'none' });

// First try with empty key, causes 'secret or public key must be provided'
jwt.verify(signedToken, null, { audience: 'test.client.id', issuer: 'https://example.com' }, ...);

// Second try with a dummy key, causes 'jwt signature is required'
jwt.verify(signedToken, '<dummy key>', { audience: 'test.client.id', issuer: 'https://example.com' }, ...);
```

I expected the first version to do what I want, which is to realize that the token does not have a signature and therefore doesn't require a signature validation and hence not a key either.

**Comment by jfromaniello** [comment]
The verify method options support algorithms which is an array of supported algs

**Comment by jonekdahl** [comment]
Thanks for the suggestion. Unfortunately, using `options.algorithms` didn't help:

```javascript
// Third attempt, also causes 'secret or public key must be provided'
jwt.verify(signedToken, null, { algorithms: ['none'] }, ...);
```

**Comment by jonekdahl** [comment]
I had a look at the jwt.verify() implementation and it does not seem to handle unsigned JWTs correctly. This is the snippet of code where the problem occurs:

```javascript
  if (parts[2].trim() === '' && secretOrPublicKey){
    return done(new JsonWebTokenError('jwt signature is required'));
  }

  if (!secretOrPublicKey) {
    return done(new JsonWebTokenError('secret or public key must be provided'));
  }

```

If the token does not have a signature, the method will always return with an error. One way to fix this would be to add an additional condition to the second if statement:

```javascript
  if (parts[2].trim() !== '' && !secretOrPublicKey) {
    return done(new JsonWebTokenError('secret or public key must be provided'));
  }
```

This change allows `jwt.verify()` to successfully verify an unsigned token, assuming you pass `{ algorithms: ['none'] }`. It does not break any of the existing test cases, but I am not sure it is correct.

**Comment by jfromaniello** [comment]
Yes! Sounds like a good plan

**Comment by jonekdahl** [comment]
Okay, great. I updated the title to reflect that this is more of a defect than a question.
