### ISSUE TITLE
size of session?

### ISSUE THREAD

**Issue by Kaijun** [auth0/node-jsonwebtoken#186]
I'm considering how big is the size of session which stores the token and related content. 

I stored the user json and was calculating how many users can be stored at the same time? 

Or it will consume all my memory if there is enough amount of users?

**Comment by jppellerin** [comment]
The size of the token is really dependent on what information you are storing in it.  It can be very small or very large.  Your workflow and how you use the token will determine the usefulness of a larger vs smaller token.

The beauty of a token is that it's stateless.  You don't really need to save the token in session.  If you want to revoke a token, there is a lot of talk about it on the web.
Here is an example of such discussion : https://github.com/auth0/node-jsonwebtoken/issues/103

At the end of the day, check the amount of information that you're saving in your token.  This will give you it's size, which should be quite consistent.  After that it's easy to determine based on the number of expected user.

**Comment by Kaijun** [comment]
@jppellerin 
thanks, i thought i was misunderstanding the mechanism of jwt, i thought jwt works with session when i posted this question, but actually it doesn't right?

so where does jwt store the payload? inside the global jwt object? if that is the case, what's the max size of the payload storage? or there's rather no limit.

**Comment by jppellerin** [comment]
@Kaijun That is correct.  JWT has nothing to do with a session.  Which, in one part, is why it's gaining so much popularity as of late with stateless back-ends.

Also correct.  The JWT itself doesn't quite encode the payload.  It is not a secret.  It is signed using your secret or private key - used to validate the payload.  If the payload absolutely needs to be hidden you might need JWE or saving the JWT in a secured cookie, or some other mechanism.
