### ISSUE TITLE
"invalid token"

### ISSUE THREAD

**Issue by chazwoza** [auth0/node-jsonwebtoken#187]
Hi all,
I am trying to verify a token using this code:

```
    jwt.verify(token, cert, function(err, decoded) {
        console.log(err);
        console.log(" tried to decode token: " + decoded) // bar
    });

```
The err message i get is below:
`{ [JsonWebTokenError: invalid token] name: 'JsonWebTokenError', message: 'invalid token' }`

How can I trace what is wrong here? BTW, the token itself does verify using http://jwt.io website so I think the token is valid/correct.

**Comment by chazwoza** [comment]
Issuee was the user :)

**Comment by sergeant-q** [comment]
@chazwoza I am having the same problem. What was your solution?

**Comment by tdezso** [comment]
Hello,
I have the same problem: get the same message while the token is valid and the signature is ok as well (also using jwt.io).

I was making some development when suddenly this error showed up. The very same authentication code still works fine on the deployed application, but it drives me crazy on my development machine.

What was the problem in your case?

**Comment by brianschardt** [comment]
same thing happening to me
