### ISSUE TITLE
Client side verification (public key) without decoding 

### ISSUE THREAD

**Issue by jchapelle** [auth0/node-jsonwebtoken#190]
Hello, I'm using your library but I cannot find a way to verify if a user is still logged in client side.
Isn't it possible to encode a token with a public and a private key and to be able to verify the validity of a token without decoding it with the public key ?

**Comment by jppellerin** [comment]
Same would be true : 

```
// verify a token asymmetric
var cert = fs.readFileSync('public.pem');  // get public key
jwt.verify(token, cert, function(err, decoded) {
  console.log(decoded.foo) // bar
});
```

I'm not sure why verifying client side would be any different from verifying server side.  The beauty with JavaScript... it's the same process client or server side.

Hope this helps!

**Comment by ssboisen** [comment]
My guess is that OP have mistaken signing for encryption. With JWT the content is not encrypted, only signed. So as @jppellerin mentioned you can very easily verify it using the public key, and since the content is not encrypted you can get the decoded content. Check out www.jwt.io for exxamples.
