### ISSUE TITLE
Migrating from 5.7

### ISSUE THREAD

**Issue by ohomer** [auth0/node-jsonwebtoken#197]
I'm trying to use smooch.io
http://docs.smooch.io/javascript/#authenticating-users-optional

which does not work in the current version of jwt, what would the latest jwt expect instead of the old options of:

`
    {
        headers: {
            alg: 'HS256',
            typ: 'JWT',
            kid: KEY_ID
        }
    }
`

be?

**Comment by jfromaniello** [comment]
Headers (plural) was renamed to header (singular) in 6.

**Comment by ohomer** [comment]
Thanks, I thought so. Were there any other changes? Changing it to `header` doesn't give an error, but gives a result that is not accepted by smooch. While with 5.7 it works

**Comment by jfromaniello** [comment]
You are not required to upgrade to the very latest version, if 5.7 works
okay for you, you might want to pin to `^5.7.0`. There isn't any security
patch vulnerability in those versions.

The v6 has few changes to make the life easier for newcomers. here is the
change log:

https://github.com/auth0/node-jsonwebtoken/blob/master/CHANGELOG.md
