### ISSUE TITLE
jwtString.split is not a function

### ISSUE THREAD

**Issue by lludol** [auth0/node-jsonwebtoken#201]
Hello,

When I send a number to the verify method, there is an error:

```javascript
const jwt = require('jsonwebtoken');
jwt.verify(42, 'secret', (err) => {
  console.log(err);
};
```

```
TypeError: jwtString.split is not a function
```

**I know the verify method need a String to work.**

If we use the sync method, we have to put try/catch to catch the error and it's ok, it works.

But when we use the aync method, the err parameter is not set and an error is thrown ("TypeError: jwtString.split is not a function").

Is it normal?

I use node.js v6.

(why the module don't verify if the parameter is a String or not?)

**Comment by jfromaniello** [comment]
Let's keep discussing this on #191
