### ISSUE TITLE
Support for enc? (encryption)

### ISSUE THREAD

**Issue by scniro** [auth0/node-jsonwebtoken#204]
Is there a native way to encrypt these? According to the [spec](https://tools.ietf.org/html/rfc7519#page-26), native encryption is a possibility. Am I doing something wrong here?

```
var cert = fs.readFileSync('./priv.pem');
var token = jwt.sign({ foo: 'bar' }, cert, {'enc': 'A128CBC-HS256'});
```

throws the following error...

> "enc" is not allowed

**Comment by tcd156** [comment]
'enc' isn't passed through in this library. This is using an implementation of JWS which does not support encryption.
