### ISSUE TITLE
This is not issue, just ask some questions

### ISSUE THREAD

**Issue by cybercoder** [auth0/node-jsonwebtoken#207]
1. Is possible to store tokens into a database? like pgsql table where users are stored?
2. Is possible the token never expire? ( e.g. mobile APP telegram.me )

**Comment by jfromaniello** [comment]
> 1. Is possible to store tokens into a database? like pgsql table where users are stored?

JWT is a signed token, like a piece of information digitally signed.

The fact that is digitally signed means that you can validate the signature, if the signature is valid you can trust the information it contains.

You could store it anywhere, but generally you don't need to.

> 2. Is possible the token never expire?

Yes, don't specify `exp`.

**Comment by jfromaniello** [comment]
more info here https://jwt.io/introduction/

**Comment by cybercoder** [comment]
@jfromaniello gratitude for light explain

Warm Regards
