### ISSUE TITLE
PromisifyAll causes optional attributes to become mandatory

### ISSUE THREAD

**Issue by antony** [auth0/node-jsonwebtoken#210]
Hi,

I am aware that recently the library was changed so that bluebird's PromisifyAll would work to make everything thenable.

However I have noticed that it is not a straight swap as you would expect, as formerly optional attributes have become mandatory.

The one in question that I have run into is 'sign', but there might be more.

Synchronous version:

``` javascript
jwt.sign({sub: 'xyz'}, 'my-key')
```

Asynchronous version:

``` javascript
jwt.sign({sub: 'xyz'}, 'my-key', {})
```

Note that the async version requires an empty options object, otherwise there is a `joi` validation error that 'value is required' which, after a lot of digging, appears to be the joi validation on the options object being:

[https://github.com/auth0/node-jsonwebtoken/blob/master/sign.js#L6](https://github.com/auth0/node-jsonwebtoken/blob/master/sign.js#L6)

``` javascript
Joi.object().keys({ ... })
```

Whereas I think it should be:

``` javascript
Joi.object.optional().keys({ ... })
```

**Comment by ziluvatar** [comment]
Duplicated: https://github.com/auth0/node-jsonwebtoken/issues/318
Done on: https://github.com/auth0/node-jsonwebtoken/pull/320 (only available in master branch so far)

Now you can do: `jwt.sign({sub: 'xyz'}, 'my-key', yourCallbackFunction)` without specifying the options object.
