### ISSUE TITLE
Follow JWT spec Claim names on jwt.verify options

### ISSUE THREAD

**Issue by DiegoZoracKy** [auth0/node-jsonwebtoken#214]
`jwt.verify` expects as options:

``` javascript
{ audience: 'urn:foo', issuer: 'urn:issuer', jwtid: 'jwtid', subject: 'subject' }
```

Which is good for the clarity of the code, but i think that it should also accept the original claim names defined on JWT spec, as:

``` javascript
{ aud: 'urn:foo', iss: 'urn:issuer', jti: 'jwtid', sub: 'subject' }
```

Suggestion, at index.js:

**From:**

``` javascript
if (options.audience) {
    var audiences = Array.isArray(options.audience)? options.audience : [options.audience];

    // current code
}
```

**To:**

``` javascript
if (options.audience || options.aud) {
    var audience = options.audience || options.aud; // I would also suggest the use of 'let' instead of 'var' inside these blocks
    var audiences = Array.isArray(audience)? audience : [audience];

    // current code
}
```

Are you open do Pull requests?

**Comment by felixfbecker** [comment]
They are not the same though. `expiresIn` accepts a string like `1 day` that gets converted to a timestamp, but I would always expect `exp` to be the raw `exp` value.

**Comment by DiegoZoracKy** [comment]
Good @felixfbecker. So the claims passed on using the same key as the spec (e.g. `exp`) would be treated as is, `raw`. Leaving the others that can act with some sort of helper with their "associative" names, like `expiresIn`.

**Comment by felixfbecker** [comment]
Imo this is would make the API very confusing

**Comment by DiegoZoracKy** [comment]
@felixfbecker But do you agree that the original spec keys should be accepted?

**Comment by felixfbecker** [comment]
no, I think it's fine as-is

**Comment by panva** [comment]
Closing as stale.
