### ISSUE TITLE
Buffer signing incorrectly serializes payload

### ISSUE THREAD

**Issue by sandersaares** [auth0/node-jsonwebtoken#216]
The documentation states that *payload could be an object literal, buffer or string* but this does not appear to match the implementation. The following code incorrectly transforms the buffer into a JSON object, instead of serializing it as-is.

```
let jwt = require("jsonwebtoken");
let payload = Buffer.from("TkJyotZe8NFpgdfnmgINqg==", "base64");

console.log(payload);

let token = jwt.sign(payload, "signing key");

console.log(token);
```

Expected behavior: payload is the 16-byte buffer provided.
Actual behavior: payload is `{"0":78,"1":66,"2":114,"3":162,"4":214,"5":94,"6":240,"7":209,"8":105,"9":129,"10":215,"11":231,"12":154,"13":2,"14":13,"15":170,"iat":1465815291}`

Adding the noTimestamp option makes no difference (besides removing the timestamp).

**Comment by jfromaniello** [comment]
Thank you very much for reporting this. I found the issue and solved in `v7.1.6`
