### ISSUE TITLE
 sign asynchronously - has no err in callback only token

### ISSUE THREAD

**Issue by ddennis** [auth0/node-jsonwebtoken#218]
Sign asynchronously - from the readme

      jwt.sign({ foo: 'bar' }, cert, { algorithm: 'RS256' }, function(err, token) {
        console.log(token);
      });

The generated token is in the **err** - the function should be like so?

      jwt.sign({ foo: 'bar' }, cert, { algorithm: 'RS256' }, function(token) {
        console.log(token);
      });

**Comment by yitomok** [comment]
Didn't got error when I tested, can you give version and full code example, thanks

**Comment by ddennis** [comment]
i apologize,  forgot to validate my package.json, i was on version 5.5.0.  Updating to 7.0.1 , everything works as described in the readme.
