### ISSUE TITLE
Unable to resolve jws/lib/sign-stream.js

### ISSUE THREAD

**Issue by calclavia** [auth0/node-jsonwebtoken#221]
Just installed jsonwebtoken@7.0.1 and required the module, then immediately got the error "Cannot find node_modules/jws/lib/sign-stream.js"

Context: Running this on React Native

**Comment by jfromaniello** [comment]
I am not familiar with React Native, but the file is there. Try `rm -rf node_modules && npm i`

**Comment by crbrasfield** [comment]
Having the same issue as @calclavia. I tried reinstalling the node module but still no luck. It seems like several dependencies are missing. I manually stream, only to see that more modules were missing.

**Comment by calclavia** [comment]
@jfromaniello Tried that as well. Did not fix it.

**Comment by calclavia** [comment]
Any update on this issue? Still having this problem...

**Comment by RyanMitchellWilson** [comment]
Just got this problem today trying to use 7.2.1.

Using React-Native 0.41

**Comment by anders-g-hansen** [comment]
According to this https://github.com/facebook/react-native/issues/3874#issuecomment-167150393

> Node core modules cannot be used inside React Native as it's a completely different environment

I only needed to decode the token and switched to using this https://github.com/auth0/jwt-decode

In any case, this issue can be closed.  It isn't really applicable to node-jsonwebtoken itself.

**Comment by antoncoding** [comment]
Is there any React-Native alternative that can perform`sign()` with HMAC SHA256? 
Can't find any that would work.

**Comment by grifotv** [comment]
@anders-g-hansen could you please let me know how you managed to make it work with `jwt-decode` https://github.com/auth0/node-jsonwebtoken/issues/221#issuecomment-283108676

**Comment by heritiermwalila** [comment]
You can try this module react-native-pure-jwt

**Comment by sashiksu** [comment]
> @anders-g-hansen could you please let me know how you managed to make it work with `jwt-decode` [#221 (comment)](https://github.com/auth0/node-jsonwebtoken/issues/221#issuecomment-283108676)

didn't see passing the key to decrypt in this package. Wonder how it decodes.

**Comment by its-me-ilia** [comment]
> > @anders-g-hansen could you please let me know how you managed to make it work with `jwt-decode` [#221 (comment)](https://github.com/auth0/node-jsonwebtoken/issues/221#issuecomment-283108676)
> 
> didn't see passing the key to decrypt in this package. Wonder how it decodes.

jwt does not need secret key to decode content, secret key is for validation
