### ISSUE TITLE
JWT returned as first argument on OS X

### ISSUE THREAD

**Issue by DamonGant** [auth0/node-jsonwebtoken#222]
During debugging we noticed the JWT is returned as the first argument (`err`) on OSX.

OpenSSL 0.9.8zh 14 Jan 2016
OSX El Capitan 10.11.5

Here's a part of our code:

      return new Promise((resolve, reject) => {
        jwt.sign({userid: userid}, new Buffer(config.get("jwt:ec_priv"), "base64"), {issuer: "flot.to.master", expiresIn: "30d", algorithm: "ES512"}, function(err, jwt) {
          if (err) {
            return reject(err);
          }
          return resolve(jwt);
        })
      });

CC @4ware

**Comment by jfromaniello** [comment]
You might be using jsonwebtoken v5. This was changed in v6 as stated in the changelog:

https://github.com/auth0/node-jsonwebtoken/blob/master/CHANGELOG.md#600---2016-04-27

**Comment by DamonGant** [comment]
Ha, now I feel silly, the dependency wasn't installed locally on the machine. Thanks for spotting it so fast.

**Comment by jfromaniello** [comment]
@DamonGant no problem.. and sorry for the confusion, this breaking change was tough given we know there are lot of articles/examples using the previous version.
