### ISSUE TITLE
err == JWT, token == undefined in async sign?

### ISSUE THREAD

**Issue by r3wt** [auth0/node-jsonwebtoken#226]
```js
var jwt = require('jsonwebtoken');
jwt.sign(req.user, config.jwt.secret , {
	expiresIn: '365 days',
}, function (err, token) {
	log.debug("err: \n%s\ntoken: \n %s",err,token);
	if (err !== null) {
		return res.error(err);
	}
	res.apiResponse({
		id: newUser.id,
		email: newUser.email,
		isAdmin: !!newUser.admin,
		token: token,
	});
});
```

the call to `log.debug()` outputs:

```

[Fri Jul 08 2016 18:56:58 GMT+0000 (UTC)] DEBUG err:
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjU3N2ZmNzdhMDM2NGQ2MTExY2FlNTY3OCI    sImVtYWlsIjoiZ2FycmV0dEA2Yml0Y29uc3VsdGluZy5jb20iLCJpc0FkbWluIjpmYWxzZSwiZGF0ZSI    6IjIwMTYtMDctMDhUMTg6NTY6NTguNTg1WiIsIl9fc3B0IjoiZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2N    pT2lKSVV6STFOaUo5LmV5SnBjM01pT2lKb2RIUndjem92TDJGd2FTNXpkRzl5YlhCaGRHZ3VZMjl0TDN    ZeEwyRndjR3hwWTJGMGFXOXVjeTgyVGt0WFdUaFFOekU1Uld4SU1YbG9ZV2RaVTBFMElpd2ljM1ZpSWp    vaWFIUjBjSE02THk5aGNHa3VjM1J2Y20xd1lYUm9MbU52YlM5Mk1TOWhZMk52ZFc1MGN5ODFiMmRJUzI    1TU1VUTRTRXB2ZUZsU1lrSXpVV1Z6SWl3aWFuUnBJam9pTXpJNU1UazBZemt0WWpVNU15MDBOREpsTFR    rell6UXRNRFEyTlRCaU9XRTVNek5rSWl3aWFXRjBJam94TkRZNE1EQTBNakU0TENKbGVIQWlPakUwTmp    nd01EYzRNVGg5LkhLalVZTTBKa0hiR242MFdQNGc0dDVkdno1c2VQWXBVMktRalZaSmJ6cGsiLCJpYXQ    iOjE0NjgwMDQyMTgsImV4cCI6MTQ5OTU0MDIxOH0.7iw_iSZ-05O1Py-nl2z7FCFbhGu63urt4_iqaeE    7DFc
token:
 undefined
```

I'm having trouble understanding if your documentation is incorrect and the signature to the callback is actually `function(token,error)` or if some type of error occured during signing. the `req.user` object does contain a base64 encoded JWT already that comes from stormpath, so if the error is correct it could be a result of that.

**Comment by jfromaniello** [comment]
You are using an older version. Rule of thumb with node modules, if you have this kind of doubts on an API always read the readme from your node_modules folder not from github.

**Comment by r3wt** [comment]
thanks for the hasty reply.

**Comment by jfromaniello** [comment]
No problem, glad to help. I really sorry to cause this trouble , is the second time in a week someone has this issue. I think it will be better to explain this change directly on this readme

**Comment by r3wt** [comment]
@jfromaniello no worries man, it happens to us all on occasion. I think an explanation in the Readme would do the trick. Appreciate your humility and hasty response which helped me to fix it quickly. I would rather see wrong documentation. Than someone who takes weeks to reply to new issues. Have a good day man, and BTW thanks for the awesome libraries
