### ISSUE TITLE
JWT.verify() mutates options parameter.

### ISSUE THREAD

**Issue by rokoroku** [auth0/node-jsonwebtoken#227]
I define and use a same options variable as argument for JWT.verify() and JWT.sign(), to reduce duplicated codes.
In this case, JWT.verify() method mutates options object, which causes validation error from JWT.sign().

So I'd like to suggest cloning options parameter rather than mutating by something like Object.assign() .

**Comment by jfromaniello** [comment]
thanks for reporting this and sorry for the delay, fixed in `v7.1.1`
