### ISSUE TITLE
JWT returns error during mocha tests

### ISSUE THREAD

**Issue by cevatkerim** [auth0/node-jsonwebtoken#228]
When testing jwt included project, if I run mocha tests it fails with a valid token whereas it the test itself will pass if it's run individually. I get a "[JsonWebTokenError: invalid signature]" error even though the token is valid.

**Comment by jfromaniello** [comment]
can you show me the test? thanks

**Comment by ziluvatar** [comment]
@cevatkerim I'm going to close this issue, you can reopen it if you still have the issue.
