### ISSUE TITLE
Can we using jsonwebtoken for authentication with load balancing ?

### ISSUE THREAD

**Issue by pmd30011991** [auth0/node-jsonwebtoken#230]
As title, I need to implement a notification system as well as the authentication, I using NodeJS 0.10.44, Redis & socket-jwt 

Regards

**Comment by tomaspinho** [comment]
You probably already have the answer for this question, but yes, JWT is ideal for load balancing scenarios. You just have to keep in mind to deploy the same secret to all of your webservers.

**Comment by oliverdunk** [comment]
As far as I can tell, this issue can be closed.
