### ISSUE TITLE
Umbrella header 'JSONWebToken-umbrella.h' not found

### ISSUE THREAD

**Issue by askingquestion** [auth0/node-jsonwebtoken#233]
When I run JWT, I got Umbrella header 'JSONWebToken-umbrella.h' not found.

I used cocoapods, already reinstall and still got Umbrella header 'JSONWebToken-umbrella.h' not found error.

How to correct this?
![screen shot 2016-08-01 at 11 18 22 am](https://cloud.githubusercontent.com/assets/20764452/17283360/af5a3c1e-57d9-11e6-8727-251291afd269.png)

**Comment by jfromaniello** [comment]
Wrong repository. This is a javascript library.

@hzalaz What is the repository @askingquestion should be looking for?

**Comment by hzalaz** [comment]
@askingquestion the repo is https://github.com/auth0/JWTDecode.swift
