### ISSUE TITLE
7.1.8 is a breaking change

### ISSUE THREAD

**Issue by jdiprizio** [auth0/node-jsonwebtoken#237]
In previous versions of this package, `jwt.verify` returns a plain JS object whereas 7.1.8 returns a stringified version of the object.

I'm perfectly fine with having to run `JSON.parse` myself though could you confirm this is intended behavior? If that's the case, I'd suggest you bump the major version number as this could lead to issues in other packages/projects that are assuming that it returns a plain object.

**Comment by RickDT** [comment]
`jwt.verify` (async version) also started incorrectly returning an invalid issuer warning, but switching back to 7.1.7 (with no other changes) fixes the problem.

**Comment by jfromaniello** [comment]
Sorry for the big inconvenience.

I just reverted the merge and release a 7.1.9.

I will look deeper in this change.

@jdiprizio does your token has a `"typ":"JWT"` in the header?

@RickDT sorry again

**Comment by RickDT** [comment]
Thanks!
