### ISSUE TITLE
Invalidate token and reuse tokens

### ISSUE THREAD

**Issue by serganus** [auth0/node-jsonwebtoken#247]
I am using JWT as the secondary authentication method. The workflow is simple :
- user logs in using some authentication
- User generates a private link using jwt

The issue : 
- I can set the expiry of jwt to be 1 hour but cannot invalidate the jwt if the user is logout
- Dynamix expiry in case the one hour is expired but the user is already authenticated.

I can take care of the logic just cannot find a direction in terms of jwt?

**Comment by cdhowie** [comment]
When implementing JWT, I wanted to do something similar -- invalidate all previous tokens when a user's password was changed.  The way we implemented this was to have an "authentication serial number" field stored both on the user's DB record and the issued JWT.  A token is only valid if the contained serial number matched the one on the user's record.

So all we have to do to invalidate all existing tokens for that user is increment their authentication serial number.

If you're trying to implement functionality whereby one *specific* token can be invalidated (user has two tokens and wants only one of them to be revoked) then that's not something you can do with JWT.
