### ISSUE TITLE
How to identify reconnect?

### ISSUE THREAD

**Issue by overflowz** [auth0/node-jsonwebtoken#253]
Hi, I'm using handshake authentication at the moment. Problem is that, I get token (which expires in 30 seconds), it works fine, it's authenticated and I'm talking to user. But when the user disconnects (due to high ping) and reconnects, I would like to resume that session, but in that time token might be invalid. Generating new token does not resume session too. May I ask how to implement such thing? #

**Comment by jfromaniello** [comment]
I think this question belongs to https://github.com/auth0/socketio-jwt

**Comment by overflowz** [comment]
ouch, I'm really sorry! I was over-exhausted when I wrote that.
