### ISSUE TITLE
Permit forever token

### ISSUE THREAD

**Issue by alvaro-paco** [auth0/node-jsonwebtoken#255]
I need my token never expires. If  it is possible today, i can i do that?

**Comment by denneulin** [comment]
Hi, you just do not have to set `expiresIn` option.

**Comment by jfromaniello** [comment]
yes, @denneulin is right. Don't set `expiresIn` or `exp`.

**Comment by alvaro-paco** [comment]
But it is expiring!

**Comment by BojDom** [comment]
expireIn: "1000y"
i doubt you have to worry about the expiration date
