### ISSUE TITLE
This package should define a peer dependency for crypto-browserify to latest version

### ISSUE THREAD

**Issue by rw3iss** [auth0/node-jsonwebtoken#256]
The version shipped with this package is 3.2.x, which doesn't have the 'createVerify' and other methods implemented, which are required to run this package in the browser. The newest package of 'crypto-browserify (3.11.0) has them implemented.

**Comment by rw3iss** [comment]
I noticed upon defining the peer dependency this package says:
npm WARN peerDependencies The peer dependency crypto-browserify included from jsonwebtoken will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

**Comment by jfromaniello** [comment]
This package doesn't ship with "crypto-browserify", maybe you are using some fork?

https://github.com/auth0/node-jsonwebtoken/blob/master/package.json#L21-L34

crypto is part of nodejs and this project wasn't meant to be used in the browser.

- if you only need to decode JWTs in the browser you can use http://github.com/auth0/jwt-decode
- if you need to verify you can use http://kjur.github.io/jsrsasign/

**Comment by rw3iss** [comment]
Ah! Cool, thank you for the links, will definitely put them to use.
Cheers!

**Comment by jfromaniello** [comment]
glad to help
