### ISSUE TITLE
Question?JWT with ACL

### ISSUE THREAD

**Issue by a-covar** [auth0/node-jsonwebtoken#263]
Is there any guide or best practices on how to connect JWT with ACL in Node.js .

The are just a couple of libraries out there but not too much documentation on this.

**Comment by ziluvatar** [comment]
Hi @a-covar, do you mean a way to define in JWT the access control for a user (subject of the JWT)?

If so, you could add scopes for that user in the JWT. You can take a look to [this post](https://auth0.com/blog/using-json-web-tokens-as-api-keys/), it's old but I think it is useful.
