### ISSUE TITLE
Process times out when signing

### ISSUE THREAD

**Issue by ja-bravo** [auth0/node-jsonwebtoken#266]
Hi

I'm trying to use this package to sign and verify tokens used in my application.
I want to return a token for the user when he logs in, for that, I'm using the following code:

```
                  if(bcrypt.compareSync(password, user.password)) {
                    delete user.password;
                 
                    console.log('start the signing');
                    var token = jwt.sign(user, app.get('superSecret'), {
                        expiresInMinutes: 480 // expires in 8 hours
                    });
                    console.log('finished the signing');
                    res.json({success: true, user: user, token: token});
                }
                else {
                    res.status(401).end('Incorrect username or password.');
                }
```

This will output the first console.log message, but won't output the second one and after a couple of minutes the server will time out with a 504 error.

What could be happening?

I'm using Debian Wheezy, Express 4.13 and the lastest version of this package.

Thank you.

**Comment by jfromaniello** [comment]
How big is the profile and the secret?

Also, I think you are using an old version since `expiresInMinutes` was deprecated long ago..
