### ISSUE TITLE
DeprecationWarning: Using Buffer without `new` will soon stop working.

### ISSUE THREAD

**Issue by santanu-biswas** [auth0/node-jsonwebtoken#268]
With Node v7.0.0, following deprecation warning is generated:
```
DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or 
preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
```
It seems the warning is emitted by the package [jwa](https://github.com/brianloveswords/node-jwa) (dependency of [jws](https://github.com/brianloveswords/node-jws)).

**Comment by pito-svk** [comment]
Have same problem.

**Comment by samikarak** [comment]
same for me

**Comment by safebyte** [comment]
same

**Comment by DyuldinKS** [comment]
+1

**Comment by ralphtheninja** [comment]
Should be fixed by https://github.com/brianloveswords/node-jwa/pull/18 and https://github.com/brianloveswords/node-jws/pull/61

**Comment by tmcgannon** [comment]
Can you bump jws to 3.1.4 to make this message go away?

**Comment by ralphtheninja** [comment]
@tmcgannon It says `^3.1.3` in package.json so should work now

See https://github.com/auth0/node-jsonwebtoken/blob/cc0f4d67b649110a035db3df9265f05db269a15a/package.json#L23

**Comment by tmcgannon** [comment]
Yes, that works fine if I install jws into my project's package.json (which I'd rather not do but will since this module does not seem to be actively updated).

**Comment by ziluvatar** [comment]
At the time of writing `^3.1.4` is already added to dependencies, we can close this issue.
