### ISSUE TITLE
Version 7.2.0 Will not minify properly.

### ISSUE THREAD

**Issue by failpunk** [auth0/node-jsonwebtoken#280]
My builds started failing today and I have traced it all the way back to node-jsonwebtoken: v7.2.0
Pinning my project to v7.1.10 minifies just fine.

Using:

- gulp-uglify: 2.0.0

**Comment by ziluvatar** [comment]
Have you tried v7.2.1? https://github.com/auth0/node-jsonwebtoken/blob/master/CHANGELOG.md#721---2016-12-07
There was a ES5 compatibility break in v7.2.0

**Comment by failpunk** [comment]
@ziluvatar `7.2.1` seems to minify correctly. Thanks.
