### ISSUE TITLE
Upgrading to 7.2.0 throws SyntaxError (up to node v3.3.1)

### ISSUE THREAD

**Issue by hbaqai** [auth0/node-jsonwebtoken#281]
#193 seems to have shown up again starting in 7.2.0. Using node v0.12.17 gives the following error:

```
>> const Hoek = require('hoek');
>> ^^^^^
>> SyntaxError: Use of const in strict mode.
>>   at exports.runInThisContext (vm.js:73:16)
>>   at Module._compile (module.js:443:25)
>>   at Object.Module._extensions..js (module.js:478:10)
>>   at Module.load (/Users/hashir/Projects/opentok-node/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
>>   at Function.Module._load (module.js:310:12)
>>   at Module.require (module.js:365:17)
>>   at require (module.js:384:17)
>>   at Object.<anonymous> (/Users/hashir/Projects/opentok-node/node_modules/jsonwebtoken/sign.js:1:73)
>>   at Module._compile (module.js:460:26)
>>   at Object.Module._extensions..js (module.js:478:10)

```

various other errors show up if I upgrade to a node version up to and including v3.3.1. Upgrading to node v4.0.0 and above seems to make the errors go away.

**Comment by hbaqai** [comment]
For now, I've worked around the problem by using:

`"jsonwebtoken": "~7.1.x"
`
instead of 

`"jsonwebtoken": "^7.x.x"
`

in my package.json

**Comment by ziluvatar** [comment]
@hbaqai this should work now with last version, can you check?

**Comment by ziluvatar** [comment]
@hbaqai I'm closing the issue, be free to open it if you find it happening again.
