### ISSUE TITLE
[Question] Caching the user object

### ISSUE THREAD

**Issue by jpinkster** [auth0/node-jsonwebtoken#283]
I am using JWT for my SSO solution and it is working out really well. The problem I am trying to figure out now is how to use JWT with ACL without having to lookup the users access in the database on every request. I am considering caching the user object in Redis but am not sure of the recommended approach and if I am overlooking something that already streamlines this process. 

_What I am thinking_: When the user logs in, cache their user object in Redis. For all authorized request, fetch the user cache from Redis. If they don't exist, fetch them and then cache them. If anyone updates that user object, delete the user cache from Redis and then re-add them. 

Any issues with this approach? Am I missing something that is already baked in to another module? Any thoughts are appreciated.

**Comment by jcw-** [comment]
I'm currently working through a similar thought-process and would be interested in hearing any thoughts on the validity of this approach (or if you've arrived at a refined solution?), as it is basically what I arrived at as well. One potential alternative I was thinking about is updating the JWT (re-sign and send back to client to include in future requests) with the key pieces of the user object added to the private claims section. This way it's more stateless and eliminates storing that detail in Redis, but at the expense of a larger token.

**Comment by ziluvatar** [comment]
@jpinkster I'd need to read where JWT fits in the solution.
- Is it similar to session cookies but instead of raw cookie information you have a JWT?
- Is it a token with ACLs that the client (web browser?) sends to your backend to performa actions?
- Is it that you have the "What I am thinking" part as your solution but you are considering "Could JWTs do this better?" ?

**Comment by ziluvatar** [comment]
Closing since there was no answer in months, be free to re-open it.
