### ISSUE TITLE
Token size increase each and every time when I call jwt.sign() method

### ISSUE THREAD

**Issue by ramthakur1991** [auth0/node-jsonwebtoken#284]
Hello ,

I'm using JsonWebToken as following manner 
`var token = jwt.sign(user, config.apiSecret, { notBefore: "365 days" });`

I used that token in Login Api . When I hit the Login Api each and every time the token size get increased. 
I just check my all configuration but still getting the same issue 
I'm currently using the following version for JsonWebToken 
`"jsonwebtoken": "^7.2.1"`

Waiting for your reply 
Thanks

**Comment by jfromaniello** [comment]
Can you show us an example token?

**Comment by ziluvatar** [comment]
@ramthakur1991 I will close this issue, if you still experience the problem be free to re-open it adding an example or any other useful information.
