### ISSUE TITLE
Cannot have a user named 'iat'

### ISSUE THREAD

**Issue by cancerberoSgx** [auth0/node-jsonwebtoken#290]
It seems that user's cannot be named 'iat' because the 'decoded' object uses this property for validation. If this is a fact of life, then as an enhancement I would suggest to use a less common name, like '__iat'. Example: 

```
{ ValidationError: child "iat" fails because ["iat" must be a number]
    at Object.exports.process (/home/sg/git/locis/node_modules/joi/lib/errors.js:140:17)
    at internals.Object.internals.Any.validate (/home/sg/git/locis/node_modules/joi/lib/any.js:667:25)
    at Object.module.exports [as sign] (/home/sg/git/locis/node_modules/jsonwebtoken/sign.js:68:62)
    at /home/sg/git/locis/src/authentication.js:36:20
    at process._tickCallback (internal/process/next_tick.js:103:7)

```

**Comment by jfromaniello** [comment]
`iat` (issued-at)  is an standard claim of the JWT specification:

> The "iat" (issued at) claim identifies the time at which the JWT was
> issued.  This claim can be used to determine the age of the JWT.  Its
> value MUST be a number containing a NumericDate value.  Use of this
> claim is OPTIONAL.

https://tools.ietf.org/html/rfc7519#section-4.1.6

**Comment by cancerberoSgx** [comment]
ok sorry for my ignorance :(

**Comment by jfromaniello** [comment]
@cancerberoSgx hey, no problem at all!

Your suggestion is valid, just that we want to follow the spec in this library.

> It seems that user's cannot be named 'iat' 

What do you mean by that? Typically the name of the user will be on a "name" property, let's say you have a user named `iat` then the payload for the JWT will looks like this:

```javascript
{
   "iat": 21321312312,
...
   "name": "iat"
}
```

**Comment by cancerberoSgx** [comment]
I'm using:

 jwt.verify(token, 'superSecret', (err, decoded)=>  

and the decoded object returned has the following format:

{ sgurin: 'test123', iat: 1483371249 }

(no 'name' property). In my case I'm using this decoded object to then get the request's user and check for permissions. 
Also I just updated to latest jwt version and this is still the behavior. 
Should I configure the library or am I missing something ? 
Thanks in advanced
