### ISSUE TITLE
decoded value is not a valid json string

### ISSUE THREAD

**Issue by cancerberoSgx** [auth0/node-jsonwebtoken#291]
the 'decoded' result of calling jwt.verify(token...  is not a valid JSON string, although is a javascript object representation. I want to use JSON.parse and not eval() to parse it.

**Comment by jfromaniello** [comment]
I don't understand what you are trying to do, can you explain more?

You don't need to do `eval()` nor `JSON.parse` to the result, it is already an object.

**Comment by cancerberoSgx** [comment]
You are right sorry, I got confused my bad, sorry again :(
