### ISSUE TITLE
JsonWebTokenError: 'invalid exp value'

### ISSUE THREAD

**Issue by scippio** [auth0/node-jsonwebtoken#293]
I'm get this error: ` name: 'JsonWebTokenError', message: 'invalid exp value'`
but I think my token is ok (decoded): `{ exp: '1484048026', password: 'aaaaaaaa', iat: 1484047996 }`
What's wrong? Please help.

**Comment by ziluvatar** [comment]
Hi @scippio! the claims `exp`, `nbf` and `iat` must be numbers. In your `exp` claim you can see how the number is inside a string. 

ok => `exp: 1484048026`
invalid => `exp: '1484048026'`

**Comment by scippio** [comment]
Thanks, I thought it :)
