### ISSUE TITLE
Expire a token manually

### ISSUE THREAD

**Issue by IbraheemAlSaady** [auth0/node-jsonwebtoken#298]
Is there a way that I can make a token expires manually?

**Comment by ziluvatar** [comment]
Hi @IbraheemAlSaady, can you elaborate the question? What do you mean by `manually`? Once it is generated to be able to modify the `exp` claim?

**Comment by IbraheemAlSaady** [comment]
Hello @ziluvatar, if I requested two tokens at the same time, the first token remains active.

**Comment by ziluvatar** [comment]
I see, to get more context, why is that a problem?

**Comment by IbraheemAlSaady** [comment]
@ziluvatar, I was just doing some testings, so I actually don't have a case, I'm just curious.

**Comment by ziluvatar** [comment]
The JWT itself is just a bunch of claims that optionally can expire at a time, If I get a JWT, I can not make it expire, it was already signed, if I modify the claim, I won't be able to re-signing without the issuer's secret. 

Different thing is to be able to revoke/blacklist a JWT based on its unique id (`jti` claim), user (ie: `sub` claim) or any other information stored in the JWT (+ your system?) to let you know that one is valid and the other is not.

If it is a matter of test suite, you could fake the time of the system to test a scenario when a JWT gets expired.

**Comment by IbraheemAlSaady** [comment]
Great, thank you very much.

**Comment by 12345anurag** [comment]
I have a same problem ,when  I  requested two tokens at the same time, the first token remains active

**Comment by IbraheemAlSaady** [comment]
@12345anurag I ended up expiring it manually using Redis. Which is an okay solution for this problem.

**Comment by 12345anurag** [comment]
Ohk

**Comment by ilaopenxcell** [comment]
What should i do in case i want to expire token to do logout user.

**Comment by Deepak-Dhaka** [comment]
I have a use case, im using JWT token to access webdrive documents using link having jwt token to be  send through mails. at some event after process end i want to invalidate/expire the token so that no one can use that token. how can i do that, only way i see is to store the token and use flag to valid/non valid token. seems not good

**Comment by ziluvatar** [comment]
@ilaopenxcell @Deepak-Dhaka those are different use cases from the original question, you can check:
https://github.com/auth0/node-jsonwebtoken/issues/375
and https://github.com/auth0/node-jsonwebtoken/issues/143

**Comment by coderblower** [comment]
When someone issued jwt a token with a certain time to expire. But suddenly Admin wants unAthorize him before expire. How can An admin to expaire token and refresh cliant page??
