### ISSUE TITLE
Nodejs verify token from .net failed

### ISSUE THREAD

**Issue by khoachung89** [auth0/node-jsonwebtoken#299]
I create token from .net by this code:

`var keybytes = Convert.FromBase64String("MYCUSTOMCODELONGMOD4NEEDBEZE");`
`var signingCredentials = new SigningCredentials(`
`                        new InMemorySymmetricSecurityKey(keybytes),`
`                        SecurityAlgorithms.HmacSha256Signature,`
`                        SecurityAlgorithms.Sha256Digest);`
`var nbf = DateTime.UtcNow.AddDays(-100);`
`var exp = DateTime.UtcNow.AddDays(100);`
`var payload = new JwtPayload(null, "", new List<Claim>(), nbf, exp);`
`var user = new Dictionary<string, object>();`
`user.Add("userId", "1");`

`payload.Add("user", user);`
`payload.Add("success", true);`
`var jwtToken = new JwtSecurityToken(new JwtHeader(signingCredentials), payload);`
`var jwtTokenHandler = new JwtSecurityTokenHandler();`
`var resultToken = jwtTokenHandler.WriteToken(jwtToken);`

I send the resultToken to nodejs and verify it with this code:

`var result = jwt.verify(resultToken, `
`new Buffer('MYCUSTOMCODELONGMOD4NEEDBEZE').toString('base64'), `
`  { algorithms: ['HS256'] },`
`  function(err, decoded) { `
`    if (err) {`
`      console.log('decode token failed with error: '+ JSON.stringify(err));`
`    }`
`  }`
`);`

I got the error: invalid signature. The resultToken content:

`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0ODU1MTk1NTYsIm5iZiI6MTQ4NDc5OTU1NiwidXNlciI6eyJ1c2VySWQiOiIxIn0sInN1Y2Nlc3MiOnRydWV9.6Uey1pt0AFXdSUZtHPvTYYqD26FQXPII1s-QpxSlSiI`

I have debug it on jwt.io with above signature and secret base64 encoded enabled, it's ok.

I have tried a signature without base64 encoded by chaging my keybytes in .net code:

`var keybytes = Encoding.UTF8.GetBytes("MYCUSTOMCODELONGMOD4NEEDBEZE");`

And it's ok. So i think the issue comes from the verify function in nodejs code. Did i miss some options when verify token or somethings?

**Comment by maxpavlov** [comment]
Yep, while jwt passes both verification and decoding on jwt.io debugger, this package is unable to process valid jwts.

**Comment by maxpavlov** [comment]
https://jwt.io/ does not verify your signature as well. Problem is on your side.

**Comment by khoachung89** [comment]
It's invalid because the expire time passed. I have change a C# code so the generated token can be valid up to 10 days. Could you help me with the below token:

`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0OTQ4MTMxMTUsIm5iZiI6MTQ3NzUzMzExNSwidXNlciI6eyJ1c2VySWQiOiIxIn0sInN1Y2Nlc3MiOnRydWV9.4bjYyIUFMouz-ctFyxXkJ_QcJJQofCEFffUuazWFjGw`

**Comment by khoachung89** [comment]
It's my fault when using Buffer. I have to create the buffer in nodejs by this way:

`new Buffer("MYCUSTOMCODELONGMOD4NEEDBEZE", "base64")`
