### ISSUE TITLE
Doubt expiresIn?

### ISSUE THREAD

**Issue by leonetosoft** [auth0/node-jsonwebtoken#307]
I would like to know something that I did not find in the documentation.
If I do not set an expiresIn the token will never expire?
As incredible as it may seem, in my case, I need a token that does not expire.
Thanks for the help.

**Comment by ziluvatar** [comment]
@leonetosoft it is an optional property. In the JWT the `exp` claim is optional. If you don't pass either `expiresIn` or `exp` you won't have any expiration claim on it.

**Comment by leonetosoft** [comment]
Thank You for your answer!
