### ISSUE TITLE
Role based authentication

### ISSUE THREAD

**Issue by sashakru** [auth0/node-jsonwebtoken#309]
Hey,

thanks for the great library.

Is there any plans for supporting role based authentication?

**Comment by ziluvatar** [comment]
@sashakru can you elaborate your need? 

At the end with this library you can pass the claims/payload you want to sign, i.e: you can pass a claim named `role` (or fully namespaced if you want to avoid collisions). Afterwards, whoever verifies the JWT can trust on the role for that user.

**Comment by jfromaniello** [comment]
@risa We validate the type for the claims defined by the spec but we do allow any other claim. That's  the `.unknown()` here:

https://github.com/auth0/node-jsonwebtoken/blob/master/sign.js#L25

**Comment by risa** [comment]
Oh great! I do not know how I could have overlooked that.  Thanks a lot, that makes my life a lot easier now.
