### ISSUE TITLE
ability to run in the client

### ISSUE THREAD

**Issue by ehartford** [auth0/node-jsonwebtoken#313]
I wanted to decode the token on the client side.
But due to dependency on joi [which has no client side support](https://github.com/hapijs/joi/issues/665), I can not use node-jsonwebtoken on the client side.

Please remove dependency on joi library to resolve this.

**Comment by ehartford** [comment]
I used [jwt-decode](https://github.com/auth0/jwt-decode) to accomplish my use case.

**Comment by gnu-user** [comment]
Thanks @ehartford I had this exact same problem, wanted to do a simple check to see if it's first expired before sending requests to the APIs.

**Comment by ziluvatar** [comment]
Thanks @ehartford for letting us know the solution as well :)

I close the issue, be free to reopen it if needed.
