### ISSUE TITLE
Options required for async signing but not sync signing

### ISSUE THREAD

**Issue by louiscenter** [auth0/node-jsonwebtoken#318]
Hey there ^__^

I wouldn't say this is a bug as I assume the following behaviour is intended, but I'm curious to know the reasoning behind it.

When synchronously creating a token, passing `options` into `jwt.sign()` is optional.

When asynchronously creating a token, passing `options` into `jwt.sign()` is required, otherwise a `ValidationError` is returned.

Why is validation is enforced one way but not the other? I scanned through the documentation but couldn't find any mention of this.

Many thanks!

**Comment by ziluvatar** [comment]
@louiscenter I created a PR to modify that, let's see if the rest see some reason to avoid `options` to be optional on `sign` method.

In the docs you can find the optional parameters wrapped by `[]`
