### ISSUE TITLE
Using decode on unverified tokens

### ISSUE THREAD

**Issue by poida** [auth0/node-jsonwebtoken#319]
Hi, the documentation for `decode` clearly states that:

`Warning: This will not verify whether the signature is valid. You should not use this for untrusted messages. You most likely want to use jwt.verify instead.`

I'd like to first decode an untrusted message to get the `kid` from the header, in order to do verification with the correct key from our metadata endpoint.

Is this safe despite the warning? How else would you do it?

**Comment by ziluvatar** [comment]
Yes, you need to read the header to realize how to verify the token, we do something similar with the `alg` header: https://github.com/auth0/node-jsonwebtoken/blob/master/verify.js#L81-L104

1. Decode & Get kid
2. Look for the right key
3. Verify with that key
4. If it is ok you know the jwt has been signed properly

Not sure how your `kid`/keys are related with the issuers, you may want to check the issuer is the expected. If you are the issuer and this is for key rotation then forget about my last sentence :)

**Comment by poida** [comment]
thx
