### ISSUE TITLE
Oauth social login and protect API with jsonwebtoken

### ISSUE THREAD

**Issue by vforv** [auth0/node-jsonwebtoken#324]
I need to allow user to login on client side(angular2) with oauth(facebook or google) and then on server side(express.js) to check user with jsonwebtokens and allow them access...

Is it possible? Could you explain me flow?

**Comment by ziluvatar** [comment]
You could take a look to these docs: https://auth0.com/docs/api-auth
You can play with it in Auth0 until you get comfortable with the idea.

In summary you would need to issue access tokens (JWT) in server side after login, then your client, as you said, will send that access token to the API endpoint which can verify the token and let the user pass.

About the "allow them access" part, depends on the granularity needed it would be enough to just verify the token or you'll need to add scopes to your JWT after login based on something (user role?) and verify those as well.

**Comment by ziluvatar** [comment]
Closing, be free to re-open it if you need more information.
