### ISSUE TITLE
Custom payload data does not decode

### ISSUE THREAD

**Issue by garethmcc** [auth0/node-jsonwebtoken#325]
Hi there,

I seem to be having an issue whereby data included within the payload when running jwt.sign is not available within the token when decoded. For example:
```
let tokenPayload = {
                    username: user.username
                };
let token = jwt.sign(tokenPayload, constructedSecret);
```

When running jwt.verify (or just running the generated token through a base64 decoder), the username data is not available. All that is available is iat and exp.

Am I misunderstanding this?

**Comment by ziluvatar** [comment]
Hi @garethmcc! Is it possible that `user.username` is `undefined`?

**Comment by garethmcc** [comment]
Sorry for the issue. It seems the problem was related to something completely unrelated. Sorry for wasting your time.
