### ISSUE TITLE
Error with RS256 algorithm

### ISSUE THREAD

**Issue by Satafur** [auth0/node-jsonwebtoken#327]
Hi guys! I am implementing jsonwebtoken but when I try to change within the options the algorithm to RS256 gives me an error without any description. Can anybody help me? For now I'm still using HS256, that's fine.
```javascript
function createToken(payload) {
        return new Promise((resolve, reject) => {
        jsonwebtoken.sign(payload, config.secret, config.options, (err, token) => {
            if(err) reject(err);
            else resolve(token)
        })
    })
}

//options 
options : {
        algorithm:'RS256',
        expiresIn:'2 d'
}

**Comment by ziluvatar** [comment]
@Satafur Weird, if you run it like: 
`createToken({ something: true}).then(console.log).catch(console.log)`

don't you get any meaningful error?

**Comment by Satafur** [comment]
@ziluvatar No, i don't get any meaningful error. it is the problem.

**Comment by ziluvatar** [comment]
Can you paste a dummy payload and secret to let me reproduce the situation?

**Comment by Satafur** [comment]
Payload is some object. Secret is a string. I has try with different strings for secret. I am working with HS256 algorithm and it is working fine.

**Comment by ziluvatar** [comment]
@Satafur is it the secret string a PEM encoded private key? Anyway I tried to run this function having a global `config` object with this content: 

`config = { secret: 'hi', options: { algorithm:'RS256', expiresIn:'2 d' }}`

And I executed: `createToken({a:1}).then(console.log).catch(console.log)`

I could see this error: `[Error: error:0906D06C:PEM routines:PEM_read_bio:no start line]`

Can you see it as well? What is your node version (probably not related).

**Comment by ziluvatar** [comment]
Closing. @Satafur be free to re-open the issue if you still have problems with this.
