### ISSUE TITLE
UTF8 encoding problem

### ISSUE THREAD

**Issue by martinmicunda** [auth0/node-jsonwebtoken#329]
Hi,

I try to decode token payload in the browser by using [b64DecodeUnicode](https://developer.mozilla.org/en/docs/Web/API/WindowBase64/Base64_encoding_and_decoding)  function however when payload contains special UTF8 character **ľ** then I get error `Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded`. The strange thing is that happend only in certain cases: 

**Doesn't throw error**
```js
const token = jwt.sign({
  firstName: "1",
  lastName: "oľ"
}, "key");
b64DecodeUnicode(token.split('.')[1]); 

const token = jwt.sign({
  lastName: "koľ"
}, "key");
b64DecodeUnicode(token.split('.')[1]);
```

**Throws Error**
```js
const token = jwt.sign({
  firstName: "1",
  lastName: "koľ"
}, "key");
b64DecodeUnicode(token.split('.')[1]);

const token = jwt.sign({
  lastName: "okoľ"
}, "key");
b64DecodeUnicode(token.split('.')[1]);
```

Does anybody know why this is happening and how to fix the issue? Thanks.

**Comment by jfromaniello** [comment]
It is not only base64 encoded but also url encoded. I did jwt-decode to handle this

https://github.com/auth0/jwt-decode

You can use it on the browser
