### ISSUE TITLE
Simple verify example using RS256

### ISSUE THREAD

**Issue by Sashkan** [auth0/node-jsonwebtoken#331]
I'd like to verify a simple token using RS256 algorithm, but I'm getting a weird error message
Here are the 2 functions I'm using to verify it
``` js
    getJSON(url: string, callback: any) {
      let xhr = new XMLHttpRequest();
      xhr.open('GET', url, false);
      xhr.onload = function() {
        let status = xhr.status;
        if (status === 200) {
          callback(null, xhr.response);
        } else {
          callback(status);
        }
      };
      xhr.send();
    }

    verifyToken = (token) => {
        let Joi = require('joi');
        let jwt = require('jsonwebtoken');

        let key = '';

        this.getJSON(
          'https://[******].eu.auth0.com/.well-known/jwks.json',
          function(err: any, data: any) {
            if (err != null) {
              alert('Something went wrong: ' + err);
            } else {
              let datas = JSON.parse(data);
              key = datas['keys'][0]['x5c'][0];
            }
          });

        let test = jwt.verify(token, key, { algorithms: ['RS256'] });
    }
```

This raises a ```Uncaught TypeError: Cannot read property '2' of null``` comeing from the ```jwt.verify```

Now at this point I'm not sure of many things in here (for some reason, most examples seem to be using HS256 algorithm). Is this the right way to pass my public key ? What's this ```property: '2' ``` about ?

**Comment by ziluvatar** [comment]
@Sashkan a couple of things:
- You have the verify out of the callback function of getJSON (maybe copy & paste issue?)
- You need to pass the key (certificate) with PEM format see [this](https://github.com/auth0/node-jwks-rsa/blob/master/src/utils.js#L1-L5)

You can take a look to this example as well https://github.com/auth0/node-jwks-rsa/blob/master/src/JwksClient.js because in your example you don't take into account the possible key rotation. (note the example is for nodeJS)

**Comment by ziluvatar** [comment]
Closing. @Sashkan be free to reopen it if you still have issues.

**Comment by adjavaherian** [comment]
I seem to be seeing the same issue.  I'm pretty stumped. 

```javascript
export const isLoggedIn = function () {

    const accessTokenStore = authClient.tokenManager.get('accessToken');
    const token = accessTokenStore.accessToken;


    const keys = 'https://myserver.com/keys';
    fetch(keys)
      .then((response) => {
          return response.json();
      }).then((json) => {


          const rawCert = json.keys.map((v) => v.n).shift();
          const cert = certToPEM(rawCert);


          jwt.verify(token, cert, { algorithms: ['RS256'] }, (err, stuff) => {
              console.log('verify callback', err, stuff); // TypeError returned here.
          });

      }).catch((ex) => {
          console.log('parsing failed', ex);
      });

};

```

```
TypeError: Cannot read property '2' of null
    at module.exports (fixProc.js?4dd0:13)
    at parseKeys (index.js?2aee:18)
    at verify (verify.js?980c:8)
    at Verify.verifyMethod [as verify] (index.js?b692:75)
    at Object.verify (index.js?79e8:89)
    at Object.jwsVerify [as verify] (verify-stream.js?182f:54)
    at eval (verify.js?0eec:116)
    at getSecret (verify.js?0eec:76)
    at Object.module.exports [as verify] (verify.js?0eec:80)
    at fetch.then.then.json (index.js?41f5:43) undefined
```

**Comment by snowinmars** [comment]
I get it.
The error message tells us about wrong private key format. If you'll check the `fixProc.js` file that appears on the callstack you'll see that the regex validation fails.
So double check that your key is valid.

**Comment by scrimmie** [comment]
Hey, for anyone that solved this issue can you please explain what format you used for the cert (key) in jwt.verify() . Did you use the private or public key and then did you create a PEM file and use that as the key in jwt.verify()? 
@snowinmars @adjavaherian

**Comment by snowinmars** [comment]
@scrimmie 
I used private key.
I push my solution, so check this out: https://github.com/snowinmars/jwt-helper
My code is a pile of shit, but it works.
