### ISSUE TITLE
Question about the key we sign with (public/private key)

### ISSUE THREAD

**Issue by roytz** [auth0/node-jsonwebtoken#332]
Hi,
As I understand from your example, the key I use when signing (`jwt.sign`) the object I want and creating the jwt is my private key which I use to encode the data I transfer to the client and then to decode (`jwt.verify`) it when I get it back.
What I don't understand is how does the client knows that the token he got is correct and that he got it from the server without anyone tempering it on the way? Is there a public key the client uses to check that the token he got is correct?

Thanks

**Comment by shai32** [comment]
So the public key is sent to the client?

**Comment by ziluvatar** [comment]
Yes and no. The client in based on the key that was used to sign the JWT (taking a look the JWT headers) will **request a/the server** (and cache?) to get the public key and then that server **will send** its public key.
That's one typical option, I'm sure there are more.

**Comment by ziluvatar** [comment]
Closing. @shai32 if you still have questions be free to re-open the issue.
