### ISSUE TITLE
JsonWebTokenError: jwt malformed

### ISSUE THREAD

**Issue by glowlabs** [auth0/node-jsonwebtoken#333]
I am getting this error when I try and verify. 

var decoded = jwt.verify(req.headers.authorization, "12345");

req.headers.authorization is giving me this value: Basic TGlua1NoYWRlc0FsZXhhOjEyMzQ1

I've tried this as well but get the same error:

var decoded = jwt.verify(req.headers.authorization.split(' ')[1]), "12345");

Any ideas?

**Comment by ziluvatar** [comment]
@glowlabs without knowing further details, it seems the requester is using [Basic authentication scheme](https://tools.ietf.org/html/rfc7617).

That is not a JWT, it is a base64 string containing "`username`:`password`".

Usually people use [Bearer scheme](https://tools.ietf.org/html/rfc6750#page-5) with JWT as token. Anyway, you need to create the token by calling first `jwt.sign()`.

**Comment by khushirana** [comment]
i am getting this type of error after running POST request

{
    "name": "NotAuthenticated",
    "message": "jwt malformed",
    "code": 401,
    "className": "not-authenticated",
    "data": {
        "name": "JsonWebTokenError",
        "message": "jwt malformed"
    },
    "errors": {}
}

**Comment by khushirana** [comment]
any ref for username/password authentication?

**Comment by AbilaJesy** [comment]
Error verifying access token: jwt malformed

this eroor present the react connected time server side terminal raise the error
