### ISSUE TITLE
Callback not called with an empty secret key

### ISSUE THREAD

**Issue by SebastienElet** [auth0/node-jsonwebtoken#335]
Actual behavior

```javascript
jsonwebtoken.sign({},'secret', { algorithm: 'HS256' }, console.log); // Works
jsonwebtoken.sign({},'', { algorithm: 'HS256' }, console.log); // Callback not called, no return
```

Expected behavior

A `sign` without secret (secret undefined or empty) should throw an error

**Comment by ziluvatar** [comment]
Yes, it's an issue in `node-jws` library, we have this other issue about this https://github.com/auth0/node-jsonwebtoken/issues/286

Thanks for reporting!! I will close it as duplicated so we can follow the other issue.

**Comment by SebastienElet** [comment]
Awesome 🎉
