### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by Brian-McBride** [auth0/node-jsonwebtoken#338]
Passing checks vs. Javascript library
Looking at this page (maintained by Auth0)
https://jwt.io/#libraries-io

I see that the NodeJS library has 5 failing checks. However, the Javascript repo https://github.com/kjur/jsrsasign has all passing checks. 

Could a maintainer of this project outline why it would be preferable or why we have two libraries that are listed here that work with NodeJS? 

Thank you very much.

**Comment by ziluvatar** [comment]
> why it would be preferable or why we have two libraries that are listed here that work with NodeJS?

The runtime target of this library is NodeJS environment, however `jsrsasign` can be run on any javascript environment, so if you need to do some work on browser your choice could be `jsrsasign`, if you need to run on NodeJS both of them could work for you.

I haven't used `jsrsasign`, it seems it has tons of functionality, I'd suggest to analyze what you need, if both libraries provide the functionality you need you'll be good in any case.

**Comment by ziluvatar** [comment]
Closing. @Brian-McBride be free to re-open it if you have more doubts.
