### ISSUE TITLE
How to force jwt.sign err

### ISSUE THREAD

**Issue by OmgImAlexis** [auth0/node-jsonwebtoken#341]
I'm writing code coverage tests for my site and I need a way to forcefully cause token.sign to throw an error. Here's a slimed down version of my code I've been using for testing. Is there anything you can recommend?

```js
import jwt from 'jsonwebtoken';
const config = {
    secret: '123'
};

jwt.sign({
    username: 'ava',
    iat: Math.floor(Date.now() / 1000) - 30 // Set issue date 30 seconds ago
}, config.secret, {
    expiresIn: 3600,
    issuer: 'wvvw.me'
}, (err, token) => {
    if (err) {
        console.log(err);
    }
    console.log({
        token,
        expiresIn: 3600
    });
});
```

**Comment by ziluvatar** [comment]
You can either mocking it or pass an invalid `config.secret`, since, you are using `HS256` (default algorithm), if you pass an object as `config.secret` it will throw an error.

**Comment by OmgImAlexis** [comment]
That'll work, thanks.
