### ISSUE TITLE
maxAge option incorrectly handles values expressed in number of milliseconds

### ISSUE THREAD

**Issue by zaak** [auth0/node-jsonwebtoken#346]
As stated in the docs:

> `maxAge`: the maximum allowed age for tokens to still be valid. Currently it is expressed in **milliseconds** or a string describing a time span zeit/ms. Eg: `1000`, `"2 days"`, `"10h"`, `"7d"`.  (...)

But if you pass a number, it's [converted to string](https://www.npmjs.com/package/ms#convert-from-milliseconds) by `ms` call [here](https://github.com/auth0/node-jsonwebtoken/blob/67550492cb3cff5fb764322563bb5864041eee5f/verify.js#L168), as there's no `typeof` check for `options.maxAge`. Because of this all the following validation logic is broken in this case.

**Comment by ziluvatar** [comment]
Thanks @zaak!! There was an [issue](https://github.com/auth0/node-jsonwebtoken/issues/273) about how using milliseconds does not match quite well with JWT, however, we didn't realize that it actually does not work. The good part is that we can fix both at same time, making the code work with number (only for seconds) right away.

**Comment by ziluvatar** [comment]
Fix: https://github.com/auth0/node-jsonwebtoken/pull/349
