### ISSUE TITLE
Signing with password-protected RSA private key

### ISSUE THREAD

**Issue by httpdigest** [auth0/node-jsonwebtoken#350]
I was just testing the online JWT token generator at http://kjur.github.io/jsjws/tool_jwt.html to use its RSA-256 private and public keys to sign and verify with both the online tool and the node-jsonwebtoken library.
Verifying a generator JWT token works fine with the node-jsonwebtoken library, however it turns out that this library cannot handle RSA private keys which are password-protected.
Is there any way to specify the password to use for the RSA private key?

**Comment by ziluvatar** [comment]
Hi @httpdigest , since this library is based on `jws` and it is using [crypto](https://nodejs.org/api/crypto.html#crypto_sign_sign_private_key_output_format), you can pass `{ key: myPrivateRsaKey, passphrase: 'mypassword' }`. 
I'll update the docs with this.

**Comment by httpdigest** [comment]
Awesome! Thank you.
