### ISSUE TITLE
Update joi dependency

### ISSUE THREAD

**Issue by jy95** [auth0/node-jsonwebtoken#351]
Hello,

I just find out this projet has an outdated version of Joi.
```js
  "dependencies": {
    "joi": "^6.10.1"
   }
```

Joi is currently in v 10.4.2 and so the used caret in package.json will not accept a 10.x.x release

**Comment by ziluvatar** [comment]
Hi!! Yeah, we had problems in the past upgrading, actually it is giving more troubles in different areas, there is a PR to remove it, we'll go that way: https://github.com/auth0/node-jsonwebtoken/pull/348

**Comment by ziluvatar** [comment]
@jy95 joi has just been removed in new release v8 
https://github.com/auth0/node-jsonwebtoken/wiki/Migration-Notes:-v7-to-v8
