### ISSUE TITLE
Algo es-512

### ISSUE THREAD

**Issue by rezadhah** [auth0/node-jsonwebtoken#354]
hello, i am tyring to sign my object literal using es512, but it keep gives me error 'Data must be a buffer' and i'm kinda new in this jwt topic.

so my object literal is :
var data = {
  type: dog,
  sound: woof
}

when i code like this : 
`jwt.sign(data , priv_key, {algorithm: 'ES512'})` ->  it returns error :  "**Data must be a buffer**"

i have tried to change my object into base64 encoding like this.
`var stringngify_data = JSON.stringify(data);
var base_64_data = new Buffer(stringngify).toString("base64");`

But unfortunately it keeps giving me error "**Data must be a buffer**"

so, what did i do wrong?

**Comment by ziluvatar** [comment]
Hi @rezadhah, that message can be misleading, I could only get it when you pass an empty object as priv_key, using node v6+.

ie: `jwt.sign({ type: 'dog' } , {}, { algorithm: 'ES256'})`

Can you check the format of `priv_key` to see if it is a PEM, or an object with the right format?

**Comment by ziluvatar** [comment]
Closing. @rezadhah reopen it if you still have the issue.
