### ISSUE TITLE
How to destroy token?

### ISSUE THREAD

**Issue by vforv** [auth0/node-jsonwebtoken#364]
Is there a way to destory the tokens?

**Comment by AnatoliyGatt** [comment]
@vforv There is no way to destroy it. You can implement black/whitelisting on your server to achieve similar to destroy behaviour.

**Comment by westy92** [comment]
@vforv use the **jti** claim so you can identify tokens and blacklist them.
https://auth0.com/blog/blacklist-json-web-token-api-keys/
