### ISSUE TITLE
User can get other user data by using his own token.

### ISSUE THREAD

**Issue by formanite-20** [auth0/node-jsonwebtoken#366]
Hi
My question is that I generate a token for User A and then another token for User B. Now when I request User A with User B token, API allowed it but payload data depict User A. I just want API to respond with 401 rather than allow it. In this way, any user can get any other user data by using his own token.
TIA

**Comment by ziluvatar** [comment]
Hi @formanite-20 I guess you are looking for the `sub` claim ([spec](https://tools.ietf.org/html/rfc7519#page-9)), which will contain an unique id for your user, in the API side you will know the user getting that claim value.
