### ISSUE TITLE
callback not triggered in 7.4.1

### ISSUE THREAD

**Issue by reduxdj** [auth0/node-jsonwebtoken#368]
Neither error or callback are triggered with the following code on node 8.1   

 jwt.sign({ foo: 'bar' }, secret, { algorithm: 'HS256' }, (err, asyncToken) => {
      console.log(err, asyncToken)
    });

**Comment by reduxdj** [comment]
happened with an undefined secret

**Comment by ziluvatar** [comment]
Thanks @reduxdj for the heads up, we already have a [bug](https://github.com/auth0/node-jsonwebtoken/issues/286) about this.
I'll close this issue to track the problem in the older one.
