### ISSUE TITLE
Tokens don't expire

### ISSUE THREAD

**Issue by rahatm1** [auth0/node-jsonwebtoken#37]
Hi,
I am creating the token like so:
`var token = jwt.sign(user, secret, {expiresInMinutes: 1});`
and verifying using:

`jwt.verify(token, secret, function(err, decoded) {
      if (err) {
          console.log(err);
      }
      else { console.log(decoded);
      }`
But, I don't see any errors after one minute and the token is successfully decoded every time. Am I doing anything wrong?

My jsonwebtoken version is 1.3.0, if that helps.

**Comment by khowarizmi** [comment]
It seems to appear again. when I change the expiresInSeconds, the token generated does not change, and never expire.
