### ISSUE TITLE
jwt.verify fails to throw error for expired tokens

### ISSUE THREAD

**Issue by Teebo** [auth0/node-jsonwebtoken#370]
I am creating a jwt like this:
`    return jwt.sign({
       some_key: some_value
    }, Authentication.secret, { expiresIn: '1s'});`

And verifying it like:

`jwt.verify(token, Authentication.secret, (err, result) => {
                if (err) {
                return res.status(400).send('Failed');
            }
                return next();
            });
        }`

When I log the decoded results, I can see something like:

` iat: 1499970792,
  exp: 1499970793 `

which looks fine I suppose, I have checked whether the token I am sending to the client is the same as the one I am verifying, all looks good..but the middleware proceeds with next(), am I missing something here?

**Comment by z2oh** [comment]
I used the following line:

```
jwt.verify(token, secret, (err, result) => { return res.status(200).send({ err: err, result: result, }); });
```

on an expired token and got this result:
```
{
    "err": {
        "name": "TokenExpiredError",
        "message": "jwt expired",
        "expiredAt": "2017-07-19T17:08:44.000Z"
    }
}
```

On a non-expired token, I got this result:

```
{
    "err": null,
    "result": {
        "data": "data",
        "iat": 1500484656,
        "exp": 1500916656
    }
}
```

which is the expected result. Maybe try logging your `err` object and seeing what's happening? Perhaps the `next()` is being called later in your code?

**Comment by Teebo** [comment]
I am using the `next()` ... snap! this is how it looks like

`        return jwt.verify(token, Authentication.secret, (err, result) => {
                if (err) {
                    console.log("Auth error", err);
                return res.status(400).send('Failed on second middleware');
                }
                return next();
            });`

I guess putting the `next()` in an `else` would cut it? thank you...

**Comment by z2oh** [comment]
If wrapping the call to `next()` in an else works then it is a fine solution, but I would imagine that the `return` statement should stop execution. Maybe there is something I'm missing, however? Give the `else` a try and see if that fixes it for you.

**Comment by Teebo** [comment]
@z2oh the `return` was not needed, thanks

**Comment by borrey** [comment]
Still not sure if this is resolved

````
jwt.verify(keyToken, publicKEY, verifyOptions, (err, result)=>{
  console.log('testToken:', 
    result, 
    result.exp - Math.floor(new Date().getTime() / 1000 ),
    err );
});
````

> testToken: { username: 'fakeuser',
  iat: 1570218102,
  exp: 1570218103,
  aud: 'sampleaudience.com',
  iss: 'Sample issuer',
  sub: 'Sample Subject' } -3 null

node version: v11.4.0
"dependencies": {
    "jsonwebtoken": "^8.5.1"
 }

**Comment by khangahs** [comment]
I hope this help someone. If you use try catch method, you need to put next() in the try. Ex:
`try {
    jwt.verify(token, "your secret", (err, decode) => {
      if (err) {
        if (err instanceof TokenExpiredError) {
          return res.status(401).send({ message: "Access token denied!" });
        }
        if (err.name === "UnauthorizedError") {
          return res.status(401).json({ error: err.name + ": " + err.message });
        }
        return;
      }
      req.user = decode;
      return next(); // !important, you need this here to run.
    });
  } catch (err) {
    return res.status(500).send({ message: err.message });
  }`

**Comment by themoenen** [comment]
Another case that made me lose some time and some hair:

`iat` needs seconds not miliseconds, so if you don't divide your date object by 1000, you will set an issue time ~55,179 years in the future and your token will never expire.

Wrong:
```
const authToken = jwt.sign(
   {
      ...
      iat: new Date().getTime()
   },
   'abcdef',
   { expiresIn: '10s' }
)
```

Correct:
```
const authToken = jwt.sign(
   {
      ...
      iat: new Date().getTime() / 1000
   },
   'abcdef',
   { expiresIn: '10s' }
)
```

Hope this will help someone some day somewhere out there.
