### ISSUE TITLE
Can't resolve 'dns'

### ISSUE THREAD

**Issue by bertolo1988** [auth0/node-jsonwebtoken#372]
#Hello,

We use jsonwebtoken in our package... today we got this:

```
ERROR in ./~/isemail/lib/isemail.js
Module not found: Error: Can't resolve 'dns' in 'mypath/node_modules/isemail/lib'
 @ ./~/isemail/lib/isemail.js 45:10-24
 @ ./~/isemail/index.js
 @ ./~/joi/lib/string.js
 @ ./~/joi/lib/index.js
 @ ./~/jsonwebtoken/sign.js
 @ ./~/jsonwebtoken/index.js
 @ ./~/@slickss/ums-client/dist/src/JwtTokenAuth.js
 @ ./~/@slickss/ums-client/dist/src/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://dev.slicktracking.com:8080 ./src/main.ts

```

Maybe you should freeze [joi](https://github.com/hapijs/joi) version in an older one.

**Comment by bertolo1988** [comment]
I did not know that jsonwebtoken does not support browsers.

**Comment by Chaoste** [comment]
opentok uses jsonwebtoken - of course it should support browser. It's just a wrong dependency ;)

see #317 \

**Comment by bertolo1988** [comment]
joi does not support browsers

**Comment by CHANDRAMOHANnegi** [comment]
delete node_modules  and paackage.lock.json    and do   npm install    or  yarn add
