### ISSUE TITLE
Just launched a new staging AWS instance of my application, JWT token expires immediately following a login

### ISSUE THREAD

**Issue by ewosleger** [auth0/node-jsonwebtoken#377]
terminal log:

`2017-08-03T03:23:59.475Z - error: 500 message=jwt expired, method=POST, url=/api/login, email=admin@admin.com, password=11111`

**Comment by ziluvatar** [comment]
@ewosleger could you give more information? How do you use the library?

**Comment by baruinho** [comment]
I'm facing the same problem here. The funny thing is last night it was working.

SO: Red Hat Enterprise Linux Server release 7.4 (Maipo)
jsonwebtoken version: 7.4.1

Basically, the token is already expired when created.

jwt.sign
```
function sign(user, options) {
  var expiresIn = options && options.expiresIn || parseInt(ms(EXPIRES_IN)/1000)
  var payload = JSON.stringify(user);
	
  return jwt.sign(user, SECRETORPRIVATEKEY, {expiresIn: expiresIn});
}
```

jwt.verify (does not throws)
```
verify(token) {
  try {
    return jwt.verify(token, SECRETORPRIVATEKEY)
  } catch(err) {
    return null
  }
}	
```

**Comment by BrOrlandi** [comment]
@ziluvatar any investigation on this issue? I think it may be a critical issue.

We tried to investigate but we couldn't find anything in the source code.

Thanks!

**Comment by ziluvatar** [comment]
Closing. Reopen it if you have further details.
