### ISSUE TITLE
Little mistake in README

### ISSUE THREAD

**Issue by shawninder** [auth0/node-jsonwebtoken#385]
I found a little mistake in the README, see https://hyp.is/49FjfoEDEee2WVfxwy1Brw/www.npmjs.com/package/jsonwebtoken

> Callback is passed the decoded payload if the signature and optional expiration, audience, or issuer are valid.

I think there is a part missing here. I'd like to propose the following new sentence as a replacement:

> Callback is passed the decoded payload if the signature is valid and optional expiration, audience, or issuer are valid.

**Comment by ziluvatar** [comment]
I understand almost the same (actually what I don't like is the "Callback is passed the decoded payload").
Anyway, I see it's clearer your way, be free to open a PR and I'll merge it.

**Comment by joovel** [comment]
@ziluvatar : I've created the PR.

**Comment by ziluvatar** [comment]
PR was merged.
