### ISSUE TITLE
Expiry Feature

### ISSUE THREAD

**Issue by chassrouny** [auth0/node-jsonwebtoken#389]
Can we add an option that whenever jwt.verify is called, if the token is verified, reset the expiry timer,

example:
var token = jwt.sign(user, process.env.SECRET_KEY, {
        expiresIn: 10
    });
token expires in 10 seconds,

If after 5 seconds i call an api and it verifies the token, reset the expiration counter, so it count for 10 seconds after the verification process and not continue the remaining 5 seconds.

Thanks in advance,
Regards

**Comment by subversivo58** [comment]
Humm ... there is a very clear reason for a token to have an expiration time ... **validation!**

I believe that this "feature" you want is more related to issue [#122](https://github.com/auth0/node-jsonwebtoken/issues/122) which is described in the [documentation](https://github.com/auth0/node-jsonwebtoken#refreshing-jwts)

A practical example (and the reason why it is not part of this lib) is described in this [gist](https://gist.github.com/ziluvatar/a3feb505c4c0ec37059054537b38fc48)
