### ISSUE TITLE
Question Even if I stopped my application, token comes back alive?

### ISSUE THREAD

**Issue by rluisr** [auth0/node-jsonwebtoken#392]
Create a jwt-token with this module and I stop the application.
But even if I restart the application, end user can access with jwt-token that is created before stopped.

Why node-jsonwebtoken can realize?

**Comment by PeppeL-G** [comment]
That's how it should work. If you don't want it to work like that, you can randomly create a new secret to sign/verify the tokens each time the application starts, but then it might be hard to use horizontal scaling (if you ever come to that).
