### ISSUE TITLE
How to exclude some router/api url from jsonwebtoken

### ISSUE THREAD

**Issue by ashrafmangalore** [auth0/node-jsonwebtoken#395]
I am using node.js express app. jsonwebtoken for authentication. I want to exlude some api url from the jsonwebtoken verification. below is what I have tried and my code

    router.use('/authentication', mountAllRoutes(authenticationModule));

    // route middleware to verify a token
    router.use((req, res, next) => {
    const r = req;
    const token = req.body.token || req.query.token || req.headers.authorization;
    // decode token
    if (token) {
        // verifies secret and checks exp
        jwt.verify(token, (req.app.get('superSecret')), (err, decoded) => {
            if (err) {
                // res.json({ success: false, message: 'Failed to authenticate token.' });
                res.status(401).send({
                    success: false,
                    message: 'Failed to authenticate token.'
                });
            } else {
                // if everything is good, save to request for use in other routes
                r.decoded = decoded;
                next();
                // console.log(decoded);
            }
            return {};
        });
    } else {
        // if there is no token
        // return an error
        return res.status(403).send({
            success: false,
            message: 'No token provided.'
        });
    }
    return {};
    });

    router.use('/test', mountAllRoutes(testModule));
    router.use('/other', mountAllRoutes(otherModule));
    router.use('/data', mountAllRoutes(dataModule));

Here I have placed routes above middleware which I dont want to protect. and I have placed after middleware which I want to protect. But it is protected which I placed above middleware. In **authenticationModule**, login and user registration api comes. so for user registration it gives response **no token provided**

![image](https://user-images.githubusercontent.com/28133954/30270660-fb0f3dc8-970a-11e7-85ee-65321b7e8200.png)

**Comment by ziluvatar** [comment]
@ashrafmangalore I think you may like: https://github.com/auth0/express-jwt/

**Comment by TheGitPanda** [comment]
Another quick solution
https://github.com/nuxt-community/auth-module/issues/211#issuecomment-401486864
