### ISSUE TITLE
Undocumented breaking change in version 8

### ISSUE THREAD

**Issue by wraithgar** [auth0/node-jsonwebtoken#396]
With the introduction of a `lodash.isplainobject` check on the object being signed, a tighter constraint is now in place than there was in version 7, which was using `Joi.object()`

It would be helpful if this were added to the [migration notes for v7 to v8](https://github.com/auth0/node-jsonwebtoken/wiki/Migration-Notes:-v7-to-v8l)

**Comment by ziluvatar** [comment]
@wraithgar thanks! I've updated the wiki page, could you take a look to see if that's clear enough?
Be free to put here any modification you think could help consumers to make them realize about it.

**Comment by wraithgar** [comment]
That's great, thank you so much for updating it.  It seems pretty clear to me and I think it would be to someone else in my position.
