### ISSUE TITLE
node-jsonwebtoken & redis

### ISSUE THREAD

**Issue by rluisr** [auth0/node-jsonwebtoken#397]
I want to manage jwt with redis.

create, verify token using `node-jsonwebtoken` and want to send redis server.
Is it possible?

**Comment by rluisr** [comment]
My api servers are using this module and many server is running using load balancer with sticky footer.
But on-premises server and public cloud(ec2 instance) can't share jwt.

I want to store the JWT token to redis and all my api servers include ec2 instances share it.
Is it possible?

**Comment by ziluvatar** [comment]
What's the reason towards the thought of storing the JWT?

Initially, leaving apart the blacklisting for now, you don't need to store the JWT, it will contain the needed information to trust the issuer + identify the user + authorize the user.
Probably I'm missing something about your use case.

**Comment by rluisr** [comment]
My infrastructure is hybrid cloud.
So the api servers always are running on my office but sometimes the api servers are running on AWS when incidents are occured.
Then client have to re-login, the api servers will get high load.

I think need the store the JWT on one place in order to solve this problem.

**Comment by ziluvatar** [comment]
You API should use the JWT in stateless manner for verifying the tokens. 
User A gets a token "A1" and sends it to you API server (at your office).
15 min after, incident happens, AWS servers run up and your office is unreachable.
User A sends token "A1", AWS API servers should be able to verify it.

Can you write some kind of diagram or sequence example like ^ ?

FYI similar question: https://github.com/auth0/node-jsonwebtoken/issues/207

**Comment by ziluvatar** [comment]
Closing. @rluisr let's reopen if you need to.
