### ISSUE TITLE
Same tokens within a second

### ISSUE THREAD

**Issue by olegmdev** [auth0/node-jsonwebtoken#399]
Because of this line:
https://github.com/auth0/node-jsonwebtoken/blob/cc0f4d67b649110a035db3df9265f05db269a15a/lib/timespan.js#L4

In case you call `sign` method multiple times within 1 second with the same payload, you'll get exactly the same token every time you sign it which is not cool as for me.

What do you think about changing that behavior (iat) to keep tracking milliseconds instead of seconds?

This way tokens will be different.

**Comment by kjvalencik** [comment]
@olegmdev The "Issued at" or `iat` claim is defined in the RFC as seconds. https://tools.ietf.org/html/rfc7519#page-6

It is not intended to provide uniqueness. If you require uniqueness in your claim, this is what the "JWT ID" (jti) claim provides. https://tools.ietf.org/html/rfc7519#section-4.1.7

You can provide a random value to ensure uniqueness.

```js
import crypto from 'crypto';

{ jwtid : crypto.randomBytes(16).toString('hex') }
```
