### ISSUE TITLE
How to revoke token after logout ?

### ISSUE THREAD

**Issue by booradleys** [auth0/node-jsonwebtoken#401]
Hi there,
How to revoke token after logout ?
I saw this module but it is available for express-jwt module:
https://github.com/layerhq/express-jwt-blacklist

**Comment by ziluvatar** [comment]
👋  Take a look to:
https://github.com/auth0/node-jsonwebtoken/issues/103
https://github.com/auth0/node-jsonwebtoken/issues/99
