### ISSUE TITLE
Using Firefox and Safari, jwt.verify raises Error.capturestacktrace is not a function

### ISSUE THREAD

**Issue by TLX3** [auth0/node-jsonwebtoken#402]
I've started testing my application outside of Chrome and started receiving the error regarding Error.capturestacktrace is not a function.

I have both the latest Firefox and Safari. The token verification works fine on the latest version of Chrome. This error occurs specifically after the token is expired and I attempt to verify it. 

The token verification below is executed during specific route transitions on the client side. The  error caused prevents me from logging inside of the verification callback.

```javascript
 jwt.verify(
      token,
      secret,
      function(err, verifiedJwt) {
        if (err) {
          if (
            err.name === "TokenExpiredError" ||
            err.name === "JsonWebTokenError"
            ) {
            next("/logout");
        }
      } else {
          //Refresh token if it is not expired
          store.dispatch("REFRESH_TOKEN", token);
        }
      }
  );
```

**Comment by joovel** [comment]
@ziluvatar : I've added a PR to ensure that `captureStackTrace` is truthy before attempting to call it.

**Comment by joovel** [comment]
@ziluvatar : I'm also curious if browser support is a thing for this project ... both this repo and jws specifically call out node, but there's no explicit statement in the README whether browsers are supported or not.

**Comment by ziluvatar** [comment]
This project focus is NodeJS, nevertheless since the community seems to be using it for browsers, we balance the issue, the effort to maintain node vs browser and it makes sense.

**Comment by ziluvatar** [comment]
PR was merged. It's on v8.1.0

**Comment by TLX3** [comment]
Thanks!
