### ISSUE TITLE
Client Build

### ISSUE THREAD

**Issue by Austio** [auth0/node-jsonwebtoken#405]
Hello, thanks so much for the library.

Would you be open to a PR for a client build that does minification and such?

**Comment by ziluvatar** [comment]
I'm not quite against that, however, since its focus is NodeJS (although it can be used in browsers), probably it's better to leave that work to the consumer.
Thoughts?

**Comment by Austio** [comment]
Hey, well thought is that wouldn't be a ton of maintenance to provide some builds.  Users could import from the minified build dist instead of standard.  Or maybe the client build would be best as a separate package.  browser-jsonwebtoken or something that wraps this library and npm distributes it.  

I use this in an isomorphic app so like having both really (easy access to readable source on server and then small build for client)

**Comment by ziluvatar** [comment]
I would rather like doing it in different project. Apart from the minification you could use it as repo for the community that uses it in browser (not sure what for but I'm sure it'll be useful).

**Comment by crawforde** [comment]
Another use case for a minified build is for testing in AWS Lambda.
