### ISSUE TITLE
Remove PEM files from npm

### ISSUE THREAD

**Issue by Mottie** [auth0/node-jsonwebtoken#411]
Please remove the test folder, or just the PEM files in the test folder, from the node package - these can be excluded by adding it to a `.npmignore` file.

I am working on a WebExtension and using [`web-ext`](https://github.com/mozilla/web-ext) which includes this module. When I attempt to "Load unpacked extension..." into Chrome, I see the following warnings <del>and can not load the extension</del> until I manually delete the `test` folder from this module.

![](https://user-images.githubusercontent.com/136959/31051743-63a4a4a6-a636-11e7-8e4c-02b0f5fdf2bc.png)

Update: I misspoke. I *can* run the extension while these warnings are shown.

**Comment by ziluvatar** [comment]
It's strange, in the v8.0 there was a change to fix that: https://github.com/auth0/node-jsonwebtoken/blob/master/package.json#L46-L51

I've just downloaded the package (with `npm i`) and this is what I see:
<img width="114" alt="screen shot 2017-10-09 at 3 15 49 pm" src="https://user-images.githubusercontent.com/1424663/31339951-cea73e6a-ad04-11e7-88f8-8d1d68f6c6b3.png">

Are you using v8.0?

**Comment by Mottie** [comment]
Sorry for not responding earlier, yes I was using v8.0+ (I'm currently using v9.2.0). I am still seeing the reported `.pem` files included when I install the module.

**Comment by ziluvatar** [comment]
🤔 Current last version is v8.1.0.

From npm: https://docs.npmjs.com/misc/developers
> If, given the structure of your project, you find .npmignore to be a maintenance headache, you might instead try populating the files property of package.json, which is an array of file or directory names that should be included in your package. Sometimes a whitelist is easier to manage than a blacklist.

So both of them should provide the same result.

What do you see if you do a `npm install`? Can you see the `test` folder? I wondering if the installation is different inside the WebExtension system you mentioned. What about other installed modules, does it respect their package json "files" property?

**Comment by Mottie** [comment]
Well, if I `npm install jsonwebtoken` directly, I don't see the test folder; but when I `npm install web-ext` I do... it appears that module is still using v7.1.9. So once they update it should fix the problem. Thanks!
