### ISSUE TITLE
User info in payload interchanging with other Users?

### ISSUE THREAD

**Issue by ankush38u** [auth0/node-jsonwebtoken#414]
Hi Team,

I've noticed a quite strange issue on our Android app, Some of the users are seeing someone else's profile. The api uses jsonwebtoken for authorization.

The implementation is quite similar to this article: https://scotch.io/tutorials/authenticate-a-node-js-api-with-json-web-tokens

We have a middleware which intercept requests and check if the auth token is valid, if it is valid then adds the payload to the request.
Code

```js
var router = express.Router();


// ------- ROUTE MIDDLEWARE START ----//
router.use(function(req, res, next) {
    //check header or url parameters or post parameters for token.
    var token = req.body.token || req.query.token || req.headers['x-access-token'];

    // decode token
    if (token) {

        // verifies the scret and checks expiration
        jwt.verify(token, app.get('superSecret'), function(err, decoded) {
            if (err) {
                res.status(400).json({
                    success: false,
                    message: 'Session Expired, Please Relogin.'
                });
                //	return next();  //dont send next() here as we return the response needed.
                return;
            } else {
                // if everything is good, save to request for use in other routes
                //var decoded = jwt.decode(token, {complete: true});
                //req.doc = decoded.payload;

                req.doc = decoded;
                // console.log(decoded);
                return next();
            }
        });
    } else {
        // if there is no token
        // return an error

        return res.status(403).send({
                success: false,
                message: 'Please Login to access this Service.' //no token provided
            })
            //dont send next here if no token is provided.
    }

});
// ------- ROUTE MIDDLEWARE END  ----//
```

Then in Endpoint implementation for get profile.

```js
router.get('/profile', function(req, res) {
    user.findOne({
        _id: req.doc._id
    }, function(err, data) {
        if (err) {
            console.error(err);
            return res.status(400).send({
                message: err.message,
                status: false
            });
        }
        if (data) {
            data.user_password = null;
        }
        return res.send(data);

    });

});


module.exports = router;
```

The above code implemetation is for User module, router is exported by module.exports 

and in main app.js

```js
var express 	         	= 		require('express');
var app	 = module.exports   =		express();
var port 			=		process.env.PORT || 3000; 		//used to create, sign and verify token
mongoose.connect(config.database);							// connect to our database
app.set('superSecret', config.secret);	
app.set('config',config);                                      

app.use(bodyParser.urlencoded({extended: true}));
app.use(bodyParser.json({}));

//adding all the modules or routes we have
app.use('/user',require('./routes/user'));        //pass router object of user module
app.use('/admin',require('./routes/panel_user'));  //pass router object of panel_user module
app.use('/news',require('./routes/news'));  		//pass router object of news module

app.listen(port);
```

I have tried digging into our implementation but can not find something wrong app was running good from an year, no one reported such issue recently 2 users have reported that they are seeing someone else's profile. I'm not able to reproduce the issue on my own, it could have been payload is being mixed of 2 different authtoken's signed by jwt due to whatever reason? or server load?

We are refreshing the token on each app start if user's token is not expired he is allotted a new one on app start with 15 days expiration time, old token is just discarded and not added into any blacklist or so and if his token is expired he is expected to login again in that case.

**Comment by Austio** [comment]
Hello, not a maintainer but just speculating, what you are describing could be happening when generating/signing the jwt if you are using an object reference to create the jwt user instead of regenerating it using a function or new object each time.   Could you add you section for login?

**Comment by ankush38u** [comment]
@Austio 

Here is the login section 
```js
router.post('/login', function(req, res) {
    var regex = new RegExp(req.body.user_email, "i")
    user.findOne({
        'user_email': regex
    }, function(err, docs) {
        if (!docs) {
            // if email is not selected
            return res.status(400).json({
                success: false,
                message: 'Sorry, Email is not registered'
            });
        } else {
            if (docs.user_verified) {
                // user have verified email account
                if (!passwordHash.verify(req.body.user_password, docs.user_password)) {
                    res.status(400).json({
                        success: false,
                        message: 'Authentication failed. Wrong Password'
                    });
                } else {

                    var payLoad = {
                        _id: docs._id,
                        email: docs.user_email,
                        user_name: docs.user_name,
                        create_time: new Date().getTime()
                    }
                    var token = jwt.sign(payLoad, app.get('superSecret'), {
                        expiresIn: "15d" // expires in 15 Day
                    });
                    res.json({
                        success: true,
                        message: 'Login Successful',
                        user_name: docs.user_name,
                        user_score: docs.user_score,
                        user_image_url: docs.user_image_url,
                        token: token
                    });





                }
            } else {
                // user have not verified email account

                res.status(400).json({
                    success: false,
                    message: 'Authentication failed. Account not yet verified'
                });
            }

        }

    });



});
```




The logic to refresh token on app restart

```js
router.post('/onappstart', function(req, res) {

    var currentVersionCode = config.currentVersionCode;
    var forceUpdate = false;


    var token = req.body.token || req.query.token || req.headers['x-access-token'];
    if (token) {

        // verifies the scret and checks expiration
        jwt.verify(token, app.get('superSecret'), function(err, decoded) {
            if (err) {
                return res.send({
                    versionCode: currentVersionCode,
                    forceUpdate: forceUpdate,
                    token: null
                });
            }
            if (!decoded) {
                return res.send({
                    versionCode: currentVersionCode,
                    forceUpdate: forceUpdate,
                    token: null
                });
            }
            var payLoad = {
                _id: decoded._id,
                email: decoded.user_email,
                user_name: decoded.user_name,
                create_time: new Date().getTime()
            }
            var newToken = jwt.sign(payLoad, app.get('superSecret'), {
                expiresIn: "15d"
            }); // expires in 15 Day
            return res.send({
                versionCode: currentVersionCode,
                forceUpdate: forceUpdate,
                token: newToken
            });
        });

    } else {
        return res.send({
            versionCode: currentVersionCode,
            forceUpdate: forceUpdate,
            token: null
        });
    }


});

```

**Comment by ziluvatar** [comment]
I can not see anything that could lead to a problem in the library. If I were you I would add some logging around:
```
var regex = new RegExp(req.body.user_email, "i")
    user.findOne({
        'user_email': regex
    }, function(err, docs)
```
You are getting only the first one which matches a regex, if a user is using dots you could have collisions: `ziluvatar@...` vs `z.luvatar@...` or, since it is case insensitive `ziluvatar@...` and `ZILUVATAR@..`
I would remove that `findOne` and use a `find` and log if you get more than one result.

**Comment by ankush38u** [comment]
@ziluvatar Thanks for the response.

But this shouldn't be the case as the users who sometimes seeing other's profile, two of them sent me the details and email of other users what they see is quite different from their, ie there is not a 1 % chance of this being the case.

This is quite random and no links are there between user emails.

In app start, the token refreshing code, I'm not adding the old tokens to any blacklist or so, I didn't want to go an extra mile, while I was deleting the old token on client, I felt there was no need. Could that some how affect this?

Server load is also not huge, that shouldn't be the reason that the middleware which validates the token and assign user to the request may have been the culprit here?


I'm out of clues here, the code I've seems pretty standard to me, but this is happening and making me panic. Please help me out. :'(

**Comment by ziluvatar** [comment]
> In app start, the token refreshing code, I'm not adding the old tokens to any blacklist or so, I didn't want to go an extra mile, while I was deleting the old token on client, I felt there was no need. Could that some how affect this?

If a user is using a non-blacklisted-but-valid access token from other user that could be possible, of course, that would be an attack (someone stole the access token at some moment), I mean, if you can leave that option apart it would be better.

I have to say it's risky to have long lived access tokens even with blacklisting. But I don't think this is an attack, otherwise the attacker wouldn't have reached you to say "Hey I see other person profile".

I honestly don't know how to help you, try to analyse those users, check your logging system. Maybe adding more around to help you find the issue. Logs are your friends :)

**Comment by ankush38u** [comment]
@ziluvatar I'll care about that much security later, for now if an android user is rooted then only he can see his access token stored in shared prefrence (sort of local storage), and no one else can see that without having his device and also need to be rooted. So caring about that case isn't important for me until i increase my team size.

I also increased server configuration, but the issue was not solved. Alas.. And those users are not some attacker, they were just trying to help, and it is more than one case. So can not be attacker reporting the issue himself.


Everyone else, and also the maintainer please check into the code if you find something unusual, please help me out. This is on highest priority for us, some of the users are Angry but we are unable to help them out. :(

**Comment by ziluvatar** [comment]
@ankush38u I'm going to close this issue, I'm curious if you finally got this solved and how, be free to share it.

**Comment by LoicVerrall** [comment]
@ankush38u did you ever figure out the culprit here, by any chance?

**Comment by ankush38u** [comment]
Hi Guys

I see every now and then people landing on this thread and reaching out to me for a solution. Instead of reverting individually, I decided to share the workaround here.

The solution is pretty simple, instead of req object, add the decoded doc or any user information to the res.locals 
for example instead of 
req.doc = decoded;

use
res.locals.doc = decoded;

The request object sometimes behaves odd, while res.locals is the right way to go for such use cases, where we need to save some data related to particular request.
