### ISSUE TITLE
RS256 key verification on firebase functions

### ISSUE THREAD

**Issue by odarbelaeze** [auth0/node-jsonwebtoken#416]
I'm trying to use jwt key verification on a firebase cloud function, asymmetric signing is the only way I see to secure one of those apps.

So, I created the function and used `jwt.verify` as stated in the commonsJS instructions, and my key wouldn't verify, the error from `jsonwebtoken` is empty.

```js
{
    "PUBLIC_KEY": "\n-----BEGIN RSA PUBLIC KEY-----\nMIIBCgKCAQEAp6aWR0qcqFeCmK/lxgYfrTSXx7/WTpBqSp18TbLcjr1QV4kyxswG\n+QzDl7EITokSd3yvI6eMbv6NxkRqumG7M50mNKm6DljRMh26/R4z17r4IFgNZr60\nFQ48cHWE7xl5O4INSyjHGIK6vHepDsbHeGJNYAbeNTB0F9CHl6TKYeZNAnYVykPd\nC3/Wp5TzLNP6KgDvGMlyLHh1ZyF0Xau+bupGvvMfnL9hw04/Y7eCr8knVFOVfC5e\nlNt6NMxKtjutm/EqLW49tZRvVG5IvNhFmr2G4QzmRT6WmaWgq19L9eZ4S4qoDsYe\nE7SE3LWqBPR/O3L8GCw9wJEeG+A75k/QqwIDAQAB\n-----END RSA PUBLIC KEY-----\n",
    "err": {},
    "message": "invalid token",
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJlaWQiOiJBTkFETUlOU0VJRCIsImlzX2FkbWluIjp0cnVlLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZXMiOiJhZG1pbiJ9.P_VOXMgFz3N38qEx7W_8m4fgmj0pQsy1pICMnDsmr9waXhsI12bQqEuJlrSMx3DEj5OLXpxzrOd2HVAPkb0FbZB-MaWOmX_GTAMK-aVfo41skGeCZ3ACOX_S_gmHc6obcVljKtlQsgc5z1JyOvHc7aMPAG4O23Dkbm5sfwrBaiOmhxPFCEkNL0AEWbo-KG_UU_v3iVM0j68NVMvmtTyrfefw0dOHCbkzZrOTet6hGT8Rlg3LFHgE07zCnm1KOTqac4Co3Qcy8LefKcNPHO4IrASxDeJqKbTumGtFsbpBZjK7FnyR7OvPJL75mBrDMi1na8L1LeAlYomcgUP9qka0wg"
}
```

here's the code https://github.com/tech-teach/noob-holdings/blob/master/functions/index.js, and above there's an example of token, if you happen to need to sign more, here's the sample private key I'm using https://github.com/tech-teach/jwt-authentication/blob/master/auth/rsa-key.

You can post to the function at: https://us-central1-noob-holdings.cloudfunctions.net/addMessage

Any help debugging this one would be greatly appreciated.

**Comment by ziluvatar** [comment]
I have just tested with your public/private key and that token, I didn't get any error, I've modified the token to make it return error and I get: 
`{ [JsonWebTokenError: invalid signature] name: 'JsonWebTokenError', message: 'invalid signature' } `

Did the code work well locally for you? What version of jsonwebtoken are you using?

**Comment by odarbelaeze** [comment]
Ok, here's my version deal, I have the token working on a react app with the next entry in `package.json`:
```
  "dependencies": {
    "jsonwebtoken": "^8.0.1",
```
and resolves to (by looking to my `yarn.lock`):
```
jsonwebtoken@^8.1.0:
  version "8.1.0"
```

In my firebase functions project, I have the same entry in `package.json`, however, I do have 2 entries in `yarn.lock`, one of them referencing an older version of `jsonwebtoken`:

```
jsonwebtoken@7.1.9, jsonwebtoken@^7.1.9:
  version "7.1.9"
```

In the react app, I was able to run with:
```
const TOKEN = `
-----BEGIN RSA PUBLIC KEY-----
...
-----END RSA PUBLIC KEY-----
`;
```

in the one that resolved to 7, I built a little example and realised that the `pem` key could not be read, hence the silent error, and it was solved by trimming the `\n` at the beginning and end of the public key.

```
const TOKEN = `
-----BEGIN RSA PUBLIC KEY-----
...
-----END RSA PUBLIC KEY-----
`.trim();
```

that did the trick, it maybe worthwhile to back-port that trim to earlier versions of the project. Here's the diff that made it work for me https://github.com/tech-teach/noob-holdings/commit/d8962ed5d0112ee3e3f9e801524bdc1810908da9
