### ISSUE TITLE
Clustering and jwt

### ISSUE THREAD

**Issue by pokatomnik** [auth0/node-jsonwebtoken#420]
If I have more than one instance, jwt.sign(...) can be executed on first instance, but verified (jwt.verify) on another one. Could you provide a simple example how to solve this? Should I handle common 'unauthorized' error on client side, authorize with my authorization route, /login, for example and repeat protected request or you know how to do it better?

**Comment by ziluvatar** [comment]
> If I have more than one instance, jwt.sign(...) can be executed on first instance, but verified (jwt.verify) on another one. Could you provide a simple example how to solve this?

I'd say this is the normal usage for JWT, one service (Authorization Server?) will create the JWT (jwt.sign) and a different one (API? Client?) will verifiy it (jwt.verify). 
Of course this would also work if the same backend that signs the token verifies it as well.

Not sure if I understand the problem. The one verifying the token should be the one that raises the error.

**Comment by pokatomnik** [comment]
What if REST server and authorization server is the same application? Is it a bad practice for small web app? I am not planning to divide my app into auth server and app server.

**Comment by rwoody** [comment]
No, it is not bad practice for a small application

**Comment by ziluvatar** [comment]
Yes, as @rwoody that's ok. 

Coming back to the original question, every protected resource (it does not matter whether or not it is located in the same server that generated the token) should verify the JWT and return error, the client would see that error and start the login process to get a new token. 
I think that is what you already thought.
