### ISSUE TITLE
why tips me "PEM_read_bio:no start line"

### ISSUE THREAD

**Issue by xulayen** [auth0/node-jsonwebtoken#422]
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at Sign.sign (crypto.js:283:26)

**Comment by ziluvatar** [comment]
Be sure you use the private key to sign and public key to verify.

We have some example in tests, just in case the format is incorrect or not well loaded:
https://github.com/auth0/node-jsonwebtoken/blob/master/test/rsa-public-key.tests.js
You can also check the keys in the test folder.

Similar: https://github.com/auth0/node-jsonwebtoken/issues/400
