### ISSUE TITLE
Vulnerability RSA PublicKey

### ISSUE THREAD

**Issue by kodenix** [auth0/node-jsonwebtoken#423]
Hello, i see this old article [](https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/) when seggest add an algorithm parameter to their verification function how `verify(string token, string algorithm, string verificationKey)` for prevent attack with RSA publicKey but i not see the param algorithm or similary is required on verify function.
This vulnerabilities ir resolved on node-jsonwebtoken library??
How i prevent this problem on this library if not verified the used algorithm 

Best reegards

**Comment by ziluvatar** [comment]
If you don't pass any algorithm to the verify function, the library will try to infer which one it is based on the secret/public-key you passed to it:
https://github.com/auth0/node-jsonwebtoken/blob/master/verify.js#L67
