### ISSUE TITLE
Will the token expire by a default time?

### ISSUE THREAD

**Issue by gijo-varghese** [auth0/node-jsonwebtoken#425]
I was using following code to create a token:
`jwt.sign({ customer_id: data.id }, 'sssh')`

However, after some time I got an error saying that the token got expired:
```
"errors": [
    {
      "message": "jwt expired"
    }
  ]
```
Is there a default expiry time like 1hour or so?
What should I do so that the token will never expire? (Becuase I set the expiry in cookies)

**Comment by ziluvatar** [comment]
There is no default expiration. I guess you need to share your verification code instead, since that `sign` only add the `iat` claim for no options case.

**Comment by gijo-varghese** [comment]
It was something else. Its working fine now. Thanks :)
