### ISSUE TITLE
IAT not appearing in header

### ISSUE THREAD

**Issue by russmilburn** [auth0/node-jsonwebtoken#431]
I am create a JWT that contains the following options information
```
options = {
      algorithm: 'RS256',
      header : {
      exp : Math.floor(Date.now() / 1000) + (60 * 60),
        iat : Date().now,
        jti : ABCD,
        iss : 'me'
  }
}

jwt.sign(payload, privateKey, options);
```
but when i decode it i get my IAT never appears in the header it appears in the payload.

```
{
  "alg": "RS256",
  "typ": "JWT",
  "exp": 1513044340,
  "jti": "ABCD",
  "iss": "me"
}
```
is this a bug? or is this standard practice?

**Comment by joovel** [comment]
In the snippet you posted, you give `iat` the value `Date().now`, but that's undefined because `Date()` returns a string, which doesn't have a `now` property. You probably want `Date.now()`, like you have for the `exp` claim.

**Comment by ziluvatar** [comment]
Apart from what @joovel mentioned (good catch by the way). All the claims you are adding inside `options.header` should be in the payload of the JWT not in the header. Not sure if there is a particular reason for your use case to do that.
