### ISSUE TITLE
Error: Could not authenticate request invalid_grant: Invalid JWT Signature.

### ISSUE THREAD

**Issue by jabbar86** [auth0/node-jsonwebtoken#432]
**Index.js**

`const multer = require('multer');
const gcs = require('@platoai/multer-gcs');
var path=require('path');
var express=require('express');
var bodyparser=require('body-parser');
const app = express();

app.get("/", (req, res) => {
	  res.sendFile(path.join(`${__dirname}/index.html`));
	});
const storage = gcs({
  filename: function(req, file, cb) {
    cb(null, file.fieldname + '-' + Date.now());
  },
  bucket: 'fenchy100',
  credentials: require('C:/Users/memon/Downloads/FenchyImage-f8ed647b7099.json'),
  // optional metadata to add to the file
  metadata: {
    contentType: 'audio/wav'
  },
  // optional, passed to the @google-cloudg/storage `getSignedUrl` method
  // defaults to:
  urlConfig: {
    action: 'read',
    expires: new Date(new Date().getTime() + 7 * 24 * 60 * 60 * 1000),
  },
  // optional, see: https://cloud.google.com/storage/docs/access-control/lists
  // defaults to:
  acl: 'publicRead',
});

const gcsUpload = multer({storage: storage});

app.post('/upload', gcsUpload.single('file'), function(req, res, next) {
  res.send('File was uploaded successfully!');
});
const PORT = process.env.PORT || 8080;
app.listen(PORT, () => {
  console.log(`App listening on port ${PORT}`);
  console.log("Press Ctrl+C to quit.");
 });
`

**Package.Json**

`"dependencies": {

    "@google-cloud/storage": "^1.5.1",
   
     "@platoai/multer-gcs": "^1.1.0",

    "express": "^4.16.2",

    "express-jwt": "^5.3.0",

    "gcloud": "^0.36.0",

    "google-cloud": "^0.57.0",

    "grpc": "^1.7.3",

    "grpc-tools": "^1.6.6",

    "jsonwebtoken": "^8.1.0",

    "multer": "^1.3.0",

    "restify": "^6.3.4"

  },

  "devDependencies": {

    "webpack-babel-jest": "*",

    "jest-cli": "*",

    "babel-cli": "^6.26.0",

    "babel-preset-es2015": "^6.24.1",

    "babel-preset-stage-2": "^6.24.1"

  }`

![screenshot 15](https://user-images.githubusercontent.com/15046804/33871742-d2acb4ce-df39-11e7-917a-a90fd53e6d28.png)

**Comment by joovel** [comment]
First, the error stack doesn't seem to include this library -- it looks like google's library that's throwing the error.
Second, the credentials passed to `gcs` appear to be stashed in a JSON file you didn't include; I would expect issues reported here to have explicitly called this library at some point in the sample.

Without more information, I would bet that the JSON file with the credentials is _probably_ corrupted or the signature has already expired. Paste the token at jwt.io and it'll help troubleshoot the actual token.
