### ISSUE TITLE
Signing a payload with a `iat` results in an invalid `nbf` value

### ISSUE THREAD

**Issue by MitMaro** [auth0/node-jsonwebtoken#435]
Related Issue: #142 
***
## Problem Description

The calculation of `payload.nbf` does not use `payload.iat` when `notBefore` is passed an offset, and instead the current time is always used.

## Expected

In this case I would expect that the `payload.nbf` value to be an offset based on the passed `payload.iat`. This would be consistent with `payload.exp`.

## Reduced Test Case

```
const {sign, decode} = require('jsonwebtoken');
const token = sign({foo: 'bar', iat: 100}, 'secret', {notBefore: '-1s'});
const decoded = decode(token);
console.log(`Expecting nbf value ${decoded.nbf} to equal 99`);
> Expecting nbf value 1513884708 to equal 99
```
## Investigation

It seems that the `timestamp` is not passed to `timespan` function on [Line 148 of sign.js](https://github.com/auth0/node-jsonwebtoken/blob/bb27eb346f0ff675a320b2de16b391a7cfeadc58/sign.js#L148) similar to how it is passed to the call on [Line 155 of sign.js](https://github.com/auth0/node-jsonwebtoken/blob/bb27eb346f0ff675a320b2de16b391a7cfeadc58/sign.js#L155).

**Comment by MitMaro** [comment]
I would be willing to put up a PR fixing the issue with tests if this is not by designed.

**Comment by ziluvatar** [comment]
@MitMaro I think this simply wasn't fixed when the timestamp was introduced for `exp`. https://github.com/auth0/node-jsonwebtoken/issues/217. Be free to send a PR.
