### ISSUE TITLE
expiresIn is not working as expected, token is not expired or always expired when working with seconds

### ISSUE THREAD

**Issue by syberkitten** [auth0/node-jsonwebtoken#436]
Any number of seconds provided to expiresIn ->
the token never expires.

either expiresIn: 1
either expiresIn: "1s"

ps. does not matter if it's 1 second or more.

**Comment by syberkitten** [comment]
also looks like expiresIn when provided a number, is treating it as milli seconds
and not seconds, so values has to be multiplied by 1000 to actually be seconds.
(documentation states expiresIn gets "seconds" as number)

In the below example
even when the exp is above iat
but is less then the actuall timestamp (Date.now)

The token is parsed and not expired.

do I need to check for expiry manually?
(Date.now() < exp)

`
{
  "iat": 1515078084415,
  "data": {
  },
  "exp": 1515078085415,
  "aud": "1",
  "iss": "issuer",
  "sub": "2"
}
`

**Comment by syberkitten** [comment]
Ive found the reason for the discrepency.
when not providing "clockTimestamp"

inside [verify.js](https://github.com/auth0/node-jsonwebtoken/blob/81501a17da230af7b74a3f7535ab5cd3a19c8315/verify.js#L36)

If "clockTimestamp" is not provided, the default time is interpolated to seconds.
Then later on line ([175](https://github.com/auth0/node-jsonwebtoken/blob/81501a17da230af7b74a3f7535ab5cd3a19c8315/verify.js#L175))

clockTimestamp is compared to maxAgeTimestamp
but maxAgeTimestamp is always in milli-seconds, while clockTimestamp is in seconds.

So it will never be greater the maxAgeTimestamp, therefore token is never expired.

Workaround:
always provide clockTimestamp to verify method,
unless the bug is fixed :)

**Comment by syberkitten** [comment]
It also looks like when providing both expiresIn and maxAge
in seconds, there is some problem with timespan.js
where the diff is always translated to mili seconds.

supplying maxAge as 4 or '4s' and expiresIn as 10 or '10s'
does not calcalate maxAgeTimestamp properly,
having the maxAgeTimestamp equal 4 (mili seconds) behind clockTimestamp
and is expired too soon.

**Comment by syberkitten** [comment]
I'll have to rely on manual checking for expiry until
these issues are resolved.

it is very easy to reproduce:

1. sign a token with expiresAt: '10s'
2. do a sleep(3) - (optional)
2. verify it with maxAge: '4s' (lets call it variable x)

token will always be expired, 
when debugging you can see that payload.iat and payload.exp are always the same.

**Comment by syberkitten** [comment]
all the issues lead to timespan.js:
I've commented below the problem.

```
var ms = require('ms');

module.exports = function (time, iat) {

   // Is mili seconds or seconds?
  var timestamp = iat || Math.floor(Date.now() / 1000);

  if (typeof time === 'string') {
    var milliseconds = ms(time);
    if (typeof milliseconds === 'undefined') {
      return;
    }

   // Why convert to seconds, timestamp could be mili ?? - this is the problem.

    return Math.floor(timestamp + milliseconds / 1000);
  } else if (typeof time === 'number') {
    return timestamp + time;
  } else {
    return;
  }

};

```

**Comment by syberkitten** [comment]
To wrap it up after few hours around it.

expiresIn has to be provided as integer and multiplied by 1000
for the library to work as expected.

I guess you guys never tested seconds as in bigger values
such as hours  / min / day, this would probably not happen.

**Comment by mvilrokx** [comment]
I've just discovered this exact same issue.  As per @syberkitten's comments, iat is in ms so it should be converted to seconds as well, just like Date.now().

**Comment by MitMaro** [comment]
> iat is in ms so it should be converted to seconds as well

Assuming I'm understanding the issue correctly, `iat` should never be provided in milliseconds, but should be provided in seconds. The docs state:

> Remember that exp, nbf and iat are NumericDate

NumericDate as per [RFC 7519](https://tools.ietf.org/html/rfc7519) is defined as:

> NumericDate
>     A JSON numeric value representing the **number of seconds** from
>     1970-01-01T00:00:00Z UTC until the specified UTC date/time,
>     ignoring leap seconds.  This is equivalent to the IEEE Std 1003.1,
>     2013 Edition [POSIX.1] definition "Seconds Since the Epoch", in
>     which each day is accounted for by exactly 86400 seconds, other
>     than that non-integer values can be represented.  See RFC 3339
>     [RFC3339] for details regarding date/times in general and UTC in
>     particular.

In this case, I think this library is working correctly.

**Comment by mvilrokx** [comment]
Yeah, that is what I ended up doing.  I'm happy for this issue to be closed.

**Comment by ziluvatar** [comment]
Closing, @syberkitten re-open it if you still have doubts.

**Comment by mvilrokx** [comment]
Is there any way this can be documented somewhere?

**Comment by ziluvatar** [comment]
It is in the README. Could we modified it anyhow to make it clearer?
