### ISSUE TITLE
Signing returns another JWT inside header with a key named token

### ISSUE THREAD

**Issue by aa3993** [auth0/node-jsonwebtoken#439]
Which ends with two equality signs

JWT below

`eyJ0b2tlbiI6ImV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUpwWkhCaGMzTWlPaUl6WkRFME1ERmlNQzFtTkdWakxURXhaVGN0WVdReE15MHpaRGRsTUdZME9EUmlaR0k2TVRsaU4yTmpNREUyWVRVeU1ERTRNemt3TmpsbU56aGxNV0pqTXpBMk4yUTBZalJqTVRrNE1HTTBPV05tWkRsak9XWTRNV1F4Tm1VMllUbGhaR1JrTVNJc0ltbGhkQ0k2TVRVeE5UY3lNalF6TkgwLlg0dGUxRmhzbGJlcW5Id3RCQ2NOMHF5Zk9vb2tvdVN2TXRlLVBUTUtrMHcifQ==`

**Comment by aa3993** [comment]
I can't even decode that second JWT using this library but I can decode that second JWT using https://jwt.io/

**Comment by MitMaro** [comment]
That's a Base64 encoded JSON string that contains a JWT, which looks very similar to a JWT, but is not a JWT. A JWT has the format `<header>.<payload>.<signature>`.

`jwt.io` isn't really decoding the value as a JWT but is instead confusing the string as the header part of a JWT and displaying that.

**Comment by aa3993** [comment]
@MitMaro Thanks man you're a life saver
