### ISSUE TITLE
Error: Cannot find module 'jsonwebtoken'

### ISSUE THREAD

**Issue by armankarimi** [auth0/node-jsonwebtoken#445]
Hello all.
I'm facing this very weird problem.
When I install `jsonwebtoken` on windows, I can easily require() and use it. 
But when I install it on ubuntu (using --save, not globally), I always face this error:

**Error: Cannot find module 'jsonwebtoken'**

On Ubuntu, size of jsonwebtoken folder in node_modules is 90KB and 120KB on windows.
All I need to do is to copy this folder from windows to linux and it works.

Can any1 help?
Thanks.

**Comment by armankarimi** [comment]
More details:

package.json files are different on Ubuntu and Windows.

Please have a look:

[package-ubuntu.json.txt](https://github.com/auth0/node-jsonwebtoken/files/1720963/package-ubuntu.json.txt)
[package-windows.json.txt](https://github.com/auth0/node-jsonwebtoken/files/1720964/package-windows.json.txt)

**Comment by MitMaro** [comment]
Can you provide the output of `npm --version` and `node --version` on Linux. It seems you may be using an old version of npm, and perhaps node.

**Comment by armankarimi** [comment]
Thanks for responding so quickly. Here goes:

Linux:
node v0.10.25
npm 1.3.10

Windows:
node v6.11.5
npm 3.10.10

**Comment by MitMaro** [comment]
Node version 0.10.25 and npm version 1.3.10 are very old and aren't supported anymore. This project requires at least Node 4. Take a look at [nvm](https://github.com/creationix/nvm) as a way to install a newer version of Node/npm on your Linux system.

**Comment by armankarimi** [comment]
Ouch sorry. 
Thanks for your help.

**Comment by MitMaro** [comment]
No problem! Good luck. :)
