### ISSUE TITLE
Having problem setting expiration to tokens.

### ISSUE THREAD

**Issue by abhilashabhatia** [auth0/node-jsonwebtoken#449]
Using below:
`jwt.sign(data, secret, {
      audience: email,
      expiresIn: Math.floor(dateObj.getTime() / 1000),
      algorithm: 'HS256'
    });`

Expected expiration value to be set is : 1640172897 but expiration value that is set is: 3160179537

**Comment by MitMaro** [comment]
`expiresIn` isn't used to set the expired NumericDate but is used to provide a time span from the current time (or the `iat` if provided) to set `exp`. 

    Math.floor(dateObj.getTime() / 1000) + (Date.now() / 1000) ~= 3160179537

What you probably want to used is `exp` directly:

    jwt.sign(Object.assign({exp: Math.floor(dateObj.getTime() / 1000)}, data), secret, { audience: email, algorithm: 'HS256' });

Or pass an `expiredTime` that is the number of seconds from the current time to expire:

    jwt.sign(data, secret, { audience: email, expiresIn: '5 m', algorithm: 'HS256' });
    // or
    jwt.sign(data, secret, { audience: email, expiresIn: 300, algorithm: 'HS256' });

**Comment by abhilashabhatia** [comment]
Thank you! That worked.
