### ISSUE TITLE
jwtToken working, however Unauthorized message never change on the backend server

### ISSUE THREAD

**Issue by LukasZvikas** [auth0/node-jsonwebtoken#450]
Hello, for some reason I am always getting Unauthorized on the backend server, but still can access the data. I'm using passport-jwt, passport-local strategies. Also, as soon as I log in, it always says unauthorized firstly in the network log, however after I refresh the page, the information appears, so there is clearly a delay in accessing the data. I'm not sure how this can happen with the backend server always showing unauthorized.

//passport.js
<img width="550" alt="screen shot 2018-03-03 at 12 33 44 am" src="https://user-images.githubusercontent.com/31712161/36930971-b5879834-1e7a-11e8-97cc-ff5ed1081db3.png">

//Auth reducer
<img width="514" alt="screen shot 2018-03-03 at 12 34 00 am" src="https://user-images.githubusercontent.com/31712161/36930981-cfe80fc4-1e7a-11e8-830f-39ee2a10f4b0.png">

//Auth actions
<img width="596" alt="screen shot 2018-03-03 at 12 34 14 am" src="https://user-images.githubusercontent.com/31712161/36930988-e3609efe-1e7a-11e8-9b5c-f463c1e8091e.png">

//Auth controller 
<img width="540" alt="screen shot 2018-03-03 at 12 36 53 am" src="https://user-images.githubusercontent.com/31712161/36930995-0a2f3928-1e7b-11e8-9c0d-6744de05607c.png">

<img width="340" alt="screen shot 2018-03-03 at 12 40 15 am" src="https://user-images.githubusercontent.com/31712161/36931018-7b5c5cb6-1e7b-11e8-8bf3-1435ff4f8996.png">

Would really appreciate any help. Thank you.

**Comment by ziluvatar** [comment]
@LukasZvikas not sure if you already found the problem. I can't see this library used anywhere there.

Better to ask in the repos for those libraries. I'll close the issue, if you have any doubt about this library be free to re-open it.
