### ISSUE TITLE
Failed to authenticate token/Token disappearing.

### ISSUE THREAD

**Issue by OGNova** [auth0/node-jsonwebtoken#451]
I'm using jwt along with a few other packages, including mongo for user data storage, to create an API, and have encountered what I believe is a bug, although I'm not sure if it's an error on my part. I've created a token for myself about half an hour ago, with this code. https://hastebin.com/umujaterox.js

A few minutes ago when I went to test an endpoint of the API that I'd like to restrict to certain tokens, it fails to authenticate my token, which is what I find weird. Code is https://hastebin.com/ewovodukuw.js.

My endpoint to create a token works just fine, and generates what I assume is a completely valid token, until it doesn't work. If y'all could let me know if this is an issue with my code or an issue with the package, that'd be great.

**Comment by OGNova** [comment]
Apologies for the delayed response.  I was unable to find the issue that's causing this. As for isolating the calls to the library, what do you mean by that? And as for printing the error, there's no real error, just a JSON response telling me that my token isn't valid.

**Comment by addons-expert** [comment]
I ran into the same problem and found the reason.
When you use the numeric value in "expiresIn", it is considered as milliseconds, rather than seconds.
So in your case:
```
     const token = jwt.sign ({id: user._id}, config.secret, {
       expiresIn: 86400
     });
```
"expiresIn" is not 1d, but 86400ms / 1000 = 86.4s

**Comment by OGNova** [comment]
Oh, well that stinks. Thanks for letting me know though!

**Comment by OGNova** [comment]
@ziluvatar It does happen when it's a number, as can be seen with my original code, and the snippet that they provided.

**Comment by ziluvatar** [comment]
When I use a number, it adds 1000 seconds as expected.
```
> jwt.decode(jwt.sign ({id: 1}, 'aa', { expiresIn: 1000 }));
{ id: 1, iat: 1527011540, exp: 1527012540 }
```

When I use a string it adds 1 second (1000 milliseconds) which is the confusing part.
```
> jwt.decode(jwt.sign ({id: 1}, 'aa', { expiresIn: '1000' }));
{ id: 1, iat: 1527011549, exp: 1527011550 }
```

Is it different for you? (I can not see your original code anymore :( )

**Comment by OGNova** [comment]
It was different for me, instead of it being measured in seconds, it was being measured in milliseconds. I don't have the original code myself anymore, as I've since pushed a couple commits to the repo.

**Comment by ziluvatar** [comment]
I see, ok, well, let's clarify the one about string usage in the readme for now, if we found out the other scenario we can tackle it at that moment.

Thanks @OGNova 👍
