### ISSUE TITLE
Unusable with TypeScript due to base64url typings conflict

### ISSUE THREAD

**Issue by kevmo314** [auth0/node-jsonwebtoken#453]
`jsonwebtoken` depends on `jws`, which depends on `base64url`. Unfortunately, `base64url` is essentially unusable in TypeScript due to [this issue](https://github.com/brianloveswords/base64url/issues/20) for which there are numerous pull requests to fix, but it seems that the package is effectively abandoned.

```
| +-- jsonwebtoken@8.1.0
| | +-- jws@3.1.4
| | | +-- base64url@2.0.0
| | | +-- jwa@1.1.5
| | | | +-- base64url@2.0.0 deduped
| | | | +-- buffer-equal-constant-time@1.0.1
| | | | +-- ecdsa-sig-formatter@1.0.9
| | | | | +-- base64url@2.0.0 deduped
| | | | | `-- safe-buffer@5.1.1 deduped
| | | | `-- safe-buffer@5.1.1 deduped
| | | `-- safe-buffer@5.1.1 deduped
| | +-- lodash.includes@4.3.0
| | +-- lodash.isboolean@3.0.3
| | +-- lodash.isinteger@4.0.4
| | +-- lodash.isnumber@3.0.3
| | +-- lodash.isplainobject@4.0.6
| | +-- lodash.isstring@4.0.1
| | +-- lodash.once@4.1.1
| | +-- ms@2.0.0 deduped
| | `-- xtend@4.0.1
| `-- node-forge@0.7.1
```

Is there another JSON Web Signature package that could be used instead?

**Comment by ziluvatar** [comment]
We had to upgrade `jws` which removed that dependency. This should not be an issue anymore.
