### ISSUE TITLE
Returns Invalid Token or null

### ISSUE THREAD

**Issue by mouryaamit** [auth0/node-jsonwebtoken#455]
Hi folks, when i am trying to decode or verify, it return null or invalid token. Same encoded value with key i am able to verify using https://jwt.io/ Debugger

    var jwt= require("jsonwebtoken");

    var token = "eyJhbGciOiJIUzI1NiJ9.eyJpc0VuY3J5cHRlZCI6dHJ1ZSwicmVtZW1iZXJEZXZpY2UiOmZhbHNlLCJzZWN1cml0eVF1ZXN0aW9uIjpbeyJxdWVzdGlvbklkIjoiMjUiLCJxdWVzdGlvbiI6IldoYXQgc3RyZWV0IGRpZCB5b3VyIGJlc3QgZnJpZW5kIGluIGhpZ2ggc2Nob29sIGxpdmUgb24/IiwiYW5zd2VyIjoiMTIzIn0seyJxdWVzdGlvbklkIjoiMTkiLCJxdWVzdGlvbiI6IldoYXQgd2FzIHRoZSBuYW1lIG9mIHlvdXIgSGlnaCBTY2hvb2w/IiwiYW5zd2VyIjoiMTIzIn1dfQ.bPYko6bN-2nGCqoSP16NxTtMAFEloWZKtiYxnBLiC0I"

    var key = "tLnE7782T9HI8TxpYh-cdbsI9Ak";
    console.log(jwt.decode(token,key)); //null
    try{
        console.log(jwt.verify(token,key));
    } catch (e){
        console.error(e); // invalid token
    }

I have having node version  : 6.11.2
and tried with jsonwebtoken : 7.1.3, 7.4.3 & 8.2.0
for all its same result.

**Comment by MitMaro** [comment]
I tried the token on jwt.io and it shows an invalid signature. With jwt.io make sure you enter the `key` first then provide the `token`. jwt.io regenerates the token when you change/enter a new secret, you can see the signature section of the token changes as the key changes.

This would be the correct token for that payload/key pair:

```eyJhbGciOiJIUzI1NiJ9.eyJpc0VuY3J5cHRlZCI6dHJ1ZSwicmVtZW1iZXJEZXZpY2UiOmZhbHNlLCJzZWN1cml0eVF1ZXN0aW9uIjpbeyJxdWVzdGlvbklkIjoiMjUiLCJxdWVzdGlvbiI6IldoYXQgc3RyZWV0IGRpZCB5b3VyIGJlc3QgZnJpZW5kIGluIGhpZ2ggc2Nob29sIGxpdmUgb24_IiwiYW5zd2VyIjoiMTIzIn0seyJxdWVzdGlvbklkIjoiMTkiLCJxdWVzdGlvbiI6IldoYXQgd2FzIHRoZSBuYW1lIG9mIHlvdXIgSGlnaCBTY2hvb2w_IiwiYW5zd2VyIjoiMTIzIn1dfQ.zWvRcCt9AQfoR8nF5grnZobNGa-38qTQkNSeYSc7QCU```

**Comment by MitMaro** [comment]
Just noticed this. Besides for the invalid signature, whatever you are using to generate your tokens are doing it incorrectly. You token appears to be base64 encoded, and not base64url encoded. You can tell by the fact that your token contains `/` where they should be `_`.
