### ISSUE TITLE
Flaw in parsing expiresIn attribute value from string (?)

### ISSUE THREAD

**Issue by ottoo** [auth0/node-jsonwebtoken#456]
I am passing the `expiresIn` value from an environment variable as a string in seconds (for example 86400s = 1 day), as the documentation suggests it should work. However, the `timespan.js` implementation expects the `expiresIn` attribute to be in milliseconds and my token expiry ends up being 86400 ms = 1.44 minutes). So if I pass an expiry as a number string, it should be in milliseconds, if i pass it as a number, it should be in seconds. 

Not sure if this is a real problem though as I can just parse the environment variable as a number, but it was something that caught me off guard and took some time to debug.

Example:

```
// Will yield wrong result and expire in 1.44 minutes
const jwt = JWT.sign(jwtData, jwtSecret, {
      expiresIn: process.env.JWT_TOKEN_EXPIRY (value is '86400')
    });
```

```
// Will yield corrent result and expire in 1 day
const jwt = JWT.sign(jwtData, jwtSecret, {
      expiresIn: 86400
    });
```

```
// timespan.js
var ms = require('ms');

module.exports = function (time, iat) {
  var timestamp = iat || Math.floor(Date.now() / 1000);

  if (typeof time === 'string') {
    var milliseconds = ms(time);
    if (typeof milliseconds === 'undefined') {
      return;
    }
    return Math.floor(timestamp + milliseconds / 1000);
  } else if (typeof time === 'number') {
    return timestamp + time;
  } else {
    return;
  }

};
```

**Comment by ziluvatar** [comment]
True, I guess we should include a warning in README for this, we currently mention:
> expiresIn: expressed in seconds or a string describing a time span zeit/ms. Eg: 60, "2 days", "10h", "7d"
