### ISSUE TITLE
endless waiting for jwt.sign({..})

### ISSUE THREAD

**Issue by moda20** [auth0/node-jsonwebtoken#460]
Hey i am using jwt in nodeJS in my user creation logic and was stuck with `jwt.sign()` method never finishing or displaying any error .
This is the function i am using  ( note the comments )
```
creatingTokens(UID,password){
    console.log("RRRRRRRRRRRRRR") //Does get logged
    var key
    try{
      key =fs.readFileSync(process.env.KEYS_DIR+"/private.pem")
    }catch (e){
      console.error(e) // no errors detected
    }
    console.log(key);// Does log the key as buffer

    return new Promise((res,rej)=>{
      console.log("Inpromise") // Does get logged
      jwt.sign({
        data: UID+password
      }, key, { expiresIn: '1h' },{ algorithm: 'RS256'},function (err,data) {
        if(err){
            rej(err);
        }else{
          console.log("Finished creating token") // Doesn't get logged
          res(data);
        }

      })
    })
  }
```
The `creatingTokens` function promise never resolves. 
help !

**Comment by MitMaro** [comment]
Before responding to your problem directly, I want to point out that the payload of a JWT isn't secure. Any data stored in the JWT can be trivially read, so I would strongly recommend against storing a password in the JWT.

As per your problem, you are passing two options to `sign` function. I think you mean to combine the `expiresIn` and `algorithm` options, like so:

```
jwt.sign(
    {data: UID+password},
    key,
    {expiresIn: '1h', algorithm: 'RS256'},
    function (err,data) {
        //...
    }
);
```

**Comment by moda20** [comment]
@MitMaro Thanks for the advice.
I'll see that i use an other payload. 
I will try the combination, i think it is my problem.
but why didn't `jwt` create any error when calling it with 2 options.

**Comment by MitMaro** [comment]
If the provided callback isn't a function it defaults to using the synchronous version of sign. There's an argument to be made that there could be stronger validation on the sign arguments, but that would be a decision for the package author.

Glad to hear that fixed your problem. :)
