### ISSUE TITLE
How to specify e.g. audience, expiresIn in options

### ISSUE THREAD

**Issue by DazWilkin** [auth0/node-jsonwebtoken#463]
If I'm reading the README correctly, I should be able to:

```
jwt.sign("", key, {
    algorithm: "RS256",
    audience: c.projectID,
    expiresIn: "24h"
});
```
But this generates errors.
```
Error: invalid expiresIn,audience option for string payload
```

Instead I must:
```
jwt.sign({
    aud: c.projectID,
    exp: Math.floor(Date.now()/1000 + 24*3600),
}, key, {
    algorithm: "RS256"
});
```

And I don't know why... I think the code support this

**Comment by MitMaro** [comment]
When you pass a string of buffer to `sign` it does not set items like `audience` and `expiresIn`, since the payload is already considered a JSON string.

The following will work:
```
jwt.sign({}, key, {
    algorithm: "RS256",
    audience: c.projectID,
    expiresIn: "24h"
});
```
The documentation in this regard could be greatly improved, as it only mentions that `exp` will not be set:

> `payload` could be an object literal, buffer or string representing valid JSON. Please note that `exp` is only set if the payload is an object literal. Buffer or string payloads are not checked for JSON validity.
