### ISSUE TITLE
 Error: Failed to match tag: "0" at: ["tbsCertificate"]["version"]

### ISSUE THREAD

**Issue by martinhbramwell** [auth0/node-jsonwebtoken#464]
I have two identical copies of code to first sign and then immediately verify a jwt.

The routine run in NodeJs 8 works **without error**.

The routine run in the browser in a VueJs app **fails** to verify, emitting:

``` Error: Failed to match tag: "0" at: ["tbsCertificate"]["version"]```

I created the key pair using : 

```
openssl req -newkey rsa:2048 -new -nodes -keyout key.pem -out csr.pem
openssl x509 -req -days 365 -in csr.pem -signkey key.pem -out server.crt
```

Is there an obvious explanation for this or do I need to dig deeper?

**Comment by ziluvatar** [comment]
I don't have any clue about it. Maybe you can provide the code.

Was the library correctly loaded in VueJS? I'm aware other people have had some issues when using the library outside NodeJS.

What if you use HS256 just to see if the signing/verification works fine in that case? So we can start reducing the possible scope.

**Comment by martinhbramwell** [comment]
I'm sorry I no longer have the code, and don't remember enough about what I was trying to do.

**Comment by ziluvatar** [comment]
I'll close the issue then
