### ISSUE TITLE
TypeError: crypto.createVerify is not a function

### ISSUE THREAD

**Issue by DamsBr** [auth0/node-jsonwebtoken#474]

**Comment by MitMaro** [comment]
Could you provide more details on the error? Perhaps a stack trace, and some environment information.

**Comment by DamsBr** [comment]
I used jwt.verify(token, 'secret')
![image](https://user-images.githubusercontent.com/10253176/40489046-7ee9de48-5f68-11e8-88f3-b3543fe775d9.png)
