### ISSUE TITLE
Adding Private Claims

### ISSUE THREAD

**Issue by StriderHND** [auth0/node-jsonwebtoken#476]
I've read the readme and I can't find where is described how to add private claims in the jwt.sign() method.

I need to add like 3 Private Claims to the signing of my Token

Any help will appreciated

Thanks

**Comment by MitMaro** [comment]
You can just add additional claims to the payload:

```
const jwt = require('jsonwebtoken');
const token = jwt.sign({ myclaim: 'myvalue' }, 'secret');
```

**Comment by StriderHND** [comment]
Thanks worked great, we should add this in the docs
