### ISSUE TITLE
Timestamps should allow fractional values

### ISSUE THREAD

**Issue by ThomasR** [auth0/node-jsonwebtoken#478]
Acoording to [RFC 7519](https://tools.ietf.org/html/rfc7519), all timestamps should take the `NumericDate` format, which represents

> the number of seconds from  1970-01-01T00:00:00Z UTC

that is `Date.now() / 1000`, but it explicilty states that

> non-integer values can be represented

Currently, `jsonwebtoken` uses `Math.floor` on all timestamps, which means that rounding errors of up to 1 second may occur.

It would be nice to have fractional values available.

---

<sub>Motivation: My application's unit tests take unnecessarily long because the token refresh testing is slowing them down.</sub>

**Comment by MitMaro** [comment]
Some context on that addition to the specification. It was added in [Draft 26](https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-26), and that particular section was discussed here: https://mailarchive.ietf.org/arch/msg/oauth/q3cIjOx2jLFxA3g93NpyHYAePH8

**Comment by ziluvatar** [comment]
> Motivation: My application's unit tests take unnecessarily long because the token refresh testing is slowing them down.

In case it helps we use [`sinon.useFakeTimers`](https://github.com/auth0/node-jsonwebtoken/blob/969813f1df3aa597545dca45af03c29a956fd1e5/test/verify.tests.js#L167) so you can control the time 😎
