### ISSUE TITLE
Error on insufficient key length

### ISSUE THREAD

**Issue by MichielDeMey** [auth0/node-jsonwebtoken#48]
Might I suggest we throw an error when the user tries to sign a token with a key of a length with an insufficient length?

I believe a length > 8 should be sufficient against brute-force attacks.

Let me know what you guys think.

**Comment by jfromaniello** [comment]
Maybe `console.warn` instead? I'm not sure

**Comment by MichielDeMey** [comment]
That definitely sounds more reasonable, throwing an error would be too aggressive.

**Comment by panva** [comment]
Closing this as stale. Using sufficient entropy secrets and higher bitsized RSA keys remains the responsibility of the user, not of the library to enforce or log about. We could make a recommendation in the README though, possibly with a link to the [JWT BCP](https://tools.ietf.org/html/draft-ietf-oauth-jwt-bcp-06#section-3.5)
