### ISSUE TITLE
Facebook Login via JWT

### ISSUE THREAD

**Issue by pranjalkumar** [auth0/node-jsonwebtoken#482]
I have been trying to implement social logins like Facebook, Google, Linkedin via JSON web token but am unable to do so. In most of the example on the web, people use the passport library for social logins but that require session storage (which I want to avoid). So, is there an inbuilt functionality for social logins in JWT.

**Comment by ziluvatar** [comment]
I'm not quite follow where JWT plays in that scenario. The session storage is needed basically to match the state you send and receive to/from the social provider to prevent CSRF attacks ([Oauth2 spec](https://tools.ietf.org/html/rfc6749#section-10.12))

If what you want is to avoid to store the session in db you can take a look to: https://www.npmjs.com/package/client-sessions (store session information in an encrypted cookie)

If you still feel JWT is good for your use case, can you elaborate the interactions between your system, the social providers, the user and the JWT?

**Comment by ziluvatar** [comment]
Closing, be free to open it if needed.
