### ISSUE TITLE
Invalidate the token before expiry

### ISSUE THREAD

**Issue by rajavijayavendan** [auth0/node-jsonwebtoken#485]
Hi,
My application has two panels(admin and client). In Client panel, after every user login I am issuing a fresh token to the user from the server.
In admin panel, I have the provision to deactivate any client user.
If I am deactivating any client user, and if that client user has any active sessions, all the sessions should be terminated at their subsequent API calls to server.
This requires revoking all the tokens issued to that client user(My jwt is used as session token)
How can I achieve?
Please help.

**Comment by mfaheemakhtar** [comment]
It is not possible to invalidate the JWT token before expiry.

One option is to create a blacklist of the JWT tokens until they expire, but you will have to check for blacklisted token every time you validate the user.

You can use a memory store to save DB calls.

Hope this help. 
If not, go to Stackoverflow.

**Comment by rajavijayavendan** [comment]
Thanks @mfaheemakhtar
