### ISSUE TITLE
JWT check if cookies was set

### ISSUE THREAD

**Issue by arnasledev** [auth0/node-jsonwebtoken#487]
Is it even possible to check if JWT cookie was set after signing? 

`const token = jwt.sign(user, '4waNdqInzkWHwTs4BXXp9ZAsolK0EV75', {expiresIn: 86400 * 30});`

and after this I can use token and see its value, I can even decode it. But I can't see any new cookie that would be created on my browser. So on I can't use `JWTStrategy` to check if user is authorized or not. So if the cookie was not set, how can I know why? 

The problem described before is [here](https://stackoverflow.com/questions/50795079/passport-jwt-unauthorized-after-logging-in)

**Comment by JacoKoster** [comment]
Hello @arnasledev, i have replied to your StackOverflow question. This library only creates / verifies or decodes the JWT and it is up to your application to do something with it. Your application should be creating the cookie or supplying the token as a header, this is not something this library helps with.
