### ISSUE TITLE
Signing, object vs string

### ISSUE THREAD

**Issue by mhingston** [auth0/node-jsonwebtoken#49]
> If `payload` is not a buffer or a string, it will be coerced into a string using `JSON.stringify`.

Shouldn't these result in the same output or am I missing something?

```js
jwt.sign({x: 1}, "secret")
// 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ4IjoxLCJpYXQiOjE0MjE4NjE1ODB9.YBvFd7_yRFKGRs09T1I6ChZze-6OmY7SpiCXxVzknVc'

jwt.sign(JSON.stringify({x: 1}), "secret")
// 'eyJhbGciOiJIUzI1NiJ9.eyJ4IjoxfQ.XOAA7XIKOu4yBszS83Yc_js4QvGVrdubYLQdNnpQ8J4'
```

**Comment by MichielDeMey** [comment]
If it's an object, the library will add the "typ" header as well.
https://github.com/auth0/node-jsonwebtoken/blob/master/index.js#L16

In addition it'll generate and add an iat to the token's payload in case of an object.

This doesn't happen in case of a string.
