### ISSUE TITLE
Compatibility with Angular6

### ISSUE THREAD

**Issue by eyesmunt** [auth0/node-jsonwebtoken#498]
Currently the crypto library is not included in the webpack.config file of Angular 6, and the webpack.config file it's not exposed to end-users of Angular 6. This prevents me from being able to use the jsonwebtoken package in an Angular 6 application.

**Comment by ziluvatar** [comment]
Can you check if this helps you? https://github.com/auth0/node-jsonwebtoken/issues/471

**Comment by eyesmunt** [comment]
I did read that but that's not really an option for the project I'm working on. Everything needs to be pretty legit in this application.

**Comment by mp3killa** [comment]
This module does appear to require an update to be compatible with Angular 6. I've had to rollback to Angular 5 for this to still work. Please won't you look into it and resolve?

**Comment by MitMaro** [comment]
In the past providing compatibility with angular has been outside the scope of this project.

The issue with the usage of the `crypto` module not being provided is an issue with Angular 6 not providing a mechanism to enable the [node crypto polyfill](https://webpack.js.org/configuration/node/) in their webpack configuration. See https://github.com/angular/angular-cli/issues/1548 for more details and a few workarounds for Angular.

The [angular2-jwt](https://github.com/auth0/angular2-jwt) project that adds some support for JSON Web Tokens to Angular projects and reports to work with Angular 6.

**Comment by JacoKoster** [comment]
I still maintain that this is the `node`-jsonwebtoken project, including the work for frontend would introduce too much complexity in this package.

**Comment by mp3killa** [comment]
Thanks for the responses, it is appreciated. Also the link to the 1548 issue is helpful.  I know it's "in the name" node-jwt... however your fantastic module is the only useful option for signing & generating a usable JWT and not just to decode & verify. I'd be super grateful if you were able to somehow get it to work in the future :)
