### ISSUE TITLE
Auth token should get invalidated if the node server is restarted.

### ISSUE THREAD

**Issue by alnvny** [auth0/node-jsonwebtoken#508]

**Comment by MitMaro** [comment]
Generally, it's not possible with JWTs directly as once they are issued they cannot be revoked or invalidated.

In your particular case, you could securely generate a signing secret on server start. That way any tokens signed with the old secret would then invalid.

Another option would be to use the `issuer` claim with a value generated at the server start, and when you verify use the `issuer` option to ensure they match. Old tokens will be considered invalid.
