### ISSUE TITLE
Improve expirationInMinutes precision

### ISSUE THREAD

**Issue by dan-silva** [auth0/node-jsonwebtoken#51]
Currently this library only allows the token to be signed with a expiration in minutes. Shoudn't it be able to handle in a more granular way — maybe using a Date object?

At this moment, it's possible to use float values (e.g. 1.5 minutes) but I'm not sure if the current output ("exp": 1422230816.994) is valid based on JWT specs. If not, maybe a simple rounding would probably suffice too.

**Comment by demisx** [comment]
Would like to be able to set it in seconds too to be consistent with other implementations.

**Comment by jfromaniello** [comment]
Thank you guys , I added `expiresInSeconds` to sign. This will be released today as v4

**Comment by demisx** [comment]
:+1:
