### ISSUE TITLE
Invalid token error: illegal padding error 0D0E20DD

### ISSUE THREAD

**Issue by eaardal** [auth0/node-jsonwebtoken#510]
Hi

It’s been a while since I worked on this project of mine, but when I picked it back up and had updated the out-of-date npm packages, authorization no longer worked between my (React) client and (Node) api. I get this error:

```js
error: {
  "name": "UnauthorizedError",
  "message": "error:0D0E20DD:asn1 encoding routines:c2i_ibuf:illegal padding",
  "code": "invalid_token",
  "status": 401,
  "inner": {
    "opensslErrorStack": [
      "error:0906700D:PEM routines:PEM_ASN1_read_bio:ASN1 lib",
      "error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error",
      "error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error"
    ]
  }
}
```

This error is thrown [here](https://github.com/auth0/express-jwt/blob/master/lib/index.js#L102) in `express-jwt` which is a call to `verify.js` in this codebase. I still haven't found the root issue or where the `illegal padding` part occurs, it seems to be further down the dependency tree. But I'm posting this here in the hope that someone here knows this stuff better than me and can either pinpoint what I can do on my side to fix it if this is due to bad data/input, or debug this through the Auth0 stack, since all of the packages regarding this issue seems to be owned by Auth0.

I also posted this [on Auth0's forums](https://community.auth0.com/t/invalid-token-error-illegal-padding-error-0d0e20dd/13209) a few weeks ago.

**Comment by eaardal** [comment]
Thanks for the reply 🙏 
I have checked and re-checked the access_token I receive from Auth0 when logging in, and the value passed to `jwt.verify` on the server is exactly identical to the value received from Auth0. The access_token is also validated successfully on the client when the callback endpoint is invoked by Auth0 after logging in, but then fails later when validated on the api.

The other issues you referred to is discussing the `=` padding character. My token does not include `=`, `+`, or `/` or other typically problematic characters. Do you know if there are other things beside `=`/base64 issues that might cause an `illegal padding` error? Any little idea is helpful at this point 😓

**Comment by ziluvatar** [comment]
When you say "my token does not include `=`", do you mean the access token?

The error is coming from a problem with the public key, not from the access token. For verifying you do `jwt.verify(mytoken, secretOrPublicKey, options, cb)`. It seems the verification is done with asymmetric algorithm (based on the error), that `secretOrPublicKey` is the problem.

**Comment by xcv58** [comment]
Did you find a solution @eaardal ?
