### ISSUE TITLE
AWS Load Balancer Auth

### ISSUE THREAD

**Issue by delianides** [auth0/node-jsonwebtoken#514]
AWS recently added the functionality to authenticate a user on the load balancer and have a authenticated and hydrated user details in the request header.

I wasn't able to decode the object that comes from the load balancer even though it will decode on jwt.io. The example AWS give is in python but should be straight forward enough to decode the token.

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html

Has anyone attempted to decode the `x-amzn-oidc-data` header using `jwt.decode`?

**Comment by MitMaro** [comment]
Interesting!

Could you provide the code that you tried that did not work?

Off the top of my head it should be pretty easy, and would be something along the lines of:

```javascript
// this should always work
console.log(jwt.decode(token));

const pubKey = fs.readFileSync('/path/to/publickey'); // replace this line with the HTTP request to get the key

jwt.verify(token, pubKey, (err, decoded) => {
  console.log('err:', err);
  console.log(decoded);
});
```

**Comment by delianides** [comment]
@MitMaro 

This is what I was trying to do but I've even tried your example and it still didn't work. The only thing I added was the `{ algorithms: [ 'ES256' ]}`.

```js
const verifyJwt = async (token, db) => {
  const encoded_jwt_header = token.split('.')[0];
  const decoded_jwt = JSON.parse(base64.decode(encoded_jwt_header));
  const request = await fetch(
    `https://public-keys.auth.elb.us-west-2.amazonaws.com/${decoded_jwt.kid}`,
  );
  const cert = await request.text();  // -----BEGIN PUBLIC KEY----...

  return new Promise((resolve, reject) => {
    jwt.verify(
      token,
      cert,
      { algorithms: ['ES256'] }, 
      async (err, decoded) => {
        if (err) {
          reject(err);
        }

        resolve(decoded);
      },
    );
  });
};
```

**Comment by delianides** [comment]
@MitMaro 

![](https://share.ajd.fyi/3NePin9SH2/Screen-Shot-2018-09-11-11-49-02.png)

Same data added to jwt.io

![](https://share.ajd.fyi/Rfmf4KZvqs/Screen-Shot-2018-09-11-11-51-56.png)

**Comment by delianides** [comment]
@MitMaro figured it out and found this:
https://github.com/brianloveswords/node-jws/pull/84

**Comment by MitMaro** [comment]
That's a common mistake but Amazon should know better. Should be easy to do a simple string replace to work around the problem.

**Comment by MitMaro** [comment]
@jreeter ,

Amazon is using base64 to encode the tokens, which has a different character set than base64url, which is what the JWT specification requires.

Specifically, the `+` character is replaced with `-`, the `/` character is replaced with `_` and the trailing `=`s are optional. You can do a basic string replace on the invalid tokens to make them valid base64url encoded tokens.

Untested Code, but the basic idea would be:
```javascript
const correctToken = token.replace(/+/g, '-').replace(/\//g, '_');
```

**Comment by daerion** [comment]
Just wanted to add that we're having the same issue. Converting token encoding to base64url will allow the library to decode it, however, it will also cause signature verification to fail (both with the library as well as on jwt.io, while using the original token and pubkey will successfully validate on jwt.io).

**Comment by morganabel** [comment]
@daerion I found a way to make this work, but it's not pretty......

Basically, the verify method in this library won't work, but the signature can be verified using the underlying node-jwa library. Then you just have to check things like is the token still valid (I am only checking if token is not expired):


```
const base64Url = require("base64url");
const jwt = require("jsonwebtoken");
const jws = require("jws");
const fetch = require("node-fetch").default;

async function verifyToken(token) {
  var base64UrlToken = base64Url.fromBase64(token);
  const decoded = jwt.decode(base64UrlToken, { complete: true });

  const { kid, signer } = decoded.header;
  const region = signer.split(":")[3];

  const uri = `https://public-keys.auth.elb.${region}.amazonaws.com/${kid}`;

  console.log(`Fetching key at: ${uri}`);

  const response = await fetch(uri);
  const key = await response.text();

  console.log(key);

  try {
    const verify = jws.verify(token, "ES256", key);
    if (!verify) {
      return null;
    }

    var clockTimestamp = Math.floor(Date.now() / 1000);
    if (clockTimestamp >= decoded.header.exp) {
      // Token expired.
      return null;
    }
  } catch (err) {
    console.error(err);
    throw err;
  }

  return decoded.payload;
}
```

**Comment by daerion** [comment]
@morganabel Thanks for sharing your implementation :)

**Comment by trallnag** [comment]
Just ran into the same issue...
