### ISSUE TITLE
PEM_read_bio:no start line

### ISSUE THREAD

**Issue by george-norris-salesforce** [auth0/node-jsonwebtoken#517]
passing in RSA private key from env varaible to the jwt.sign. Results in PEM_read_bio:no start line

**Comment by MitMaro** [comment]
Can you verify that your private key begins with `-----BEGIN RSA PRIVATE KEY-----`?

You can also verify your private key format using:
```
openssl rsa -in path/to/rsa-private.pem -check
```

**Comment by josianni** [comment]
Hello, 

I have the same problem here.

**Comment by cjk** [comment]
@george-norris-salesforce Did you ever solve your problem and if so, how?

**Comment by george-norris-salesforce** [comment]
Had to put it all on one line, seperated by `/n` and remove all blank spaces

**Comment by yasithph** [comment]
I had the same issue and none of the answers given here or else where did not work. Finally I found out that one of the '-' in -----BEGIN RSA KEY----- was missing. There need to 5 dashes exactly.
