### ISSUE TITLE
Fail to verify a OAuth2 RS256 id_token from implicit flow: invalid algorithm

### ISSUE THREAD

**Issue by benji** [auth0/node-jsonwebtoken#519]
Hi!
I'm using jsonwebtoken to validate an id_token server side, but it fails with:

```
{ JsonWebTokenError: invalid algorithm
    at /home/.../node_modules/jsonwebtoken/verify.js:110:19
```

The IdP is Google, the algorithm is RS256.

Background:
I'm using the implicit flow to get an id_token from Google entirely in JS to avoid using server resources / to avoid having to remember a state/nonce etc.
Once I have one I send it to the server but I wish to verify it.

I must be doing something wrong but I can't seem to find what it is. Any idea?

**Comment by MitMaro** [comment]
Can you provide the code that is producing the error, and also provide the output of the following to verify the algorithm used:

```javascript
console.log('Algorithm: ', jwt.decode(token, {complete: true}).header.alg);
```

**Comment by benji** [comment]
The code that's producing the error is simply:

```
  jwt.verify(id_token, '<thesecret>', function (err, decoded) {
    if (err) {
      console.error(err);
    } else {
      console.log(decoded) 
    }
  });
```

That's the only thing I'm doing on the server side.

The Algorithm is indeed RS256 in the header.

**Comment by MitMaro** [comment]
`RS256` uses a public/private key pair, and it seems you are using a shared secret.

**Comment by benji** [comment]
OK got it, thank you.
For future reference, I did not have a certificate from Google OAuth UI configuration but it can be retrieved with an API call.
More details here: https://developers.google.com/identity/protocols/OpenIDConnect#validatinganidtoken

**Comment by MitMaro** [comment]
Great to hear you figured it out. :smiley:
