### ISSUE TITLE
UTF8 encoding problem

### ISSUE THREAD

**Issue by MilosStanic** [auth0/node-jsonwebtoken#52]
I have implemented into my project the code from your example at https://github.com/auth0/angular-token-auth/

However, if the payload contains an UTF8 character, in my case 'ć' the payload is badly encoded, and I get an error when doing a JSON.parse of the payload, like I described here https://github.com/auth0/angular-token-auth/issues/9

**Comment by brianloveswords** [comment]
This was an issue in `node-jws`, I was using `binary` as the default encoding with no option to override. I just released [v2.0.0] which changes the default to `utf8` and gives the option to override the encoding.

[v2.0.0]: https://github.com/brianloveswords/node-jws/blob/master/CHANGELOG.md#200---2015-01-30

**Comment by RoberMac** [comment]
Same problem with @MilosStanic , see below code:
```
var token = jwt.sign({
    username: '測試'
 }, key)
```
then when:
```
jwt.verify(token, key)
```
with error Unexpected token at JSON.parse.

**Comment by RoberMac** [comment]
@brianloveswords Awesome! 👍

**Comment by jfromaniello** [comment]
It will be fixed on v4. Thank you guys!
