### ISSUE TITLE
How to Expire token Immediately ?

### ISSUE THREAD

**Issue by AhmadRaza786** [auth0/node-jsonwebtoken#525]
I want to expire the generated jsonwebtoken immediately. So that it will not able to authorize any next request.

**Comment by tumulr** [comment]
You might want to look into blacklisting of JWT tokens.

[https://auth0.com/blog/blacklist-json-web-token-api-keys/](url)

**Comment by AhmadRaza786** [comment]
@tumulr cant find anything on your provided link.

**Comment by MitMaro** [comment]
Copy and paste the link into your address bar, as @tumulr 's link text and href do not match.

It's not possible to directly expire a JWT, and instead you will need to create a blacklist of tokens. The link provided by @tumulr described one way to create this blacklist.

**Comment by ziluvatar** [comment]
> I want to expire the generated jsonwebtoken immediately. So that it will not able to authorize any next request.

Is that for testing? I mean why would you generate a JWT that is invalid right after the creation?
In the case you want to simulate an expired token you can pass negative expiration `.sign(payload, secret, { expiresIn: '-10s' }`

**Comment by alex-morales-web1on1-chat** [comment]
>I mean why would you generate a JWT that is invalid right after the creation?

Dude, come on, great answer but stop w/ the policing.
