### ISSUE TITLE
Using node-jsonwebtoken on React Native

### ISSUE THREAD

**Issue by johanjmoncada** [auth0/node-jsonwebtoken#530]
Hi there,

Does anyone know how I could use this module with react native?

I tried installing the module and importing it in my react solution but I got the following issue: 

`error: bundling failed: Error: Unable to resolve module "stream" from "/project_folder/node_modules/jws/lib/sign-stream.js": Module "stream" does not exist in the Haste module map`

I did a lot of researching but unfortunately, I couldn't find a solution with allow me run the application with this module.

Many thanks in advance whoever could help me with a solution.

**Comment by ziluvatar** [comment]
Check this past issue to see if it helps: https://github.com/auth0/node-jsonwebtoken/issues/221
