### ISSUE TITLE
Text input does not work in iOS

### ISSUE THREAD

**Issue by ntotten** [auth0/node-jsonwebtoken#54]
There are a few issues I found:

1. When clicking on the textbox and holding the delete key only one character is deleted and the delete key is released. The expected iOS behavior is that you can click and hold to continually delete.
2. You cannot click and hold to select the text thus making it difficult to clear the textbook. 
3. You cannot click and hold to copy or paste. Paste is most problematic because it makes the site impossible to use on iOS unless you memorize and type the key manually.

Here is a video of the interactions. At then end you will see me trying to click, click and hold, etc. 

https://www.dropbox.com/s/26bw8lkp380k8lv/2015-02-06_12-24-24.mp4?dl=0

My guess is we are just intercepting too many events incorrectly. One nice thing would be on mobile browsers that once you click on the text box it automatically clears then the user can easily paste in the box.

**Comment by jfromaniello** [comment]
@ntotten this is the repository for the jwt library for node.js, I think you meant to create the issue in 

https://github.com/jsonwebtoken/jsonwebtoken.github.io

BTW I've the same problem on Android, the editor is a crap on mobile, it will be nice to use a normal textarea on mobile.

**Comment by ntotten** [comment]
Ah, yeah. wrong repo. thanks!
