### ISSUE TITLE
my data in web site jwt.io is very  clear 

### ISSUE THREAD

**Issue by riadhriadh** [auth0/node-jsonwebtoken#542]
this is my code . 

  const expiresIn = 6000 * 60;
    const secretOrKey = fs.readFileSync("./key.pem");;
    const user = { email };
    
     const token = jwt.sign(user, secretOrKey,   { audience: 'urn:foo' });
   
  
    return { expires_in: expiresIn, token };

========================
this is my result

{
"expires_in": 360000,
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZhcmhhdGlyZWRAZ21haWwuY29tIiwiaWF0IjoxNTQwMzcwMDI2LCJhdWQiOiJ1cm46Zm9vIn0.wg1vAo0AruBgK6DB2XtyzXNo-5V0b12l1La6bBtiYQU"
}
======================================
wen to go  in site jwt.io and click 
this is my result 

HEADER:ALGORITHM & TOKEN TYPE

{
  "alg": "HS256",
  "typ": "JWT"
}
PAYLOAD:DATA

{
  "email": "farhatired@gmail.com",
  "iat": 1540370026,
  "aud": "urn:foo"
}
VERIFY SIGNATURE

HMACSHA256(
  base64UrlEncode(header) + "." +
  base64UrlEncode(payload),
  

) secret base64 encoded
=====================================================================

**Comment by MitMaro** [comment]
I'm not exactly sure what you are asking.

If you are asking why an email address and other payload data is viewable on jwt.io, then this is expected. JWTs only encode information and it is fairly trivial for anyone to decode and view the encoded information. There's [information from Auth0](https://auth0.com/blog/ten-things-you-should-know-about-tokens-and-cookies/#confidential-info) on how to handle sensitive information in tokens.
