### ISSUE TITLE
Why getKey doesn't get called?

### ISSUE THREAD

**Issue by SirwanAfifi** [auth0/node-jsonwebtoken#546]
> If jwt.verify is called asynchronous, secretOrPublicKey can be a function that should fetch the secret or public key

I have following function:

```
const client = jwksClient({
  jwksUri: `${process.env.AUTH0_DOMAIN}/.well-known/jwks.json`
});
const getKey = (header, cb) => {
  client.getSigningKey(header.kid, (err, key) => {
    var signingKey = key.publicKey || key.rsaPublicKey;
    cb(null, signingKey);
  });
};

const result = new Promise((resolve, reject) => {
      jwt.verify(token, getKey, options, (err, decoded) => {
        if (err) {
          console.log("token verification failed:", err.message);
          reject(err);
        } else {
          resolve(decoded);
        }
      });
    });
```

Any idea why `getKey` doesn't get called?

**Comment by SirwanAfifi** [comment]
Here's the option:
```js
const options = {
  audience: process.env.AUTH0_CLIENTID,
  issuer: process.env.AUTH0_DOMAIN,
  algorithms: ["RS256"]
};
```

**Comment by MitMaro** [comment]
That looks alright. Can you verify that `getKey` isn't being called with a `console.log` or with a break point?

My other guess would be that `client.getSigningKey` is getting called but returning an error, which is unhandled.

**Comment by sebk** [comment]
I have the same problem, that `getKey` isn't called.
I tried adding various `console.log` statements, but the implementation for `getKey` is not executed.
I also tried version 8.3.0 and 8.4.0.

**Comment by ziluvatar** [comment]
@sebk can you provide some simple code to review it?

**Comment by ziluvatar** [comment]
I downloaded your project and used one jwks url and it worked fine 🤔
If you don't have a jwks uri you can easily remove the code calling `client.getSigningKey` and return a hardcoded secret, you will see it is called.
