### ISSUE TITLE
in Java how to do ?

### ISSUE THREAD

**Issue by mylovetop** [auth0/node-jsonwebtoken#557]
the jsonwebtoken token
How do you decode the same token in Java?
in java use keystore.jceks decode the token, The following How do I write commands like this

keytool -genseckey -keystore keystore.jceks -storetype jceks -storepass [secret_key] -keyalg HMacSHA256 -keysize 2048 -alias HS256 -keypass [ secret_key]

thank you!

**Comment by MitMaro** [comment]
You may have more luck with https://github.com/auth0/java-jwt as this library is specific to Node.js.

**Comment by mylovetop** [comment]
thank you! 
but i use vert.x jwt  
eg.
JWTAuth jwtAuth = JWTAuth.create(vertx,
                new JWTAuthOptions()
                        .setKeyStore(
                                new KeyStoreOptions()
                                        .setPath("config/jwt.jceks")
                                        .setType("jceks")
                                        .setPassword(token)));

the token is the same,  but the token  Not certified.

i use vert.x-jwt create token and decode the token  no problem,  but  use nodejs`s token  not decode, The default HS256  algorithm in nodejs

Thank you again for!
