### ISSUE TITLE
Allow iss, sub, and aud in the header

### ISSUE THREAD

**Issue by KevinAllenWiegand** [auth0/node-jsonwebtoken#575]
According to RFC 7519, the iss, sub, and aud keys should be allowed in the header, but there are no options in the code to do that.

5.3.  Replicating Claims as Header Parameters

   In some applications using encrypted JWTs, it is useful to have an
   unencrypted representation of some claims.  This might be used, for
   instance, in application processing rules to determine whether and
   how to process the JWT before it is decrypted.

   This specification allows claims present in the JWT Claims Set to be
   replicated as Header Parameters in a JWT that is a JWE, as needed by
   the application.  If such replicated claims are present, the
   application receiving them SHOULD verify that their values are
   identical, unless the application defines other specific processing
   rules for these claims.  It is the responsibility of the application
   to ensure that only claims that are safe to be transmitted in an
   unencrypted manner are replicated as Header Parameter values in the
   JWT.

   Section 10.4.1 of this specification registers the "iss" (issuer),
   "sub" (subject), and "aud" (audience) Header Parameter names for the
   purpose of providing unencrypted replicas of these claims in
   encrypted JWTs for applications that need them.  Other specifications
   MAY similarly register other names that are registered Claim Names as
   Header Parameter names, as needed.

**Comment by ziluvatar** [comment]
Currently the library does not support JWE either, only JWS. Do you have a different use case where you need to have them in the header?

**Comment by KevinAllenWiegand** [comment]
My current requirement is to allow issuer in the header.

**Comment by panva** [comment]
@KevinAllenWiegand that section is specifically intended for JWE where the claims like iss or aud are required to be "peekable" in order to avoid having to cycle through all key material to get a hit but rather nail down the CEK unwrap or direct oct decryption key upfront. This does not apply to unencrypted JWTs.

There's no real benefit in putting stuff in the header as both header and payload are protected by the signature in JWT due to its use of compact mode.

**Comment by ziluvatar** [comment]
Out of curiosity
> My current requirement is to allow issuer in the header.

I guess that is the solution, what is the use case?

**Comment by ziluvatar** [comment]
Closing, be free to reopen if you want to continue the conversation.
