### ISSUE TITLE
Clarification on ECDSA support

### ISSUE THREAD

**Issue by mathiasconradt** [auth0/node-jsonwebtoken#579]
On https://github.com/auth0/node-jsonwebtoken#algorithms-supported, ECDSA is mentioned, while the README.md on https://github.com/auth0/node-jsonwebtoken only gives code examples for HMAC and RSA. 
Also, in the Auth0 dashboard / Application > Advanced Settings, one can only choose between RS256 and HS256, but not ECDSA for the JWT Signature algorithm. 
Why is the ECDSA not an option in the Auth0 dashboard, while it's supported in this Node.js library though?

**Comment by panva** [comment]
> Why is the ECDSA not an option in the Auth0 dashboard, while it's supported in this Node.js library though?

We do not strive for parity in available signing algorithms. This library's audience is not just Auth0 customers.

> Clarification on ECDSA support
> On [auth0/node-jsonwebtoken#algorithms-supported](https://github.com/auth0/node-jsonwebtoken#algorithms-supported), ECDSA is mentioned, while the README.md on [auth0/node-jsonwebtoken](https://github.com/auth0/node-jsonwebtoken) only gives code examples for HMAC and RSA.

Let me clarify then. ECDSA is supported by `jsonwebtoken`, it's "code example" is exactly the same as RSA - only different alg values and private/public key material representing an EC key.

**Comment by mathiasconradt** [comment]
> We do not strive for parity in available signing algorithms.

Understood, was just wondering about the reasons behind it - why ECDSA is not an option in the Auth0 dashboard but only RSA and HMAC when choosing the sign algorithm, as it's only one additional option and then we'd support all that JWT supports.

From a blog post, I learned about the differences as follows:

> "The main difference between RSA and ECDSA lies in speed and key size. ECDSA requires smaller keys to achieve the same level of security as RSA. This makes it a great choice for small JWTs. RSA, however, is usually faster than ECDSA. As usual, pick the one that best aligns with your requirements."

Trying to understand, why was RSA chosen over ECDSA as the asymmetric sign option, or why aren't simply both options offered. But maybe that's more a question towards the product team rather than this node library repo.

**Comment by ziluvatar** [comment]
> But maybe that's more a question towards the product team rather than this node library repo.

Yeah, better to ask on different channel like https://community.auth0.com/ or Auth0 Support.
