### ISSUE TITLE
verify expects a specific jwtid?

### ISSUE THREAD

**Issue by bencmbrook** [auth0/node-jsonwebtoken#581]
This module seems to expect the verifier to know what the "jti" is beforehand. I understand "jti" to be primarily used as a nonce to prevent replay attacks, or keeping a revocation list. The verify step, however, seems to just check that the provided `jwtid` [matches a specific string](https://github.com/auth0/node-jsonwebtoken/blob/eefb9d9c6eec54718fa6e41306bda84788df7bec/verify.js#L187-L191).

["jti" reference](https://tools.ietf.org/html/rfc7519#section-4.1)

**Comment by bencmbrook** [comment]
I suppose this could act as a valid use-case, and it's good that if the option isn't passed, the token isn't rejected. Maybe it should just be [documented](https://github.com/auth0/node-jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback) that passing the option is only if you expect a specific `jwtid` beforehand?

**Comment by ziluvatar** [comment]
Yeah, probably not too useful, good catch, would you like to go ahead and document it clear for others?
