### ISSUE TITLE
jwt.verify/decode working only on static strings when using websockets

### ISSUE THREAD

**Issue by FrederickEngelhardt** [auth0/node-jsonwebtoken#587]
Hi,

I'm able to generate a token and then send it to a used. The user then stores this locally. Afterwards we call a authentication script to send that token up to the server

Issue: The dynamic token sent is never valid. However, if you console.log this value and hardcode it into the verify function you are able to get a verification and result.

Using this with websockets if that matters.

```
      this.socket.on('authentication_token', (token) => {
        jwt.verify(token, process.env.JWT_KEY, { algorithm: 'HS512', maxAge: '2d'}, function(err, decode) {
          console.log(decode)
        })
      });
```

Working example with REST

```
router.post('/jwt/verify', async (req,res,next) => {
  const { token } = req.body;
  const data = jwt.verify(token, process.env.JWT_KEY, { algorithm: 'HS512', maxAge: '2d'}, function(err, decode) {
    if (err){
      console.log('ERROR', err)
    }
    console.log(decode)
  });
  res.send(true);
});
```

**Comment by rupertbg** [comment]
Are you never passing `token` in as the first parameter to jwt.verify?

**Comment by FrederickEngelhardt** [comment]
Yes sorry I've been iterating through this a bunch of times. Looks like it works with a rest endpoint without an issue. But web-sockets it fails to recognize the string.

**Comment by panva** [comment]
@FrederickEngelhardt Your report does not state what error you're getting. This is most likely not an issue with `jsonwebtoken` but rather your code.

`jsonwebtoken` only cares that the input is a string, if it wasn't you'd get `jwt must be a string` error or similar.

Not being familiar particular websocket frameworks is it possible for you to to log the jwt string in your code and provide the public key you're verifying with?

**Comment by FrederickEngelhardt** [comment]
Looks like the main issue is related to the jwt.decode which returns null when you receive an emitted token. If you hardcode that token into the jwt.decode it will pass.

**Comment by panva** [comment]
@FrederickEngelhardt Yes, decode returns `null` on invalid tokens. Please provide the details requested.

Once again

1) the error you're getting (!!!)
2) log `typeof token` from your websocket handler
3) log `token` from your websocket handler
4) the public key for verification

**Comment by FrederickEngelhardt** [comment]
@panva looks like I was missing a JSON.parse for the token inside of the websocket response. Adding that did the trick. Thank you!

See code below for reference.
```
      this.socket.on('authentication_token', (token) => {
        jwt.verify(JSON.parse(token), process.env.JWT_KEY, { algorithm: 'HS512', maxAge: '2d'}, function(err, decode) {
          console.log(decode)
        })
      });
```

**Comment by markerberg** [comment]
I was also receiving a null value when trying to use `jwt.decode(token)`. Turns out I also needed to parse it `jwt.decode(JSON.parse(token))`

**Comment by mirajehossain** [comment]
> I was also receiving a null value when trying to use `jwt.decode(token)`. Turns out I also needed to parse it `jwt.decode(JSON.parse(token))`

token already string, but when I parse it using JSON.parse() it throw parse error.
