### ISSUE TITLE
handle "TokenExpiredError: jwt expired" Error

### ISSUE THREAD

**Issue by splservices** [auth0/node-jsonwebtoken#590]
```
const checkToken = (req, res, next)=>{
    let token = req.headers['x-access-token'] || req.headers['authorization'];
    if(token && token.startsWith('Bearer ')){
        token = token.slice(7, token.length)
    }
    if(token){
        try{
            let decoded = jwt.verify(token, secret);
            req.decoded = decoded;
            User.findOne({email:decoded.email})
                .populate('following')
                .exec((err, user)=>{
                    if(err) throw err;
                    if(user){
                        req.user = user;
                        next();
                    }
                });
        }catch(err){
            res.status(403).send({
                success:false,
                message:err
            })
        }
    }else{
        return res.status(403).json({
            success:false,
            message:'Unauthorized'
        })
    }
};
```
**If Token is Expired. Getting this error:**

``{ TokenExpiredError: jwt expired
    at /Users/pradeepkumar/Desktop/bitbucket/volupn-api/node_modules/jsonwebtoken/verify.js:152:21
    at getSecret (/Users/pradeepkumar/Desktop/bitbucket/volupn-api/node_modules/jsonwebtoken/verify.js:90:14)
    at Object.module.exports [as verify] (/Users/pradeepkumar/Desktop/bitbucket/volupn-api/node_modules/jsonwebtoken/verify.js:94:10)
    at Socket.socket.on (/Users/pradeepkumar/Desktop/bitbucket/volupn-api/sockets/base.js:10:17)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at /Users/pradeepkumar/Desktop/bitbucket/volupn-api/node_modules/socket.io/lib/socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
  name: 'TokenExpiredError',
  message: 'jwt expired',
  expiredAt: 2019-04-14T13:12:19.000Z }``

**Comment by panva** [comment]
Hi @splservices is there something particularly not clear about this expected error when JWTs are past their self-contained expiration?

**Comment by splservices** [comment]
@panva This Error is clear to me but right now this error is breaking my application and I want to handle this error in right manner.

**Comment by Adityacprtm** [comment]
@splservices try to just use `err.name`, so it will return string value

**Comment by panva** [comment]
`TokenExpiredError` is also exported btw -> `instanceof`

**Comment by splservices** [comment]
thanks @Adityacprtm `err.name` is just working fine.

**Comment by TeijiW** [comment]
I'm using `err.name`, but he just returns "_Error_"

**Comment by Shhuy** [comment]
是否是到了设置的过期时间以后进行解密，就会进入异常处理，我需要再时间过期以后拿到存入的信息，但是现在进入了异常。怎么解决呢？

**Comment by webrsb** [comment]
> 是否是到了设置的过期时间以后进行解密，就会进入异常处理，我需要再时间过期以后拿到存入的信息，但是现在进入了异常。怎么解决呢？

https://github.com/auth0/node-jsonwebtoken#jwtdecodetoken--options

**Comment by mayeskhatri243** [comment]
import jwt from "jsonwebtoken";

const auth = async (req, res, next) => {
  try {
    const token = req.headers.authorization?.split(" ")[1];
    const isCustomAuth = token?.length < 500;

    if (!token) return res.status(401).json({ message: "No token provided" });

    let decodedData;
    if (token && isCustomAuth) {
      decodedData = jwt.verify(token, process.env.SECRET_KEY);

      req.userId = decodedData?.id;
    } else {
      decodedData = jwt.decode(token);

      req.userId = decodedData?.sub;
    }

    next();
  } catch (error) {
    res.status(403).json({ message: "Token is not valid" });
  }
};

export default auth;


create a middleware like this.
Hope this will work as u want
