### ISSUE TITLE
JWT Decode retuning null even when Token is not null

### ISSUE THREAD

**Issue by mathellsmelo** [auth0/node-jsonwebtoken#593]
JWT Decode is not working

I've tried everything I could

let user_id = jwt.decode(req.body.auth_token).id;

req.body.auth_token is not null, it's returning the token!

**Comment by mathellsmelo** [comment]
It's working, I was passing token between ""

**Comment by panva** [comment]
Same issue as in #587

**Comment by markerberg** [comment]
I was also receiving a null value when trying to use `jwt.decode(token)`. Turns out I also needed to parse it `jwt.decode(JSON.parse(token))`
