### ISSUE TITLE
Anatomy of a Refresh token

### ISSUE THREAD

**Issue by whimsicaldreamer** [auth0/node-jsonwebtoken#599]
Hello, I want to know if there is any definite schema for refresh tokens. From [here](https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/), I understand that  
 > Refresh tokens carry the information necessary to get a new access token.  

But how to manually create the refresh token? Is it just a random string or do they contain claims and are encrypted?  

From [here](https://auth0.com/learn/refresh-tokens/), if I assume a refresh token to be: `fdb8fdbecf1d03ce5e6125c067733c0d51de209c`, its not definitely a JWT or is it? So, how do we create one if we are not using Auth0.

**Comment by panva** [comment]
Hi @whimsicaldreamer 

> But how to manually create the refresh token?

I guess here's where the disconnect happens, you don't create a refresh token, refresh tokens are (most commonly opaque) values returned by an Authorization Server, they are not to be created by you manually.

**Comment by whimsicaldreamer** [comment]
@panva Can you give an example of what kind of values are they? I am constructing the whole app on my own and authorization server and the app server are basically the same. So are these opaque values something like unique random strings?

**Comment by whimsicaldreamer** [comment]
@panva Can you give an example of what kind of values are they? I am constructing the whole app on my own and authorization server and the app server are basically the same. So how can I get these values from the server? I am using Node and Express.
