### ISSUE TITLE
Can't install jsonwebtoken due to 3rd party issue

### ISSUE THREAD

**Issue by selenwall** [auth0/node-jsonwebtoken#60]
I receive the following error message when attempting to install jsonwebtoken, npm-version: 1.1.65.

npm http 304 https://registry.npmjs.org/buffer-equal-constant-time
npm ERR! Error: No compatible version found: buffer-equal-constant-time@'^1.0.1'
npm ERR! Valid install targets:
npm ERR! ["1.0.0","1.0.1"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:563:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:478:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:218:7
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

**Comment by jfromaniello** [comment]
Your version of npm is too old.
Try `npm i - g npm` before installing.
