### ISSUE TITLE
Question - How do I re-encode a token?

### ISSUE THREAD

**Issue by bresheske** [auth0/node-jsonwebtoken#600]
**Purpose/Scenario:** 
I'm just looking to create a small unit test that:

1. Creates a new JWT.
2. Verifies the JWT.
3. Decodes the JWT.
4. Edits the JWT (like adds "isAdmin" to the payload)
5. Encodes the JWT.
6. Verifies the JWT and expects the result to be false.

**Issue/Question:**
How do I properly re-encode the JWT object? There is no exported function for re-encoding a JWT in the jsonwebtoken library.  I've tried using other libraries like 'base64url' and appended the JSON.stringify() parts with periods, but I can't get a valid re-encoded token to verify.

Could we get a .encode() method exported?

**Relevant Code:**

The test case:

```typescript
    it(`should not verify compromised token`, () => {
        // create our token
        const subject = `brandon`;
        const displayName = `Brandon`;
        const token = tokenService.createJwt(subject, { displayName });
        const jsonToken = tokenService.decodeToken(token);

        // edit it, like some hacker might try
        jsonToken.payload.isAdmin = true;
        const newToken = tokenService.encodeToken(jsonToken);

        // expect the verifyer to catch the edit
        const isValid = tokenService.verifyJwt(`brandon`, config.auth.audienceName, newToken);
        expect(isValid).toBeFalsy();
    });

```

How I'm signing my tokens:

```typescript

export function createJwt(user: string, extraData:any): string {
    const privateKeyFile = `./signingkeys/${config.auth.privateSigningKey}`;
    const privateKey  = fs.readFileSync(privateKeyFile, 'utf8');
    const signOptions = {
        issuer:  config.auth.issuerName,
        subject:  user,
        audience:  config.auth.audienceName,
        expiresIn:  config.auth.expiresIn,
        algorithm:  config.auth.algorithm
    };

    const token = jwt.sign(extraData, privateKey, signOptions);
    return token;
}
```

I'm configured to use RSA512, if that helps at all.

Thanks

**Comment by rschneiderman39** [comment]
This is an interesting question! I would argue that the described test is attempting to test a 3rd party library (node-jsonwebtoken) which I've come to understand is generally not best practice. What's the intention behind the test? Maybe there is a slightly different way to structure it such that the test covers the logic in your code without relying on 3rd party libraries?

**Comment by bresheske** [comment]
Absolutely.  Fully agree that it's testing a 3rd party library, but since this falls into the security category of my application I feel the test case is fully warranted.  As a user of the token validator, I really want to make sure the validation function works before relying on it to fully secure my system.

The main purpose/case here is to ensure the system catches any altered tokens, like some hacker might try (perhaps to add some claims/payload to elevate privileges).

I'm not sure exactly how I can re-order the code a bit, but am surely open to ideas! I really just need to know how to properly re-encode a valid token and run the verify against it and get that to pass.

**Comment by Ry7n** [comment]
The JWT spec defines how this works; it'd look something like this:

```js
function manpulateToken(token) {
  const contents = jwt.decode(token)
  const parts = jwt.split('.');
  const manipulatedContents = { ...contents, madeUpValues: true };
  return [
    parts[0],
    base64Url(JSON.stringify(manipulatedContents)),
    parts[2]
  ].join('.');
}
```

**Comment by bresheske** [comment]
@Ry7n Thanks! I'll give this a shot soon.  This looks pretty identical to what I tried previously, but I might have done something wrong.

**Comment by bresheske** [comment]
I got it working.  (Thanks @Ry7n) 

Here are the 2 relevant test cases:

```typescript
    it(`should verify re-encoded token`, () => {
        const token = tokenService.createJwt(`brandon`, { displayName: `Brandon R` });
        const isValid = tokenService.verifyJwt(`brandon`, token);
        expect(isValid).toBeTruthy();

        // basically copy the token over and expect it to verify correctly.
        const newToken = tokenService.encodeToken(tokenService.decodeToken(token));
        const newIsValid = tokenService.verifyJwt(`brandon`, newToken);
        expect(newIsValid).toBeTruthy();
    });

    it(`should not verify compromised token`, () => {
        // create our token
        const subject = `brandon`;
        const displayName = `Brandon`;
        const token = tokenService.createJwt(subject, { displayName });
        const jsonToken = tokenService.decodeToken(token);

        // edit it, like some hacker might try
        jsonToken.payload.isAdmin = true;
        const newToken = tokenService.encodeToken(jsonToken);

        // expect the verifyer to catch the edit
        const isValid = tokenService.verifyJwt(`brandon`, newToken);
        expect(isValid).toBeFalsy();
    });

```

And here is the function to re-encode a token:
```typescript
/**
 * just encodes json into a token
 * @param token the user's token
 */
export function encodeToken(tokenJson: any): string {
    return [
        base64url(JSON.stringify(tokenJson.header)),
        base64url(JSON.stringify(tokenJson.payload)),
        tokenJson.signature
    ].join('.');
}
```
