### ISSUE TITLE
Not 'complete' option in JWT.verify() as documented

### ISSUE THREAD

**Issue by Addg14** [auth0/node-jsonwebtoken#601]
Documentation shows 'complete' as a valid option for JWT.verify(), but code doesn't allow it (Not exists in code).

Should be fixed in documentation or code.

**Comment by robinzimmermann** [comment]
It worked for me, but the Typescript type definitions for `@types/jsonwebtoken` don't contain `complete` as an option for `JWT.verify()`.

**Comment by yacineMTB** [comment]
Closing this issue as the community has addressed this issue in another repository. Note; we don't maintain the types in the DefinitelyTyped repository so issues with typing should go there.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/46cb9e443891ccfb931ad823f9b6175aaa14e201/types/jsonwebtoken/index.d.ts#L71
