### ISSUE TITLE
PHP JWT not working nodejs

### ISSUE THREAD

**Issue by SrTristao** [auth0/node-jsonwebtoken#603]
Hellow Guys,

JWT by PHP and trying to authenticate / decode the token by the node, however, it returns the invalid for the verification function and when decoding returns null.

The jsonwebtoken code should be used in JWS more specifically in the function isValidJws of the JWS module that jsonwebtoken is used, well, it is a function of a regex to know if its value is valid and is not valid, funny the procedure in the python I to take the values ​​of token and authenticate it.

``const jwt = require("jsonwebtoken");

const token = jwt.decode("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZW5oYSI6InRlc3RlIiwiY2lwIjoiMTIzMTIzMTIiLCJsYWJvcmF0b3JpbyI6Imxhdm9pc2llciIsImR0bmFzYyI6IjIxXC8wMlwvMTk5MCIsImV4cCI6MTU1ODU1MTczNX0=.EI3z1agtfFqoh2RXsSKCJF61zA4Txj2vTGE+w4JA7t0=");``

The code above return null.

I commented the code that calls the function isValidJws after that the decode function of jsonwebtoken returned the values.

**Comment by panva** [comment]
@SrTristao whatever JWT module is producing that token is not a valid implementation. It is clearly using base64 (notice `+` and `=` padding characters) rather than **base64url with no padding** to encode the components.
