### ISSUE TITLE
TS2326: Types of property 'sub' are incompatible.   Type 'string' is not assignable to type '() => string'.

### ISSUE THREAD

**Issue by dauledk** [auth0/node-jsonwebtoken#604]
I don't know if this is a typings bug, or a library issue.

With the following versions:
`"@types/jsonwebtoken": "^8.3.0"`  
`"jsonwebtoken": "^8.3.0"`

The following snippet:

```typescript
const jsonWebToken = jwt.sign({
            user_id, // The userID
            sub: 'some-sub', // The id from above
            ulimit: 2 // The usage limit
        }, 'shh');
```

throws the error:
```
TS2326: Types of property 'sub' are incompatible.
  Type 'string' is not assignable to type '() => string'.
```

But if I look at the typings:

```typescript
export function sign(
    payload: string | Buffer | object,
    secretOrPrivateKey: Secret,
    options?: SignOptions,
): string;
```

It looks correct?

**Workaround**:
```typescript
const jsonWebToken = jwt.sign({
            user_id, // The userID
            sub: 'some-sub', // The id from above
            ulimit: 2 // The usage limit
        } as any, 'shh');
```

If the `sub` property indeed needs to be `() => string` I would happily like to assist with the PR to the typings, but I am not sure what the problem is 🤷🏽‍♂️

**Comment by amrew** [comment]
I also got the problem.
You can cast it `sub: 'some-sub' as any`. Temporary solution
```
const jsonWebToken = jwt.sign({
            user_id, // The userID
            sub: 'some-sub' as any, // The id from above
            ulimit: 2 // The usage limit
        } as any, 'shh');
```

**Comment by LoicPoullain** [comment]
The weird thing is that the types look correct: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jsonwebtoken/index.d.ts#L121 🤔

**Comment by LoicPoullain** [comment]
It looks like it is a compiler issue. It works with TypeScript 3.4.5 but fails with TypeScript 3.5.1 & 3.5.2.

**Comment by dauledk** [comment]
@LoicPoullain good catch - but why does it fail with Typescript > 3.5.1 🤷🏽‍♂️ ?

**Comment by LoicPoullain** [comment]
No idea 😕 I'm going to open an issue on the TS repo today when I get a chance.

**Comment by LoicPoullain** [comment]
Looks like the bug is fixed in the pending next version of TypeScript. Installing `typescript@next` (version `3.6.0-dev.20190623`) makes the compilation work. We just need to wait for the next release and build with `3.4` for now.

**Comment by panva** [comment]
I'm going to go ahead and close this as there's no TODO in this repo or the types one, which we're not the maintainers of btw.
