### ISSUE TITLE
Algorithms don't work besides HS256-HS512

### ISSUE THREAD

**Issue by TriplexRoss** [auth0/node-jsonwebtoken#605]
Whenever I try to sign something using anything besides HS256-HS512, I get this error:
```
Error: error:0909006C:PEM routines:get_name:no start line
```

My code:
```
let token = jwt.sign({ id: user.id }, cfg.get('jwt.secret'), {
  algorithm: cfg.get('jwt.algorithm'),
  expiresIn: cfg.get('jwt.expiresIn')
});
```

**Comment by panva** [comment]
HS* are HMAC based algorithm, a symmetric secret is the only thing required.

For other algorithms you need a private key to sign or a public one to verify (or a x509 certificate - they contain the public key), an asymmetric key pair. For `jsonwebtoken` these are expected to be passed as PEM-encoded strings or buffers.

Bottom line, your `cfg.get('jwt.secret')` needs to yield a private key if you wish to you use asymmetric Digital Signature JWA like RS, PS, ES or EdDSA
