### ISSUE TITLE
Question: Should EXP calculations really be based on IAT?

### ISSUE THREAD

**Issue by jvanalst** [auth0/node-jsonwebtoken#610]
Here's my scenario... when a user posts the JWT to my application, I'd like the application to renew and resign the JWT with a new expiration time. This is to have much the same behavior as a traditional session, which keeps going indefinitely as long as you don't walk away for too long and let it expire.

On resigning the payload with a new expiration, it looks like it's using the token's **iat** to calculated the **exp** timestamp. E.g. `exp = iat +  timeSpan`. I don't see anything about those two fields being tied together in [RFC 7519](https://tools.ietf.org/html/rfc7519#section-4.1.4). They look like they should be calculated and treated as independent of one another. It's totally possible I missed something, so forgive me if I'm mistaken... But shouldn't **exp** be calculated based on the current timestamp instead? E.g. `exp = Math.floor(new Date()/1000) + timeSpan`.

If **iat** and **exp** really are intrinsically linked in the JWT signing algorithm, can the documentation be updated to make that more explicit?

Example code:

```javascript
let payload = jwt.verify(originalToken, _jwtSecretKey)

//always returns the  exact same token given the same original payload (assuming exp & iat set)
getSignatureWithIAT = () => {
  delete payload.exp

  return jwt.sign(this.payload, _jwtSecretKey, {
    expiresIn: '2h'
  })
}

//works as I'd expect with exp set to Math.Floor((new Date())/1000) + 2 * 60 * 60
getSignatureWithoutIAT = () => {
  delete this.payload.exp
  delete this.payload.iat

  return jwt.sign(this.payload, _jwtSecretKey, {
    expiresIn: '2h'
  })
}

jwt.verify(getSignatureWithIAT(), originalToken) === originalToken //True
jwt.verify(getSignatureWithoutIAT(), originalToken) === originalToken //false
```

**Comment by panva** [comment]
@jvanalst this behaves exactly as documented

> Generated jwts will include an iat (issued at) claim by default unless noTimestamp is specified. If iat is inserted in the payload, it will be used instead of the real timestamp for calculating other things like exp given a timespan in options.expiresIn.

In other words, if an `iat` is already part of the payload the current timestamp used to offset claims like `nbf` or `exp` will be the `iat` value.

**Comment by jvanalst** [comment]
Oh it's hiding down there at the bottom instead of with the expiresIn option.

Thanks.
