### ISSUE TITLE
Yarn install is failing due dependency on gaxios@1.8.5

### ISSUE THREAD

**Issue by marcelijanowski** [auth0/node-jsonwebtoken#613]
I was trying to install a jsonwebtoken package but getting errors
Steps:
1. yarn add jsonwebtoken -S 
2. Error
```
An unexpected error occurred: "https://registry.yarnpkg.com/gaxios/-/gaxios-1.8.5.tgz: Request failed \"404 Not Found\"".
```
I have looked on a gaxios repo and there is not 1.8.5 version
[https://www.npmjs.com/package/gaxios](https://www.npmjs.com/package/gaxios)

**Comment by panva** [comment]
Definitely not because you're trying to install `jsonwebtoken`, `gaxios` is [not](https://github.com/auth0/node-jsonwebtoken/blob/v8.5.1/package.json#L38-L49) our dependency.
