### ISSUE TITLE
Impossible to verify JWTs with a list of algo that contains none

### ISSUE THREAD

**Issue by quentinpraz** [auth0/node-jsonwebtoken#616]
Hello,

I'm trying to verify a JWT: It can be signed (i.e. _HS256_) or not signed (_none_ algorithm). According to the doc, it should be possible by using _algorithms = ['none', 'hs256']_. I did not see anything saying that _none_ algo should be used alone. Unfortunately, this is not possible and I have an error (because I provide a key but no signature).

Is it something that should be possible (and then, there is an issue) or is it a scenario that the library does not want to handle (and it should be stated in the doc).

Thank you.

**Comment by ratulSharker** [comment]
Accepting **none** algorithm causes security vulnerabilities. Newer library implementation of `jwt.verify()` stopped implementing this **none** algorithm. Check details [here](https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/).

**Comment by quentinpraz** [comment]
Accepting the _none_ algorithm is not a security issue if the developer using the library did it on purpose. According to RFC 7519, the _none_ algorithm should be supported. Note that they call _Unsecured JWT_ when the _none_ algorithm is used which makes sense.
The security issue occurs when the _none_ algorithm is accepted by default by the library (which is not the case here). According to the documentation of the library, the none algorithm is supported but as explained in my first post, it is not possible to use _none_ and another algorithm in the same list. So either it is not supported and the documentation should be updated or this is a bug and this should be corrected.

**Comment by panva** [comment]
As far as i can see this is intended, accepting HS256 and none in one code path bears as much security as none on its own - 0.

Please use different code paths for secured and unsecured JWTs.

That being said docs could use updating to reflect that.

**Comment by quentinpraz** [comment]
I agree, having _none_ in list means that any JWTs can be validated. My use case is not a production use case and I totally understand that this is not something you want to support.
