### ISSUE TITLE
The value of "iat" field is invalid json value.

### ISSUE THREAD

**Issue by HtetLynnHtun** [auth0/node-jsonwebtoken#617]
Hello, the token I get is invalid because, the iat field is somehow messed up. You can look at the picture.

My code:
```javascript
jwt.sign(payload, config.get("jwtSecret"), { expiresIn: 360000 }, (err, token) => {
       if (err) throw err;
       res.json({ token });
    });
```

The token is: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWQxYzFhMTA0YTBmOWUyZTc4NzVjODdiIn0sImlhdCI6LgjH2m5c8emE66pjdExmgep47BAdKTrCJ7k2fQ.FKGV9Jm2u7rmsCe65wKzPTw5jtS38n2tVEGifC50VyU`

Decoded :
![Screenshot_1](https://user-images.githubusercontent.com/25409428/61095271-ca629580-a478-11e9-8ee6-7c91413e1cd7.png)

**Comment by ziluvatar** [comment]
Did you provide `iat` field in the payload? Is that token actually coming from the code above? Just asking because it should have `exp` claim too.
