### ISSUE TITLE
JsonWebTokenError - Undocumented Error

### ISSUE THREAD

**Issue by fabltd** [auth0/node-jsonwebtoken#618]
There is little in the documentation to support trouble shooting of the following error:

name: 'JsonWebTokenError',
message: 'invalid token

I have a token generated by a third-party. This verifies with JWT debugger.

Token:

`eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NjMyMTk5MDQsImV4cCI6MTU2MzIyMzUwNCwiYXVkIjoiZ2Fwb3NhLXByb2QifQ==.CoUA1uaytoIGxJUjQwGMvQzJQwUj1jZqcX8hIFjHhnPS6PlTVZf7x4AQ8DujE6noX3UtirPiHziBz5UtQMguBw==`

The following fails with the above error:

```
var publicKEY = fs.readFileSync('../assets/public.pem');
var token = fs.readFileSync('../assets/token.txt', 'utf8');

var jwtok = jwt.verify(token , publicKEY, { algorithm:  ["ES256"] })
console.log('Decoded Token: ', jwtok)

```

I have tried loading the token from a file and inserting it directly both yield the same error.

jwt.decode also fails.

**Comment by quentinpraz** [comment]
Hi, I guess your error comes from the fact that your JWT contains padding (==). Can you try to verify or decode your JWT without padding.
If you want more info, look at this closed issue: #162
