### ISSUE TITLE
Jwt not invalid on logout or blocking a user 

### ISSUE THREAD

**Issue by umar0107** [auth0/node-jsonwebtoken#626]
JWT Auth.0 should provide a function for invalidating the jwt on logout or blocking the user, token should be destroy by calling some function for the user

**Comment by panva** [comment]
this is merely a JWT token validation function with no backend for invalidating issued tokens, as such it is agnostic to the actual JWT application and cannot deliver such functionality out of the box.

You may implement such wrapper around invalidation yourself, preferably based on blacklisting token's `jti` for the remainder of their TTL (based on `exp` claim) or look for an npm module already doing so.

**Comment by jensysantana** [comment]
hi, please i would like to know how to add jti to my tokens, because this librery only have 
iat and exp.
