### ISSUE TITLE
signature of method 'sign' mismatch with behaviour

### ISSUE THREAD

**Issue by eugene-matvejev** [auth0/node-jsonwebtoken#628]
sign method signature:
```
export function sign(
    payload: string | Buffer | object,
    secretOrPrivateKey: Secret,
    options?: SignOptions,
): string;
```
if I am using it like: `jwt.sign('string', 'secret', { expiresIn: '1h' });` it will result in error "invalid expiresIn option for string payload"
but, if I am using it like `jwt.sign({ data: 'string'}, 'secret', { expiresIn: '1h' });` it will be okay

**Comment by panva** [comment]
This is very much the expected behaviour, if you're signing a JSON object the `exp` claim can be put in. If you're signing an arbitrary payload (which btw means the result is not a JWT anymore - all JWT payloads MUST be JSON objects) there's no way to stuff an "exp" or other claims in.

**Comment by eugene-matvejev** [comment]
nice test 💯 👍 , may be some note would be beneficial in 'string' ? as someone might get confused

as i just read definition of the method, options defenition

**Comment by EHadoux** [comment]
In the Readme is written near the beginning:

> Please note that exp or any other claim is only set if the payload is an object literal. Buffer or string payloads are not checked for JSON validity.

So I guess it's kind of documented even though I indeed missed it the first few times.
