### ISSUE TITLE
Typing error with Typescript

### ISSUE THREAD

**Issue by WangHansen** [auth0/node-jsonwebtoken#629]
For `decode` function, if I do this:
```javascript
import { decode } from "jsonwebtoken";

const { header } = decode(token, { complete: true })
```
I got the following error
```Property 'header' does not exist on type 'string | { [key: string]: any; } | null'.```

Another interesting design is when I call `sign` function, the second parameter has type `Secret`, but when I try to call `verify` with the same type, it complains:
```Argument of type 'Secret' is not assignable to parameter of type 'string | Buffer | GetPublicKeyOrSecret'.```
I wonder why cert/secret for the second parameter for `sign` and `verify` function are different types?

**Comment by MarcusPianco** [comment]
I have the same problem but when I'm trying get the {id} decoded.


``any
Property 'id' does not exist on type 'unknown'.ts(2339)``

**Comment by ziluvatar** [comment]
Currently the community is the one adding types for Typescript. I think this PR should fix the first issue (merged 7 days ago):
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39028/files

About the second, the library does not return any `id` field in the response for `decode()`.

If you find any improvement for the types be free to add them there (we don't own that repository).
