### ISSUE TITLE
Add option to suppress claims from `jwt.verify` return value.

### ISSUE THREAD

**Issue by bencmbrook** [auth0/node-jsonwebtoken#634]
`iat` and `exp` get pushed onto the returned object from `jwt.verify`. This can lead to unexpected problems, since the input is not equal to output.

```js
const jwt = require('jsonwebtoken');

const input = { test: 1 };
const token = jwt.sign(input, 'shh', { expiresIn: 100 });
const output = jwt.verify(token, 'shh');

// { test: 1 }
console.log(input);
// { test: 1, iat: 1568878673, exp: 1568878773 }
console.log(output);
```

Can we get an option to suppress these values from the return, so that input and output are the same? Note this also applies to `jwt.decode`.

**Comment by panva** [comment]
🤔 is that really needed given that you can use destructuring?

```js
const jwt = require('jsonwebtoken');

const input = { test: 1 };
const token = jwt.sign(input, 'shh', { expiresIn: 100 });
const { iat, exp, ...output } = jwt.verify(token, 'shh');

// { test: 1 }
console.log(input);
// { test: 1 }
console.log(output);
```

**Comment by bencmbrook** [comment]
There are certainly case-by-case workarounds, but it's more a question of API design. Pushing headers onto the returned payload requires knowledge of all headers that *might* get returned.

**Comment by bencmbrook** [comment]
One possibility: The `complete: true` option could return a fourth object, like `payloadWithoutClaims`. 

It's also weird to not know whether a key on my payload came from the client or was inserted by node-jsonwebtoken. Especially given the standard might change and a [new claim](https://www.iana.org/assignments/jwt/jwt.xhtml) might start appearing in the future.

**Comment by jfromaniello** [comment]
There is no way to determine if the claim was or not part of the input object. 

For example, assuming that we add the option `complete: false`, what would you expect in this case?

```javascript
const input = { iat: 1568898148, other: 'bar' };
const token = jwt.sign(input, 'ssh');
const output = jwt.verify(token, 'shh', { complete:  false });
```

should the output object contains `iat` given that it was part of the original input object?

In other words, the `expiresIn` in the sign method is a convenient way to add an standard claim to the token but is definitely not the only way.

**Comment by bencmbrook** [comment]
Good point @jfromaniello - the claims are technically user inputs and I retract my "It's also weird to not know whether a key on my payload came from..." statement.

> should the output object contains iat given that it was part of the original input object?

I'd say it should be excluded from the output object, given it's a registered claim and there's a reasonable expectation that `iat` is "issued at" for the purposes of JWT verification.

-----
BTW I was referring to the [existing `complete` option](https://github.com/auth0/node-jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback):
> - `complete`: return an object with the decoded { payload, header, signature } instead of only the usual content of the payload.

**Comment by ziluvatar** [comment]
Closing, we are not considering adding support for this at the moment.

**Comment by bencmbrook** [comment]
For the next person, here's the code we use to clean verified JWTs to get the pure payload.

```js
/**
 * Remove extraneous token metadata to get the token payload
 * Note: this list may grow over time: https://www.iana.org/assignments/jwt/jwt.xhtml
 * @param {string} token a JSON Web Token (JWT)
 */
function cleanJWT(token) {
  if (typeof token === 'string') {
    return token;
  }
  const cleanToken = { ...token };
  delete cleanToken.iss;
  delete cleanToken.sub;
  delete cleanToken.aud;
  delete cleanToken.exp;
  delete cleanToken.nbf;
  delete cleanToken.iat;
  delete cleanToken.jti;
  return cleanToken;
}
```

`cleanJWT(jwt.verify(...))`

**Comment by OmaritoAtPoly** [comment]
this a perfect solution.!
