### ISSUE TITLE
Create a method to delete or invalidate the token

### ISSUE THREAD

**Issue by AndreOneti** [auth0/node-jsonwebtoken#635]
## To delete or invalidate toke like

The method name is invalid or deleted.

```js
const data = { test: 1 };
const token = jwt.sign(data, 'shhhh', { expiresIn: 100 });
const invalidate = jwt.invalidate(token, privateKey);
const old_token = jwt.verify(token, 'shhhh');

// { test: 1 }
console.log(data);
// { error: "Invalid/deleted token, create a new" }
console.log(invalidate);
```
or something like this.

**Comment by Bessonov** [comment]
Most of developers doesn't understand that there is no way to invalidate the token in a stateless system. To do that you must introduce a... state. For example you can implement white- or blacklisting of tokens and check every request against this list. Or introduce a session. But well, this is never a part of an jwt library like this one. Look for example at [Single Sign Out](https://stackoverflow.com/questions/44712576/single-sign-out-principle-in-keycloak).

**Comment by panva** [comment]
https://github.com/auth0/node-jsonwebtoken/issues/626#issuecomment-519813568

**Comment by AndreOneti** [comment]
Tks for replying to me about this issue.
I didn't know jwt and didn't know its features completely.
