### ISSUE TITLE
TokenExpiredError instanceof JsonWebTokenError is true

### ISSUE THREAD

**Issue by lrecknagel** [auth0/node-jsonwebtoken#637]
### Description

When dealing with `JsonWebTokenError` and `TokenExpiredError` it came out that the following snippet evaluates to `true`, where I think it should not: `TokenExpiredError instanceof JsonWebTokenError`

### Reproduction

```js
const { JsonWebTokenError, TokenExpiredError } = require('jsonwebtoken');

function jsonWebTokenErrorTest() {
  try {
    throw new JsonWebTokenError('JWTError');
  } catch (error) {
    console.error(error);
    console.log(`isJsonWebTokenError: ${ error instanceof JsonWebTokenError }`);
    console.log(`isTokenExpiredError: ${ error instanceof TokenExpiredError }`);
  }
}
jsonWebTokenErrorTest();

function tokenExpiredErrorTest() {
  try {
    throw new TokenExpiredError('TEError');
  } catch (error) {
    console.error(error);
    console.log(`isJsonWebTokenError: ${ error instanceof JsonWebTokenError }`);
    console.log(`isTokenExpiredError: ${ error instanceof TokenExpiredError }`);
  }
}
tokenExpiredErrorTest();
```

### Environment

> Please provide the following:

- **Version of this library used: 8.5.1**
- **Version of the platform or framework used, if applicable: -**
- **Other relevant versions (language, server software, OS, browser): -**
- **Other modules/plugins/libraries that might be involved: -**

**Comment by panva** [comment]
Absolutely expected,

https://github.com/auth0/node-jsonwebtoken/blob/v8.5.1/lib/JsonWebTokenError.js
https://github.com/auth0/node-jsonwebtoken/blob/v8.5.1/lib/TokenExpiredError.js

`JsonWebTokenError` is a generic error all custom errors from `jsonwebtoken` inherit their prototype from.

**Comment by lrecknagel** [comment]
Thanks for the fast response and explanation. Sorry for the misunderstanding here.
