### ISSUE TITLE
Ensure uniqueness of a token string for the same payload but for two different use cases

### ISSUE THREAD

**Issue by coooolers** [auth0/node-jsonwebtoken#640]
I have two use cases: a. Verify Email Address b. Reset forgotten password

For JWT signing, I am just passing a user Id in the payload. Does JWT signing process make sure that two different (unique) JSON tokens be generated for these two use cases? If not, what do I need to do? Kindly help

Thanks

**Comment by ziluvatar** [comment]
> Does JWT signing process make sure that two different (unique) JSON tokens be generated for these two use cases?

Can you expand on the question? maybe giving examples for each use case

**Comment by EHadoux** [comment]
If I am not mistaken two tokens with the same payload and the same ```exp``` and ```iat``` fields will be identical. However, even in the unlikely case of the same ```iat``` for your two use cases, if you just set a different duration for each, you are almost certain to get a different token.

**Comment by panva** [comment]
> If I am not mistaken two tokens with the same payload will be identical.

Only when signed using a deterministic algorithm - RS and HS family, all other algorithms (ES, PS, EdDSA) are not deterministic and two tokens with the same header and payload will have different signatures.

**Comment by coooolers** [comment]
@panva Thanks. I confirmed it by reading the difference between these two categories of algorithms and I will use the ES256 algorithm.

@ziluvatar When a user registers, we need to verify his email address. To fulfill this need, a JWT token needs to be generated and during the signing process, only the user id is there in the payload. Then the token is sent to the user's email. Similarly, when the same user forgets his password, we again need to generate a JWT token (that should be different from the previous token) and the same user id is again there in the payload.
