### ISSUE TITLE
Please tutorial how to fix "error:0909006C:PEM routines:get_name:no start line" with algorithm: "RS256"

### ISSUE THREAD

**Issue by congthanh13dth06** [auth0/node-jsonwebtoken#642]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

> Provide a clear and concise description of the issue, including what you expected to happen.

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment

> Please provide the following:

- **Version of this library used:**
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by raginisahu** [comment]
I have the same issue.
please give me solution if you have

**Comment by taylankarakas** [comment]
I have the same issue. you must use default algorithm for now.

**Comment by panva** [comment]
@taylankarakas

I've hidden your suggestion. The point behind using an RS private key is so that noone but you can produce the signatures but everyone with the knowledge of your public key can verify it. HS256 is an HMAC based symmetric key (secret) algorithm and you'd be using the octets of malformed private key as the shared symmetric secret. DON'T DO THAT.

> error:0909006C:PEM routines:get_name:no start line

How to fix it? Provide a properly formatted `pkcs8`, `pkcs1`, or `sec1` PEM private key. That's really it.

**Comment by Shub1427** [comment]
Create JWT Token using the command shown [here](https://gist.github.com/ygotthilf/baa58da5c3dd1f69fae9)

**Comment by derN3rd** [comment]
For us we had this issue while loading a private key from ENV instead of files (because of automated deployment in aws).

We fixed it by replacing \n in the env var with real line breaks
```process.env.JWT_PRIVATE_KEY?.replace(/\\n/gm, '\n')```

Hope this helps someone

**Comment by zachgoll** [comment]
Continuing with @derN3rd 's answer, I had to approach this slightly differently.

For me, I was storing my private rsa key in a Gitlab CI/CD environment variable, which I was then reading into a file (this file was then read by the code I was testing). 

```
touch priv_key.pem
echo "$MY_PRIV_KEY_ENV_VARIABLE" > priv_key.pem
```

Where I was going wrong was in the `echo` statement.  As you see above, **I am surrounding the environment variable with double-quotes.**  This is significant because by surrounding the variable with double-quotes, it preserves the `\n` character in the private key.

When I was just using the statement `echo $MY_PRIV_KEY_ENV_VARIABLE > priv_key.pem`, it was adding spaces where the `\n` character was and causing the error mentioned in this issue `error:0909006C:PEM`

Source - https://stackoverflow.com/a/50016491/7437737

**Comment by mendoncaj** [comment]
> For us we had this issue while loading a private key from ENV instead of files (because of automated deployment in aws).
> 
> We fixed it by replacing \n in the env var with real line breaks
> `process.env.JWT_PRIVATE_KEY.replace(/\\n/gm, '\n')`
> 
> Hope this helps someone

Very useful, tks.

**Comment by kimfucious** [comment]
Just to add a bit of clarification to @derN3rd 's solution, which is great btw, adding `\n`s to the env variable is a necessary step, prior to replacing them on the client side.

I also did **not** use quotes to surround the value.

Something like this:

```console
-----BEGIN PRIVATE KEY-----\nLONG_STRING_HERE\n-----END PRIVATE KEY-----
```

**Comment by ORESoftware** [comment]
i mean if we validate the file's contents with `openssl` then there must be some other problem going on?

**Comment by bakgaard** [comment]
For Windows users with PowerShell and OpenSSL.Light installed who needs to extract everything between ``----BEGIN CERTIFICATE-----`` and ``----END CERTIFICATE-----``:

```powershell
openssl s_client -showcerts -connect YourWebsite:port | Select-String -Pattern '-----BEGIN' -Context 0,21 | Foreach { $_ -replace "  ", ""} | Foreach { $_ -replace "> ", ""} | Foreach { $_ -replace "/\\n/gm", "\n" } | Set-Content 'OutputFile.crt'
```

**Comment by patriciali** [comment]
I got this because I was accidentally signing with my public key 🤦‍♀️

**Comment by hochmanjoel** [comment]
> For us we had this issue while loading a private key from ENV instead of files (because of automated deployment in aws).
> 
> We fixed it by replacing \n in the env var with real line breaks
> `process.env.JWT_PRIVATE_KEY.replace(/\\n/gm, '\n')`
> 
> Hope this helps someone

I selected every reaction. This helped me so so so much. THANK YOU

**Comment by alex-drocks** [comment]
> For us we had this issue while loading a private key from ENV instead of files (because of automated deployment in aws).
> 
> We fixed it by replacing \n in the env var with real line breaks
> `process.env.JWT_PRIVATE_KEY.replace(/\\n/gm, '\n')`
> 
> Hope this helps someone

For me it did not work in Google Cloud Platform Cloud Functions. Deploy works but function crashes with the error code.
I got tired of the error so I use a javascript string litteral and copy pasted my private key there instead of the process.env variable

**Comment by AustEcon** [comment]
Try this:

`iconv -c -f UTF8 -t ASCII  myprivate.key >> myprivate.key`

Converting from utf-8 to ASCII made it work for me 😄 

ref: https://stackoverflow.com/questions/43729770/nginx-godaddy-ssl

**Comment by tunexlevel** [comment]
I was placing the key and crt interchangeably. So placing it rightly solve mine.

**Comment by ivenuss** [comment]
I accidentally exchanged private key and certificate.

**Comment by Usman-Qasim** [comment]
This is the complete solution of the problem.
First to generate SSL certificates, then create a HTTPS server via these certificates, after that implement Secure Web Sockets.
1st:
Generate SSL certificates via OPENSSL.
These are the 3 commands 

openssl genrsa -out abels-key.pem 2048
openssl req -new -sha256 -key abels-key.pem -out abels-csr.pem
openssl x509 -req -in abels-csr.pem -signkey abels-key.pem -out abels-cert.pem

2nd: Code 
const express = require("express");
const https = require("https");
const fs = require("fs");
const WebSocket = require("ws");

const app = express();
let cert = fs.readFileSync("abels-cert.pem");
let key = fs.readFileSync("abels-key.pem");
const options = {
  key,
  cert,
};

app.get("/", async (req, res) => {
  res.send("Server is Running on HTTPs and WSS");
});

var server = https.createServer(options, app);

server.listen(443, () => {
  console.log("Server is Running on PORT 443");
});

const wss = new WebSocket.Server({ server });

wss.on("connection", function connection(ws) {
  console.log("Connection has been established successfully");
  ws.on("message", function incoming(message) {
    console.log("received: %s", message);
  });

  ws.send("something");
});

Note:
In Online server you may face 3 problems,
1st PORT
2nd (URL), WSS will not work with IP Address (In my Case new WebSocket("wss://localhost") its work fine, new WebSocket("wss://127.0.0.1 or wss://127.0.0.1:443")) not working as expected.
3rd Certificates issues.

There are some online resources which helps us to validate our certificates

**Comment by SleeplessChallenger** [comment]
Hello, everyone! Another possible way is to have both: private and public key already (.crt. and .key), then:

- `cat file.key > file.pem`
- `cat file.crt >> file.pem`

Because our .pem is a concatenation of both files

**Comment by codcodea** [comment]
npm install jsonwebtoken
npm install jwk-to-pem

const jwt = require("jsonwebtoken");
const jwkToPem = require('jwk-to-pem')

const keyObjectInJWTformat = 
{
use: "sig",
kty: "RSA",
kid: "ins_21yJfbfkj-shortstring-Rk9vqfdsfdshasCu1i",
alg: "RS256",
n: "0Cbcyd-longltring-j5hzvZViw",
e: "AQAB"
},

const pem = jwkToPem(keyObjectInJWTformat)
console.log(PEM)

-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9dsfdsfdsfgKCAQEA0Cbcyd+01Wb8X6eWSct1Qz3qG8txsfsdfdApvWhopetosaveyouadayxGYq+S4EEFvO/z1luNhZeNXRPLgg9fsdlsdjaPk5FWvYWbMgNmTt/rpdZYSChda4opensourceh*llAme0zPUp+TbkX+OQ/cdffsfsQJ84uVjmjiBeHmQgZSWWOHNOcqGA6icap7JY0erBNIstoh1yfsdUH0Fs9WowBXiwci9B8lAjQtD8YOLk/dnEznt91tAp3C6vsdfds2zePSIgxCUT6sbytwj5hzvZViwIDAQAB
-----END PUBLIC KEY-----

jwt.verify(token, pem,  { algorithms: ['RS256']}, (err, decoded) => {
if(decoded) console.log(decoded);
if(err) console.log(err.name, err.message);	
});

**Comment by catogonzalez** [comment]
Had this same issue. My problem was I used the `auth0.pem` file downloaded from Auth0 dashboard > tenant settings > Signing keys, but that is actually a provate key!. To validate the JWT token you need to generate the `.pub` file from that certificate. So, I had to run:

`openssl x509 -pubkey -noout -in auth0.pem  > pubkey.pem`

And use the `pubkey.pem` to verify your JWT tokens.
