### ISSUE TITLE
Does the ES256 have a plan to support the S-256 curve?

### ISSUE THREAD

**Issue by babybabyboy** [auth0/node-jsonwebtoken#643]
Does the ES256 have a plan to support the S-256 curve?

**Comment by ziluvatar** [comment]
ES256 uses P-256 curve. I can't manage to find information about the `S-256` curve.

Closing, in any case [JWA specification](https://tools.ietf.org/html/rfc7518) and https://github.com/brianloveswords/node-jwa would need to defined and implement respectively support for any new curve/algorithm.
