### ISSUE TITLE
How can I verify the JWT token generated by bundle ssl certificate?

### ISSUE THREAD

**Issue by ibrahimsakar** [auth0/node-jsonwebtoken#644]
There is an IdentityServer4 based Single Sign-On project and it generates a token from SSL certificate. After bundled the SSL certificate with CA and Root certificate I cannot verify the signature of the token. I'm getting a new public key from new bundled SSL with the OpenSSL tool but the new public key does not verify the signature of the token. I don't know how to solve this.

- I tried to get a new public key from the bundled certificate.
- I used the token and public key on jwt.io and the signature is not verified.
- I'm temporarily using the jwt.decode method of jsonwebtoken package on NPM.

I'm extracting the public key with this command.

`openssl pkcs12 -in <filename>.pfx -clcerts -nokeys -out cert.pem // I used this public key`

```
jwt.verify(token, publicKey, options); // it's not working. Because public key is not working.
jwt.decode(token); // it's working. But I should verify the token.
```

**Comment by ziluvatar** [comment]
> There is an IdentityServer4 based Single Sign-On project and it generates a token from SSL certificate.

Not sure if I understand correctly the context, are you signing using a private key?

**Comment by yacineMTB** [comment]
Going to close this issue due to inactivity. Feel free to reopen if you want to follow up 🙂
