### ISSUE TITLE
Is there a way to decrypt an encrypted token?

### ISSUE THREAD

**Issue by yuvigrg** [auth0/node-jsonwebtoken#649]
Hi,

I am trying to decrypt a token which has been encrypted using the public key. I have access access to the private key before verifying the signature. 

I cannot find any function available in this package. Can anyone guide me here?

**Comment by panva** [comment]
`jsonwebtoken` does not implement JWE (JSON Web Token Encryption), you can give the [`jose`](https://github.com/panva/jose) package a try if you need both JWT/S and JWE.

**Comment by yuvigrg** [comment]
@panva it was my next to go. I was checking if this package had it.
