### ISSUE TITLE
jwt.sign not working with Node 13 ES modules?

### ISSUE THREAD

**Issue by magic8baller** [auth0/node-jsonwebtoken#650]
I am trying to use Node's latest stable version (13) Modules that require "type": "module" in package.json.
I haven't had any issues with other packages so far but trying to use jwt.sign() returns TYPE ERROR: jwt.sign is not a function
Using the same code with Common Modules, it works like it should.
I've just been importing them as import jwt from "jsonwebtoken"

Not sure if jsonwebtoken is incompatible with Node's ES Modules?

**Comment by Afzal95** [comment]
May be you have'nt required it correctly, I was also facing same issues.

**Comment by YOGESHDHANGAR** [comment]
Afzal95 thanks bro
