### ISSUE TITLE
get "invalid signature" when try to verify

### ISSUE THREAD

**Issue by PeichengLiu** [auth0/node-jsonwebtoken#653]
### Description

sign and verify works fine in simple test, but not in simple Express APP with SECRET as String. While it work with SECRET as `Buffer`.

### Reproduction

1. clone this repository: [PeichengLiu/track-server](https://github.com/PeichengLiu/track-server.git).
2. install dependencies.
3. run simple test, `node src/test.js`, all fine.
4. run express app, `npm run dev`.
5. send post request to `http://127.0.0.1:1234/signup`, we can get token; and then try to visit `http://127.0.0.1:1234/`, we can get expected response.
6. directly use SECRET as String in file `authRoutes.js` and `requireAuth.js` to sign and verify. You'll find that JWT NOT work as expected.

### Environment

OS Name: Microsoft Windows 10 Pro
OS Version: 10.0.18362 N/A Build 18362
Node.js:  v12.14.0

**Comment by ziluvatar** [comment]
I run the verification using the token and secret you have in your code and it worked well.
https://runkit.com/embed/5okn9wbwg9ot

**Comment by PeichengLiu** [comment]
Thanks! It does not work in Express APP.

**Comment by Jalson1982** [comment]
I tried 1000 options but always get the same error : JsonWebTokenError: invalid signature. Impossible to make it work even with @PeichengLiu  solution.

**Comment by lukaswilkeer** [comment]
Experiencing the same issue, with the express doesn't work, and with the node script/environment or/and the jwt.io debugger works well.

On the script I've attempted to verify if is asynchronicity by doing a composition, decode(encode(payload, secret_key))
On the express works the same way, but nothing works. The tests are passing, but when you try to get the token from the headers, I get the invalid signature. I've checked if the authorization header are wrong on jwt.io but are passing.

I've attempted over curl and postman.

What could be causing this issue?

**Comment by CoranH** [comment]
I think I'm having this same issue. I did a comparison using Python code and PyJWT, and that verifies the signature fine with the same JWT/PEM strings. So something jsonwebtoken is either doing differently or not doing.
I'm using NestJS, which is Express underneath.

**Comment by Cristiano-Rodrigues** [comment]
I found the same issue when I was working with express. First I thought the problem was in my code but I tried to follow the execution of jsonwebtoken itself. In the file verify.js I found this code that actualy verifies the token validity, starting from line 162:
```javascript
    let valid;

    try {
      valid = jws.verify(jwtString, decodedToken.header.alg, secretOrPublicKey);
    } catch (e) {
      return done(e);
    }

    if (!valid) {
      return done(new JsonWebTokenError('invalid signature'));
    }
``` 
I tried to call jws.verify function with hardcoded values (the same I used to call jwt.verify function) and it strangely worked:
```javascript
    const token = 'hard_coded_token'
    const secret = 'a_very_strong_salt_key'
    try {
      valid = jws.verify(token, 'HS256', secret);
    } catch (e) {
      return done(e);
    }
``` 
For some reason calling it with the hard coded values is working. I don't know exactly why, but I guess is something you're doing or not doing.

**Comment by PeichengLiu** [comment]
It's been years and I cannot reproduce it now.
