### ISSUE TITLE
Token Destroy Method

### ISSUE THREAD

**Issue by DevashishSuthar** [auth0/node-jsonwebtoken#656]
I want to know about that why jsonwebtoken package does not provide destroy method to kill the token. I am getting stuck to find out the solution How to set expire time to 0 or current time while logout in NodeJSapp?
Please give me the proper solution for that.

**Comment by ziluvatar** [comment]
In short: keeping a blacklist of tokens.

You can read these to get a better idea about the problem space and possible solutions:
https://github.com/auth0/node-jsonwebtoken/issues/375
https://github.com/auth0/node-jsonwebtoken/issues/626
https://auth0.com/blog/2015/03/10/blacklist-json-web-token-api-keys/
