### ISSUE TITLE
Error in Docker: Type 'string' is not assignable to type 'Algorithm[]'

### ISSUE THREAD

**Issue by lucbas** [auth0/node-jsonwebtoken#661]
### Description

Hi all 👋🏼

We are running into the following error when we trying to deploy and run our code inside a docker container. We have no issues at all when trying to run the code directly from the IDE, but have been trying to debug this error for the entire day:

```
  node_modules/@types/jsonwebtoken/index.d.ts:65:5
    65     algorithms?: Algorithm[];
           ~~~~~~~~~~
    The expected type comes from property 'algorithms' which is declared here on type 'VerifyOptions'
  node_modules/@types/jsonwebtoken/index.d.ts:65:5
    65     algorithms?: Algorithm[];
           ~~~~~~~~~~
    The expected type comes from property 'algorithms' which is declared here on type 'VerifyOptions'

src/libs/tokenManager.ts:82:32 - error TS2769: No overload matches this call.
  Overload 1 of 3, '(token: string, secretOrPublicKey: Secret, options?: VerifyOptions): string | object', gave the following error.
    Type 'string' is not assignable to type 'Algorithm[]'.
  Overload 2 of 3, '(token: string, secretOrPublicKey: string | Buffer | { key: string | Buffer; passphrase: string; } | GetPublicKeyOrSecret, callback?: VerifyCallback): void', gave the following error.
    Argument of type '{ algorithms: string; }' is not assignable to parameter of type 'VerifyCallback'.
      Object literal may only specify known properties, and 'algorithms' does not exist in type 'VerifyCallback'.
  Overload 3 of 3, '(token: string, secretOrPublicKey: string | Buffer | { key: string | Buffer; passphrase: string; } | GetPublicKeyOrSecret, options?: VerifyOptions, callback?: VerifyCallback): void', gave the following error.
    Type 'string' is not assignable to type 'Algorithm[]'.

82         let decodedData: any = Jwt.verify(token, cert, { algorithms: 'HS256' })
```

### Reproduction

Build the image on the GitLab runner - dnd.
I also then tried to directly log in to the docker container with: 
`docker run -it --entrypoint /bin/bash <image> -s`

Originally, the algorithm parameter comes from an environment variable, but we've also tried to directly insert `HS256` into the code with no luck so far.

### Environment

- Node:10 Docker image
- Typescript v3.7.4
- node-jsonwebtoken v^8.5.1
- Gitlab Runner (dind -> docker-in-docker)

Thank you!

**Comment by panva** [comment]
Hi @lucbas the `algorithms` verify method option is meant to be an array of strings, not a string.

<img width="791" alt="Screenshot 2020-01-16 18 59 17" src="https://user-images.githubusercontent.com/241506/72550116-4efff780-3892-11ea-844f-288be29c692d.png">
