### ISSUE TITLE
Invalid header algorithm when verify JWT generated with .NET/C#  (W3c URL?)

### ISSUE THREAD

**Issue by talesluna** [auth0/node-jsonwebtoken#662]
### Description

> I have a JWT generated by an .NET application and i have the key used to sign they, but the header of this JWT has a w3c url on "alg" property and for this can't be verified with jsonwebtoken

Alg should be HS256, but ...

```json
{
  "$type": "System.IdentityModel.Tokens.Jwt.JwtHeader, System.IdentityModel.Tokens.Jwt",
  "alg": "http://www.w3.org/2001/04/xmldsig-more#hmac-sha256",
  "typ": "JWT"
}
```

### Reproduction

> Generate JWT with .NET
```c#
using System;
using System.IdentityModel.Tokens;
using Thinktecture.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;

var token = new JwtSecurityToken(issuer, audience, claims, issued, expires, key);
```

> Try to verify with jsonwebtoken
```js
jwt.verify(token, key, (err, decoded) => {});
jwt.verify(token, key, { algorithms: ['HS256'] }, (err, decoded) => {}); // Same result
```

> Results
$ invalid algorithm

### Environment

> Please provide the following:

- **Version of this library used: 8.5.1**
- **Other relevant versions (language, server software, OS, browser): NodeJS on MacOs**

How to verify this JWT without change the .NET application ?

**Comment by ziluvatar** [comment]
Unfortunately that value for `alg` is not in the spec. You will need to modify the application.
Allowed algorithm values for `alg` header: https://tools.ietf.org/html/rfc7518#section-3.1
