### ISSUE TITLE
Include ignoreExpiration option to jwt.decode()

### ISSUE THREAD

**Issue by gabrielmmontenegro** [auth0/node-jsonwebtoken#663]
Hi,

Including ignoreExpire option to jwt.decode(), as available on jwt.verify(), would increase the flexibility of jsonwebtoken lib. Sometimes we just need to use jwt.decode() to quickly access the payload, letting verify() do all the verification job.

Regards,
Gab

**Comment by panva** [comment]
Hi @gabrielmmontenegro, `#decode()` does not need a `ignoreExpire` option because it does not do any verification of the claims.

**Comment by gabrielmmontenegro** [comment]
Hey @panva, I must have made a mistake with some unofficial documentation. I did the verification directly in the source code, and it really doesn't happen. I appreciate your quick reply and attention. Regards, Gab
