### ISSUE TITLE
what is the metric for expiresIn attribute in the JWT token ?

### ISSUE THREAD

**Issue by Divine1** [auth0/node-jsonwebtoken#666]
![image](https://user-images.githubusercontent.com/10482177/73169160-820f7a00-4121-11ea-813a-cdcce30e91be.png)

the detail present in the documentation is confusing for me. Should i assign the `value` for `expiresIn` attribute in seconds or milliseconds?

**Comment by yacineMTB** [comment]
If it's a numerical value, it will be interpreted as seconds.

if `expiresIn` is 1, as in `typeof 1` returns `'number'`; it will be interpreted as expiring in 1 second.

If it is a string value, it will be interpreted as milliseconds. If expiresIn is `"100"`, it will be interpreted as expiring in 100 milliseconds.

Hope that helps!

**Comment by Govrdhn** [comment]
how can we compare its returned value with current time, I'm using javascript `date` object, but it is always returning a higher value than the `exp` value returned by the `jwt`

**Comment by Divine1** [comment]
can you set a longer value for expiresIn property (like an year) and verify? 

Share your code if possible @Govrdhn

**Comment by Govrdhn** [comment]
```
let decodedToken;
try {
        decodedToken = jwt.verify(token, process.env.JWT_TOKEN)
    } catch (error) {
        return res.status(401).send("invalid authentication credentials!")
    }
    if (!decodedToken.hasOwnProperty("mail")) {
        return res.status(401).send("invalid authentication credentials!")
    }

    const { exp, mail } = decodedToken
    if (exp < new Date().getTime() / 1000) {
        return res.status(401).send({ message: "Token has expired" })
    }
```
I've got a 13 digit number with the `getTtime()` method, but a 10 digit one with the `exp` in the jwt token. As of now, I'm truncating the number by the last three digits by dividing with 1000, but I'm not sure it would be accurate.

**Comment by Divine1** [comment]
@Govrdhn 

in your approach, i think you are trying to check if `Token has expired` and then return an appropriate http status code.
i would suggest below approach instead of the approach you have tried.

i have tested below program with `"jsonwebtoken": "^9.0.2"` . 

In this program, 
- `expiresIn` is set to 10 seconds. 
- `setInterval` is added to check for validity of the `jwt` token every `1 second`. 

when you run below program, you will notice that after 10seconds, the program would throw `TokenExpiredError` . 


So, in your usecase, you can try to catch this exception and return ` return res.status(401).send({ message: "Token has expired" })` . 


```
var jwt = require('jsonwebtoken');
const { TokenExpiredError } = jwt;
var token = jwt.sign({ foo: 'bar' }, 'shhhhh' , {
    expiresIn : "10000" // token will expire in 10 seconds
});
console.log("token ",token);

var decoded = jwt.verify(token, 'shhhhh');
console.log("decoded ",decoded) // bar

let intervalObj;
intervalObj = setInterval(()=>{
    try{
        var decoded = jwt.verify(token, 'shhhhh');
        console.log("decoded ",decoded) // Once the setInterval exceeds 10 seconds you will see TokenExpiredError
    }
    catch(error){
        if(error instanceof TokenExpiredError){
            console.log("TokenExpiredError occured")
        }
        else{
            console.log("some other exception occured")
        }
        clearInterval(intervalObj);
    }
},1000)
```
![image](https://github.com/user-attachments/assets/da632727-0e31-4ab0-bb11-c81fe2ee8182)

**Comment by Govrdhn** [comment]
Sorry I didn't send the complete code. And you did understand my scenario wrong.
````
const verifyForgotPasswordToken = async (req, res) => {
    const { token } = req.query
    if (!token) {
        return res.status(401).send("token not found!")
    }

    let decodedToken
    try {
        decodedToken = jwt.verify(token, process.env.JWT_TOKEN)
    } catch (error) {
        return res.status(401).send("invalid authentication credentials!")
    }
    if (!decodedToken.hasOwnProperty("mail")) {
        return res.status(401).send("invalid authentication credentials!")
    }

    const { exp, mail } = decodedToken
    if (exp < new Date().getTime() / 1000) {
        return res.status(401).send({ message: "Token has expired" })
    }

    await pool.query(
        `SELECT *, to_json(roles) as roles_array FROM users WHERE mail = $1`, [mail]
    ).then((result) => {
        return res.status(200).send({ message: "verification successful!", data: result.rows[0] })
    })
}
````
Here I want to verify a request sent by user, which may be sent anytime between 2 hours from the token generation.  And I'm getting the `exp` as a 10 digit and the `Date.getTime()` as a 13 digit number as I said before. Hope you get me right and sorry, if my explainantion was bad.

Thanks for a quick response.

**Comment by Divine1** [comment]
> And I'm getting the `exp` as a 10 digit and the `Date.getTime()` as a 13 digit number as I said before

`expiresIn` - has value is seconds (10 digits)

`new Date().getTime()` - returns value in milliseconds (13 digits)

IMO, conversion from milliseconds to seconds is necessary to do a comparison here. i'm not sure if there are any alternatives

**Comment by Govrdhn** [comment]
Yeah, I too don't think it's a big deal if we do it in the current way or find an alternative. Anyway, thanks for everything.
