### ISSUE TITLE
How do we set a refresh token and set expiry time for a jwt? 

### ISSUE THREAD

**Issue by theshashiverma** [auth0/node-jsonwebtoken#667]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

> I am following an article and want to implement JWT on a reactjs app with a fake backend and I am following this article https://jasonwatmore.com/post/2017/12/07/react-redux-jwt-authentication-tutorial-example So far, I have added the login and logout with but I don't know how to add an expiry time for jwt and how to add refresh token for jwt.  
### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment

> Please provide the following:

- **Version of this library used:**
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by yacineMTB** [comment]
>how to add an expiry time for jwt

You can add it using the expiresIn option on the sign function. You can read more about the function signature [here](https://github.com/auth0/node-jsonwebtoken/blob/master/README.md#jwtsignpayload-secretorprivatekey-options-callback).

>how to add refresh token for jwt

This library doesn't have logic for refreshing tokens. You'll have to add the logic yourself. [You can find some additional information/hints here](https://github.com/auth0/node-jsonwebtoken#refreshing-jwts).

Hope that helps 🙂
