### ISSUE TITLE
Consider changelog

### ISSUE THREAD

**Issue by albertorestifo** [auth0/node-jsonwebtoken#67]
Please consider the implementation of a changelog.

I spent 30 minutes trying to figure out what was the breaking change in the `v4.0.0` release.  At least major releases should be well documented.

**Comment by jfromaniello** [comment]
Thanks, I've started using this format http://keepachangelog.com/

**Comment by paambaati** [comment]
Guys, would you mind updating the changelog for 5.0.0?

**Comment by pose** [comment]
@paambaati Done, sorry for the delay.
