### ISSUE TITLE
RS256 problem 4.2.x

### ISSUE THREAD

**Issue by graovic** [auth0/node-jsonwebtoken#70]
Hi,

this package have a problem with decoding RS256 signed messages

var jwt = require('jsonwebtoken');
var fs = require('fs');
var cert_pub = fs.readFileSync('app.rsa.pub');
var cert_priv = fs.readFileSync('app.rsa');

var token = jwt.sign({ foo: 'bar' }, cert_priv, { algorithm: 'RS256'});
jwt.verify(token, cert_pub, function(err, decoded) {
    console.log("Decoded: " + JSON.stringify(decoded));
    console.log("Error: " + err);
});

This code woks fine in 4.1.0, but on 4.2.0 version problem is with verifying token.

**Comment by jfromaniello** [comment]
What's the error you get? It seems to be working fine for me. Check the test I added on the branch issue_70.

**Comment by graovic** [comment]
~/ cat package.json| grep json
    "jsonwebtoken": "4.1.0",
~/ node testtoken.js  
Decoded: {"foo":"bar","iat":1426605073}
Error: null

 ~/ cat package.json| grep json
    "jsonwebtoken": "^4.2.0",
~/ node testtoken.js
Decoded: undefined
Error: JsonWebTokenError: invalid signature

**Comment by jfromaniello** [comment]
can you give me the first line of your app.rsa.pub file? thanks

**Comment by graovic** [comment]
-----BEGIN PUBLIC KEY-----

**Comment by jfromaniello** [comment]
got it! Thanks, it should be fixed on 4.2.1

**Comment by jedwards1211** [comment]
uhhh...my `id_rsa.pub` looks different:

```
ssh-rsa <KEY> <TOKEN>
```

Should this format be supported by jsonwebtoken?
