### ISSUE TITLE
About expiresIn,how to prevent clients from tampering with system time?

### ISSUE THREAD

**Issue by ddxl123** [auth0/node-jsonwebtoken#700]
Is the expiration time based on the client system time or the server system time? If it is a client, how to prevent the client system time from being tampered with? If it is a server, how to prevent the server system time from being tampered with?
And, what is the difference between expiresIn and notBefore?

**Comment by panva** [comment]
- `exp` is the timestamp **after** which you don't accept a token **anymore**
- `nbf` is the timestamp **before** which you don't accept a token **yet**

Timestamps are always evaluated by whomever is consuming the token. In general it is best practice to allow a reasonable clock skew when it comes to evalution, but JWT as a format does not deal with local time setting tampering. At some point there needs to be an authority that knows its local time setting is correct that also processes the JWT.

**Comment by yacineMTB** [comment]
Closing, feel free to reopen if you need any further clarifications
