### ISSUE TITLE
RFC confrontation on "none" algo

### ISSUE THREAD

**Issue by frankli0324** [auth0/node-jsonwebtoken#711]
### Description

According to https://tools.ietf.org/html/rfc7518#section-3.6, jws s "MUST NOT accept such objects as valid unless the application specifies that it is acceptable for a specific object to not be integrity protected"

### Reproduction

```javascript
> var token = jwt.sign({'a':1}, 'asdf', { algorithm: 'none'})
undefined
> jwt.verify(token)
{ a: 1, iat: 1587359376 }
```

maybe we should add some kind of switch options?

### Expected output:

```javascript
> var token = jwt.sign({'a':1}, 'asdf', { algorithm: 'none'})
undefined
> jwt.verify(token)
throws error
> jwt.verify(token, '', { algorithm: 'none'})
{ a: 1, iat: 1587359376 }
```

**Comment by frankli0324** [comment]
### Expected output:

```javascript
> var token = jwt.sign({'a':1}, 'asdf', { algorithm: 'none'})
undefined
> jwt.verify(token)
throws error
> jwt.verify(token, '', { algorithm: 'none'})
{ a: 1, iat: 1587359376 }
```

**Comment by frankli0324** [comment]
https://github.com/auth0/node-jsonwebtoken/blob/5f10bf9957a2541828501cfecab0310908b2f62f/verify.js#L109-L111

so it's intentional?

**Comment by panva** [comment]
@frankli0324 `none` won't be automatically accepted unless the developer provided no `keyOrSecret`. The three lines in isolation aren't the whole story.

https://github.com/auth0/node-jsonwebtoken/blob/5f10bf9957a2541828501cfecab0310908b2f62f/verify.js#L101-L118

**Comment by frankli0324** [comment]
from my point of view, providing no secret doesn't mean that one explicitly "specifies that it is acceptable for a specific object to not be integrity protected", more like a mistake one could jump into

**Comment by panva** [comment]
We'll consider making the `algorithms` option required when accepting unsigned JWTs for the next major.

**Comment by frankli0324** [comment]
seems that this issue is forgotten?
