### ISSUE TITLE
get "invalid token"  when white space in token

### ISSUE THREAD

**Issue by radekcz83** [auth0/node-jsonwebtoken#713]
Problem: An "Invalid token" error occurs when there is a space in the jwt token when calling the VERIFY function.
`eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJnZHByIjpbeyJsaW5rIjoid3d3LnByb2RvbWlhLmN6JTJGb3NvYm5pLXVkYWplIiwibmFtZSI6IlBST0RPTUlBJTJDJTIwcy5yLm8uIn1dLCJlbWFpbCI6ImxAbWFpbGluYXRvci5jb20iLCJzY29wZSI6WyJSRUdJU1RFUiJdLCJpYXQiOjE1ODc2NDMxMDYsImV4cCI6MTU4NzY4NjMwNiwiYXVkIjoiaHR0cDovL2hzZmcuY3oiLCJpc3MiOiJIU0ZHIiwic3ViIjoibWljaGFsQGRldnguYWdlbmN5In0.kmzMVIp_4IKW89dH5QV5RaM0tptCaV0DdKcBr1H8aZhX27LF5LGyR5HJ5u_j%20McDfS-DZbpor4D-ZKr8pXVPpFw
`

When the space is removed, everything is fine.
`eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJnZHByIjpbeyJsaW5rIjoid3d3LnByb2RvbWlhLmN6JTJGb3NvYm5pLXVkYWplIiwibmFtZSI6IlBST0RPTUlBJTJDJTIwcy5yLm8uIn1dLCJlbWFpbCI6ImxAbWFpbGluYXRvci5jb20iLCJzY29wZSI6WyJSRUdJU1RFUiJdLCJpYXQiOjE1ODc2NDMxMDYsImV4cCI6MTU4NzY4NjMwNiwiYXVkIjoiaHR0cDovL2hzZmcuY3oiLCJpc3MiOiJIU0ZHIiwic3ViIjoibWljaGFsQGRldnguYWdlbmN5In0.kmzMVIp_4IKW89dH5QV5RaM0tptCaV0DdKcBr1H8aZhX27LF5LGyR5HJ5u_jMcDfS-DZbpor4D-ZKr8pXVPpFw`

As a temporary solution, I chose to remove the space (`token.replace (' ', '')`), is there a better solution?

**Comment by panva** [comment]
> Problem: An "Invalid token" error occurs when there is a space in the jwt token when calling the VERIFY function.

Hi @radekcz83, I don't see why it would be expected that this results in anything but an invalid token error :) the charset of a JWT is very well defined to be base64url, a space (or urlencoded `%20`) in the token clearly means its malformed - invalid.

**Comment by Misioka** [comment]
Well then maybe it's a bug in `sign` function. I experiencing the same error. Sign generates a token with whitespace. Any solution?

**Comment by panva** [comment]
@Misioka steps to reproduce please.

**Comment by talaikis** [comment]
+1, happens unexpectedly. Probably will add replace and see will it work.
