### ISSUE TITLE
Header option should be used without any modification

### ISSUE THREAD

**Issue by weslenng** [auth0/node-jsonwebtoken#714]
### Describe the problem you'd like to have solved

I'm trying sign a JWT token with the header:
```javascript
const token = jwt.sign(payload, secret, {
  header: {
    typ: "JWT",
    alg: "HS256",
  }
});
```

But inside the `jsonwebtoken`, the header option is assigned with the default header values:
```javascript
var header = Object.assign({
  alg: options.algorithm || 'HS256',
  typ: isObjectPayload ? 'JWT' : undefined,
  kid: options.keyid
}, options.header);
```

This behavior invert the typ and alg position and add a kid property to header:
```javascript
{ alg: "HS256", typ: "JWT", kid: undefined }
```

### Describe the ideal solution
I think when `options.header` is provided, it should be used without any modifications

**Comment by jhiner** [comment]
Hello, I'm curious why the order of `typ` and `alg` matters here? The meaning is the same regardless if of which "order" the properties appear. 

Also, in my testing, I don't see a `kid` property added to the header. Can you elaborate on how you produced that result? E.g. which node version, etc?

Regarding the PR, I will comment there. But generally, I don't think this is a change we want to make to the library.

**Comment by jhiner** [comment]
Closing. If you want to discuss more, feel free to reopen.
