### ISSUE TITLE
Generated access token is invalid on verifying

### ISSUE THREAD

**Issue by force-push-master** [auth0/node-jsonwebtoken#716]
Have a problem with access token verifying.
Environment:
- ubuntu 18.04
- npm 6.9.0
- node.js v10.16.3
- "jsonwebtoken": "^8.5.1"

Access and Refresh tokens generating works fine, here the code:
`generateAccessToken(userId) {
    const payload = {
      userId,
      type: tokens.access.type,
    };
    const options = {
      expiresIn: tokens.access.expiresIn,
    };

    return jwt.sign(payload, secret, options);
  },

  generateRefreshToken() {
    const payload = {
      id: uuidv4(),
      type: tokens.refresh.type,
    };
    const options = {
      expiresIn: tokens.refresh.expiresIn,
    };

    return {
      id: payload.id,
      token: jwt.sign(payload, secret, options),
    };
  },`

Here is the result from postman:
`{
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE1ODgwNzUzMDAsImV4cCI6MTU4ODA3NTQyMH0.pnbMgWMjMwoVG7SdyfPwvDEMei7g4FDF_T7T9CeO2Xs",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU0MWE5MDcwLWY3MDgtNGUzYS05ZTk5LTkwMzFlOWM3NzIxNCIsInR5cGUiOiJyZWZyZXNoIiwiaWF0IjoxNTg4MDc1MzAwLCJleHAiOjE1ODgwNzU0ODB9.07GmPNDx-GMSPaRHu2sSwjy7l9bIyXEfA2az4yvR-iQ"
}`

**Secret key is: "secret"**

When I'm trying to decode it using online service seems like everything works fine, but in my middleware I'm receiving an error: **JsonWebTokenError: invalid token**

**Here is the code of my middleware:**

`const authHeader = req.get('Authorization');
const token = authHeader.replace('Bearer', '');
const payload = jwt.verify(token, secret);`

**Comment by panva** [comment]
> **Here is the code of my middleware:**
> 
> ```js
> const authHeader = req.get('Authorization'); 
> const token = authHeader.replace('Bearer', ''); 
> const payload = jwt.verify(token, secret);
> ```

My educated guess is that this is your problem. Your header's format is likely

```
Authorization: Bearer <token>
```

So your code should be


```js
const { 0: scheme, 1: token, length } = req.get('authorization').split(' ')
if (length !== 2 || scheme.toLowerCase() !== 'bearer') {
  // throw invalid authorization header format
}
const payload = jwt.verify(token, secret);
```


Or, just this change
```diff
- const token = authHeader.replace('Bearer', '');
+ const token = authHeader.replace('Bearer ', '');
```

**Comment by force-push-master** [comment]
> > **Here is the code of my middleware:**
> > ```js
> > const authHeader = req.get('Authorization'); 
> > const token = authHeader.replace('Bearer', ''); 
> > const payload = jwt.verify(token, secret);
> > ```
> 
> My educated guess is that this is your problem. Your header's format is likely
> 
> ```
> Authorization: Bearer <token>
> ```
> 
> So your code should be
> 
> ```js
> const { 0: scheme, 1: token, length } = req.get('authorization').split(' ')
> if (length !== 2 || scheme.toLowerCase() !== 'bearer') {
>   // throw invalid authorization header format
> }
> const payload = jwt.verify(token, secret);
> ```
> 
> Or, just this change
> 
> ```diff
> - const token = authHeader.replace('Bearer', '');
> + const token = authHeader.replace('Bearer ', '');
> ```

Oh God, you absolutely right about space after "Bearer", so stupid mistake))
Spent couple hours to fix it)) Thank you very much for this great catch!

P.S. Closing this ticket.
