### ISSUE TITLE
Error while providing algorith option to jwt.sign()

### ISSUE THREAD

**Issue by pavittarx** [auth0/node-jsonwebtoken#723]
### Description
The library produces error when an algorithm option is passed to jwt.sign() method.

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent. 
   ```js
        const jwt = require("jsonwebtoken");
        const token = jwt.sign({ foo: 'bar' }, 'shhhhh', {algorithm: 'RS384'})

        console.log(token);
   ```

> - Screenshots
![image](https://user-images.githubusercontent.com/29155477/82780063-9404ed80-9e73-11ea-9b7b-74cf36c5603f.png)

### Environment
OS: Windows 10 Ver. 1809
Editor: VS Code 1.45.1

- **Version of this library used:** 8.5.1
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by panva** [comment]
`shhhhh` is not a valid RSA key to be used with [RSASSA-PKCS1-v1_5](https://tools.ietf.org/html/rfc7518#section-3.3) algorithms.

You will get similar results in other libraries.

```js
const j=require('jose')
> j.JWT.sign({ foo: 'bar' }, 'shhhhh', { algorithm: 'RS384' })
// Thrown:
// JWKKeySupport: the key does not support RS384 sign algorithm
```
