### ISSUE TITLE
Isn't the decode just a generic base64 decoder? Is there a way to use it for a facebook token? 

### ISSUE THREAD

**Issue by xtianus79** [auth0/node-jsonwebtoken#724]
### Description
I get null when I try and decode a base64 encoded string
> Provide a clear and concise description of the issue, including what you expected to happen.
I expected it to decode it.

**Comment by panva** [comment]
It's not a generic base64 decoder and it's not applicable to facebook tokens because those are not JWTs.

JWT is composed of three base64**url** encoded parts, first two need to decode to  a `JSON.parse`able string, the third one is the signature.
