### ISSUE TITLE
jwt.verify does not throw an error if token expired

### ISSUE THREAD

**Issue by farisT** [auth0/node-jsonwebtoken#726]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

`jwt.verify` does not seem to throw an error when the `Date.now()` is greater than the expiry set on the token.

### Reproduction

Sign a token and then try to verify after expiry date.

### Environment

> Please provide the following:

- **Version of this library used:** 8.5.1
- **Version of the platform or framework used, if applicable:** Node v12.13.1

**Comment by panva** [comment]
> jwt.verify does not throw an error if token expired

It does, and rest assured we have extensive tests around this core functionality.

What's most certainly at play here is either

1) the token's `exp` claim is in milliseconds, instead of seconds as it should be. e.g. `Date.now()` is `1593336930596`, then the exp claim representing such time is supposed to be `1593336930`
2) token doesn't have `exp` at all

**Comment by farisT** [comment]
@panva I appreciate the comment, the exp is indeed in miliseconds. However this was because I used the built in `expiresIn` (with the ms library). e.g.

```
    return jwt.sign(userData, process.env.JWT_SECRET, {
      expiresIn: '1h'
    });

```
returns a token with an exp of 13 numbers (aka in miliseconds instead of seconds). 

I have even tried with:

```
expiresIn: '1s'
```

No errors are thrown from jwt.verify.

**Comment by farisT** [comment]
@panva I solved the issue, I was setting the IAT with Date.now(). Thanks again for the help.
