### ISSUE TITLE
Make jsonwebtoken compatable with Deno?

### ISSUE THREAD

**Issue by viztastic** [auth0/node-jsonwebtoken#727]
Deno has hit version 1.0 and it's great that it seems to be supported on https://www.pika.dev/npm/jsonwebtoken

But when I import jsonwebtoken into my Deno project using
```javascript
import * as jwt from 'https://cdn.pika.dev/jsonwebtoken@^8.5.1';
```

I get this compile error in Deno:

```shell
Download https://cdn.pika.dev/-/stream@v0.0.2-uCzBPZtcXP3fDgEXSSSV/dist=es2019,mode=types/index.d.ts
error: Import 'https://cdn.pika.dev/-/stream@v0.0.2-uCzBPZtcXP3fDgEXSSSV/dist=es2019,mode=types/index.d.ts' failed: 404 Not Found
```

It seems like stream is somewhere in the module's dependency chain. Whilst I appreciate it's not possible to influence the dependency author, is there any way to side-step or ensure it's compatibility with Deno?

Deno's hit v1.1 with a rapidly growing community, it'd be amazing to have this module supported along with thousands of other npm modules that are doing the same.

Thanks so much!!

**Comment by panva** [comment]
We cannot make `jsonwebtoken` compatible with Deno at the moment because Deno lacks any crypto stdlib.

**Comment by ccorcos** [comment]
Looks like there's a lot more compatibility now: https://docs.deno.com/runtime/manual/node/compatibility

Problem I'm running into currently is this version check is very node.js specific: https://github.com/auth0/node-jsonwebtoken/blob/bc28861f1fa981ed9c009e29c044a19760a0b128/lib/asymmetricKeyDetailsSupported.js
