### ISSUE TITLE
Use a default of `["HS256"]` for `verify` to be in sync with default for `sign`

### ISSUE THREAD

**Issue by daniel-j-h** [auth0/node-jsonwebtoken#728]
By default `sign` uses `options.algorithm: "HS256"`.

In contrast `verify` does not use `options.algorithms: ["HS256"]` by default - but instead accepts all algorithms.

This means by default we sign with HS256 but we verify and accept all algorithms - for example also the `none` algorithm.

If we're setting a default in sign we should set the same default in verify - and keep them in sync.

Thoughts?

**Comment by panva** [comment]
source: https://github.com/auth0/node-jsonwebtoken/blob/v8.5.1/verify.js#L99-L118

> but instead accepts all algorithms

That is a false statement.

Verify's `algorithm` option default value is derived from the `secretOrPublicKey` argument value and it never defaults to accepting **all algorithms**. The accidental acceptance of `none` tokens is **also prevented**.

What lead you this expectation of accepting everything?

**Comment by daniel-j-h** [comment]
Here is an example of what I mean. Create a token with algorithm none

```js
> jwt.sign({ user: 42 }, undefined, { algorithm: 'none' });
'eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJ1c2VyIjo0MiwiaWF0IjoxNTkzNDM2NTEyfQ.'
```

The key is not needed - I set it to undefined.

By default now we can verify that token without having to explicitly allow none as an algorithm

```js
> jwt.verify('eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJ1c2VyIjo0MiwiaWF0IjoxNTkzNDM2NTEyfQ.')
{ user: 42, iat: 1593436512 }
```

and also works in this scenario when we accidentally pass undefined (or anything else false-y as an argument)

```js
> jwt.verify('eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJ1c2VyIjo0MiwiaWF0IjoxNTkzNDM2NTEyfQ.', process.env.MYKEY) // oops env var undefined
{ user: 42, iat: 1593436512 }
```

It would be best if we could make this explicit - the user should pass `algorithms: ["none"]` if the user really knows what this means and implies.

This is the case for all algorithm options. By default sign sets `HS256` as an algorithm but in verify by default we accept all algorithms e.g. we also accept a token signed with `HS512`.

**Comment by panva** [comment]
> but instead accepts all algorithms

so, this is not true.

For the `none` being explicitly required as algorithms option we already have #711 as duplicate.

For the rest, accepting HS512 when you, by default, sign with HS256 isn't that big of a deal. However, we think that in general defaulting to use HS256 even when a private key value is passed in is a problem in itself and will be changing that for next major too, so that the algorithm is derived of the `secretOrPrivateKey` argument same as for verify today.
