### ISSUE TITLE
Sign token, generate different token

### ISSUE THREAD

**Issue by Rafailong** [auth0/node-jsonwebtoken#73]
Hi there, I am using this module with a express.js application and also using express-jwt.

Well,  in the login process each time a post to the /login url a new token is generated and saved to redis. I have a validation that if a token exists it wont be set to redis. but each time a token is signed/generated it is different even when I use the same secret string and the same payload.

The code is

`
var data = {
    _id: user.id,
    username: user.nickname,
    email: user.email,
    token: jsonwebtoken.sign({ _id: user.id }, 'secret', {
      expiresInMinutes: TOKEN_EXPIRATION
    })
  };
`

But the `data.token` each post to /login route is different and it's set to redis.

Can you help me?

Regards!

**Comment by flyingsky** [comment]
sure it's different, obviously the token contains timestamp. Your logic is not correct. Your client request should contains token all the time. So on server side just check if the request has token, if not, then create one and save it; if yes verify it.

**Comment by jfromaniello** [comment]
Moreover you dont need to store it on redis. It is digital signed, so
instead of checking if its on redis you can validate its signature. Search
for HMAC

**Comment by davidwillianx** [comment]
I'm sorry to introduce another question about same topic:  So @flyingsky  said, is It not possible to compare same user because it's generated differents tokens for each request (as you said about timestamp). How am I suppose to do this feature (on my API ) test? Do you Guys have an adivice?

**Comment by jfromaniello** [comment]
You have to validate the token with the same secret you used when you signed it. If is valid it will give you the claims inside it, one of them is the `_id`. You can thrust at this point that the request is authenticated and that the user with that id did the request.
