### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by varun-av** [auth0/node-jsonwebtoken#730]
I am trying to use jsonwebtoken in angular with socketio 
`const token = jwt.sign({ foo: "bar" }, "shhhhh");`

but it gives the following error:
`Uncaught ReferenceError: global is not defined`

node: 12.16.1
angular: 9.1.11
socket.io: 2.3.0

**Comment by panva** [comment]
**We do not actually support browser environment as a runtime for this module**.

We are not providing `jsonwebtoken` for the browser platform and would recommend use of JWT modules that utilize the browser built-in [`Web Cryptography API`](https://www.w3.org/TR/WebCryptoAPI/) instead.
