### ISSUE TITLE
"TokenExpiredError: jwt expired" right after being generated.

### ISSUE THREAD

**Issue by mxthevs** [auth0/node-jsonwebtoken#731]
I'm using Typescript.

I use configuration to generate the token

```typescript
const token = jwt.sign({ id: consumer.id }, authConfig.secret, {
  expiresIn: 86400, // should expire in 1 day
});
```

And I have an Express middleware to decode the token

```typescript
interface ITokenPayload {
  iat: number;
  ext: number;
  sub: string;
}

...

const authHeader = request.headers.authorization;

if (!authHeader) {
    throw new AppError('JWT is missing ', 401);
}

const [, token] = authHeader.split(' '); // get rid of the "Bearer" part

try {
    const decoded = verify(token, authConfig.secret);

    const { sub } = decoded as ITokenPayload;

    request.user = {
      id: sub,
    };

    return next();
  } catch (error) {
    console.log(error);
    throw new AppError('Invalid JWT', 401);
 }
```

But everytime I try to decode a token I get the "TokenExpiredError: jwt expired" error, altough I generated the token in less than 3 minutes before trying to decode. Am I missing something or is this intended behaviour?

```
TokenExpiredError: jwt expired
...
{
  expiredAt: 2020-07-11T17:57:25.000Z  // 3 days before today
} 

```

**Comment by panva** [comment]
When i'm running the latest version:

```
jsonwebtoken.sign({}, 'foo', { expiresIn: 86400 })
```

Yields this [token](https://jwt.io/#debugger-io?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTQ3NTQzNjgsImV4cCI6MTU5NDg0MDc2OH0.4O3nEaCBxW6RjqeEaNORvoAryDVQbvZrnfeMnnarJYU).

```
{
  "iat": 1594754368,
  "exp": 1594840768
}
```

```
1594840768 - 1594754368 = 86400
```

So either you're not running the latest or there's something wonky going on with your machine/server's clock.
