### ISSUE TITLE
options.algorithms for verify() is not documented

### ISSUE THREAD

**Issue by kumar303** [auth0/node-jsonwebtoken#74]
It looks like you can pass in a whitelist of [algorithms](https://github.com/auth0/node-jsonwebtoken/blob/master/index.js#L110) into the [verify()](https://github.com/auth0/node-jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback) function but this is not documented.

**Comment by pose** [comment]
Hi @kumar303,

This has been fixed and you can find it in the repository README.md file.

Thanks in advance,
