### ISSUE TITLE
Strange interference with Mongoose

### ISSUE THREAD

**Issue by CodeWithOz** [auth0/node-jsonwebtoken#740]
### Description

> Provide a clear and concise description of the issue, including what you expected to happen.

I'm using this library in a node server that uses mongoose, and I have a model that has a nested property which is also another model. Like this:

```
// nested.js
var NestedPropDef = {
  someProp: { type: String, default: '' },
};
var schema = new Schema(NestedPropDef, { minimize: false });
schema.statics = {
  getInstance() {
    var nestedObject = new NestedProp();
    nestedObject.someProp = 'something';
    console.log('[first log] value of nestedObject:', nestedObject);
    return nestedObject;
  },
});
var NestedProp = mongoose.model('NestedProp', schema);

exports.NestedPropDef = NestedPropDef;
exports.NestedProp = NestedProp;
```
```
// parent-file.js
var NestedPropDef = require('./nested').NestedPropDef;
var NestedProp = require('./nested').NestedProp;

var schema = new Schema({
  otherProp: { type: String, default: '' },
  nestedProp: NestedPropDef,
});

schema.methods.updateNestedProp = function (data, callback) {
  this.nestedProp = NestedProp.getInstance();
  console.log('[second log] value of nestedProp:', this.nestedProp);
  this.otherProp: data.otherProp;
  console.log('[third log] value of this:', this);
  this.save(callback);
});
var Parent = mongoose.model('Parent', schema);
module.exports = Parent;
```

Until I installed this library, mongoose was handling my nested model correctly (i.e. the object printed in `[first log]` was identical to the object printed in `[second log]`). However, after installing this library, I started seeing a bug where the object printed in `[second log]` would be an empty object literal (`{}`) even though `[first log]` still printed the newly created object. I'm not sure why the problem is introduced by merely installing this library, I use the library in a separate route that's not related to the routes that contain the snippet above.

**Expected outcome**: installing this library shouldn't change the behavior of my Mongoose models.

### Reproduction

I haven't been able to reproduce this outside my project.

### Environment

- **Version of this library used:** 8.5.1
- **Version of the platform or framework used, if applicable:** Express.js v4.17.1
- **Other relevant versions (language, server software, OS, browser):** NodeJS 10 and 12
- **Other modules/plugins/libraries that might be involved:** Mongoose 5.9.21

**Comment by panva** [comment]
Can you post your package-lock.json (or yarn.lock) before and after installing `jsonwebtoken`?

**Comment by CodeWithOz** [comment]
The server is run in Docker, any ideas on how to get the package-lock file from inside the container? It seems I should be using Docker volumes to do that but I'm not able to get a working volume when I run the server locally.

**Comment by panva** [comment]
> The server is run in Docker, any ideas on how to get the package-lock file from inside the container? It seems I should be using Docker volumes to do that but I'm not able to get a working volume when I run the server locally.

That's not really a question you can get assistance for here.

**Comment by CodeWithOz** [comment]
@panva please have a look at the files:
- before installing jsonwebtoken: [this file](https://gist.github.com/CodeWithOz/f0a3d53f273857b92deb364c72774758)
- after installing jsonwebtoken: [this file](https://gist.github.com/CodeWithOz/d71565cdd9895ae816fde9dd803c5579)

Thank you.

**Comment by panva** [comment]
`jsonwebtoken` is in both locks, and the exact same version. From diffing this i don't see you actually installed jsonwebtoken, i can see that plenty of other libs got updated so it's more likely this isn't related to jsonwebtoken at all.

**Comment by CodeWithOz** [comment]
Yes I installed jsonwebtoken to use it directly, but previously it was a dependency of Twilio. Yeah I'm taking a look at the other changes.

**Comment by CodeWithOz** [comment]
Turns out the problem was mongoose itself, didn't catch it because of cache issues. Thanks.
