### ISSUE TITLE
Property 'expiredAt' does not exist on type 'VerifyErrors'.

### ISSUE THREAD

**Issue by Maligosus** [auth0/node-jsonwebtoken#747]
Property 'expiredAt' does not exist on type 'VerifyErrors'.
Property 'expiredAt' does not exist on type 'NotBeforeError'.
err.expiredAt

`
jwt.verify(token,this.signature,(err:TokenExpiredError|
                                                       NotBeforeError|
                                                       JsonWebTokenError|null,
                                                       decode:any|undefined)=>{
            if (err){
                callback(err,{
                    status: HttpStatus.FORBIDDEN,
                    connected:true,
                    message: "TokenIsExpired",
                    expiredAt: err.expiredAt
                })
            }
            else
                callback(null,decode);
        });
`

**Comment by panva** [comment]
Hi @Maligosus,

the [types you're using](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jsonwebtoken) are community provided and maintained, we as Auth0 do not maintain those. You can see the list of owners of those types in the [DT repo](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jsonwebtoken/index.d.ts).
