### ISSUE TITLE
Decimal timestamps cause JsonWebTokenError on signature verification

### ISSUE THREAD

**Issue by TKlie** [auth0/node-jsonwebtoken#764]
### Description

The token verification fails, even though the token is a valid JWT.

### Reproduction

To reproduce, provide any token with decimal timestamps. This will be decoded to something like:

```json
{
    "aud": "14",
    "jti": "e1fd9735bb925432588c61bfac9ad1edd7237d11dbc008506f29329bf7260ff48106142ac09227a5",
    "iat": "1613388071.325008",
    "nbf": "1613388071.325013",
    "exp": "1644924071.299660",
    "sub": "5",
    "scopes": []
}
```

Trying to verify this same token's signature against the public key causes following error:

```
JsonWebTokenError {
    name: 'JsonWebTokenError',
    message: 'invalid nbf value'
}
```

After some initial debugging, this error seems to be caused by this package type-checking the `iat`, `nbf` and `exp` fields for being of type `number`, but the decoding process returning decimal timestamps as `string`.

### Environment

- **Version of this library used:** 8.5.1
- **Version of the platform or framework used, if applicable:** Ubuntu 20.04
- **Other relevant versions (language, server software, OS, browser):** Node 12.19.0
- **Other modules/plugins/libraries that might be involved:** Token issued by Laravel package Passport

**Comment by panva** [comment]
Hello @TKlie the type check for a number is correct.

```js
> JSON.stringify({ iat: 127.32 })
'{"iat":127.32}'
> JSON.parse(JSON.stringify({ iat: 127.32 }))
{ iat: 127.32 }
```

These are IANA registered claims with a type defined by the specification.

**Comment by TKlie** [comment]
Thanks for the quick reply @panva .

So, you're saying that - rather than this package doing something like `parseFloat` to catch this - the encoding process is a fault here, correct?

**Comment by panva** [comment]
Yes. Whomever produces that JWT produces it incorrectly. It's meant to be a JSON number type rather than a string.
