### ISSUE TITLE
Problem encoding UTF-8 data

### ISSUE THREAD

**Issue by hiagodotme** [auth0/node-jsonwebtoken#766]
### Description

> I'm having trouble encoding UTF-8 data.

### Reproduction
```

// encoding (backend nodejs)

console.log('jwt >> ', jwt.sign({name: 'Ação'}, 'secret') );

// decoding (frontend)
var token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQcOnw6NvIiwiaWF0IjoxNjEzNDg5Njg4fQ.nDYYaGZo0dFql7954SN8EVR0BLVin8jbtJWlaLjr4qI';

console.log(atob(token.split('.')[1]));
```

### Environment

> Please provide the following:

- **Version of this library used:** 8.3.0
- **Other relevant versions (language, server software, OS, browser):** Ubuntu 20.04 LTS

**Comment by panva** [comment]
The data is getting encoded correctly. It's the way you decode it that [doesn't handle utf-8](https://stackoverflow.com/questions/30106476/using-javascripts-atob-to-decode-base64-doesnt-properly-decode-utf-8-strings).


```js
decodeURIComponent(atob(token.split('.')[1]).split('').map(function(c) {
  return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
}).join(''))
```
