### ISSUE TITLE
[security] Update node-jws to 3.0.0

### ISSUE THREAD

**Issue by MarkHerhold** [auth0/node-jsonwebtoken#77]
[node-jws](https://github.com/brianloveswords/node-jws) is now at version 3.0.0. due to a security fix. The [change log for 3.0.0 is here](https://github.com/brianloveswords/node-jws/blob/master/CHANGELOG.md).

> **BREAKING**: `jwt.verify` now requires an `algorithm` parameter, and
  `jws.createVerify` requires an `algorithm` option. The `"alg"` field
  signature headers is ignored. This mitigates a critical security flaw
  in the library which would allow an attacker to generate signatures with
  arbitrary contents that would be accepted by `jwt.verify`. See
  https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/
  for details.

**Comment by dschenkelman** [comment]
Closing as duplicate of https://github.com/auth0/node-jsonwebtoken/issues/76

**Comment by dschenkelman** [comment]
Thanks for taking the time to report :smile:
