### ISSUE TITLE
Token Does Not Expire At All

### ISSUE THREAD

**Issue by sapinder-pal** [auth0/node-jsonwebtoken#771]
### Description
I'm trying to implement my own jwt authentication with access-refresh tokens. But the access_token doesn't seem to expire at all. I'm setting the `expiresIn` property to 5 seconds when signing the token for experimental purposes.  

### Reproduction

- How I'm signing the token
```
access_token = jwt.sign(payload, PRIVATE_KEY, {
  expiresIn: 5,       // I've also tried the string value - '5000'
  algorithm: 'RS256'
 });
```
- How I'm verifying the token
```
router.get('/', (req, res) => {
	const authorizationCookie = JSON.parse(req.cookies.Authorization);

	const accessToken = authorizationCookie['access_token'].split(' ')[1];

	jwt.verify(accessToken, PUBLIC_KEY,
		(err, decoded) => {
			if (err) return sendError(res, 401, err);
			
			res.sendFile(path.resolve('public', 'html', 'index.html'));
		});
	
})
```
According to the docs, the callback function is supposed to detect the expiry of the token, and throw an error, which it doesn't seem to be doing here.

### Steps I Have Tried To Validate The Expiry Time

- When I take the generated access_token and decode it on [jwt.io](https://jwt.io/) using my public key, this is what I see in the payload-
```
{
  "iat": 1614827161901,
  "username": "sapinder",
  "exp": 1614827161906    // Notice the difference between iat and exp is exactly 5 seconds as defined during the signing process
}
```
- I have tried `console.log()` to validate the expiry of jwt. Despite the expiry time been passed, the callback still doesn't throw any error.
```
(err, decoded) => {
	if (err) return sendError(res, 401, err);
	
        // it returns true, meaning the token has been expired
        console.log(decoded.exp < Date.now());
		
	res.sendFile(path.resolve('public', 'html', 'index.html'));
});
```

### Environment

- **jsonwebtoken: ^8.5.1**
- **express: ^4.17.1**
- **cookie-parser: ^1.4.5**

**Comment by book12085** [comment]
add exp to sign:
eg:
`
jwt = sign(userName: 'Aaron', exp: (Date.now() / 1000 + 5), .........)
`

it works

**Comment by sapinder-pal** [comment]
Well I'm able to make it work by adding `exp` to the payload instead since the day I opened this issue. It's just that `expiresIn` property doesn't seem to work.

**Comment by ManuC84** [comment]
Yeah it doesn't work for me either

**Comment by 13thThief** [comment]
Can confirm this.

**Comment by 3FanYu** [comment]
does not work for me too
my setup:
```
const payload = {
    sub: _id,
    iat: Date.now(),
  };
  const signedToken = jsonwebtoken.sign(payload, PRIV_KEY, {
    expiresIn: '20s',
    algorithm: "RS256",
  });
```

and my token never expires

**Comment by 3FanYu** [comment]
i think i've found my problem!
i was manually setting the "iat" as Date.now() in the payload
but apparently the token will generate iat property itself
I commented that out and it works fine.

**Comment by sapinder-pal** [comment]
yes it worked! 😃

**Comment by Davi-zzz** [comment]
> i think i've found my problem!
> i was manually setting the "iat" as Date.now() in the payload
> but apparently the token will generate iat property itself
> I commented that out and it works fine.

ohh guy, ty soo much!

**Comment by medic-code** [comment]
Can I ask why does manually setting 'iat' as Date.now() in the payload invalidate the expiration time of the token ?

**Comment by joffinjoy** [comment]
> i think i've found my problem! i was manually setting the "iat" as Date.now() in the payload but apparently the token will generate iat property itself I commented that out and it works fine.

Been driving me crazy. Thanks.
