### ISSUE TITLE
Expire a JWT

### ISSUE THREAD

**Issue by n1rjal** [auth0/node-jsonwebtoken#777]
Suppose a user of my system, clicks **logout of all devices**

Then I would want to expire / invalid all the access/refresh tokens which was signed before that time. 

Do we have some feature for doing so

How can I implement it.

**Comment by alikamrani** [comment]
> Suppose a user of my system, clicks **logout of all devices**
> 
> Then I would want to expire / invalid all the access/refresh tokens which was signed before that time.
> 
> Do we have some feature for doing so
> 
> How can I implement it.

hi . It is my question  too . could anyone help ?

**Comment by dhensby** [comment]
There is no "standard" way to revoke a JWT. JWTs are intended to be de-centralised and self-verifiable; this means there's no need to contact a central authentication service to verify a JWT, an application consuming a JWT can verify the token and trust it.

JWTs are useful for authentication services that need to authenticate a large number of users or users in a distributed wat where it's either not practical to contact a central authentication service or doing so would add undue overhead to the authentication process. There's essentially a speed vs security trade-off.

If your systems don't need to be highly scalable, then JWTs are probably not appropriate authentication tokens, instead you should consider using some other token which would just be sufficiently "random" that it can't be guessed and these tokens would then be verified by making an API call to an authentication service.

Having said that, it's not impossible to revoke a JWT, it just goes against the main advantage of JWTs and I'd argue removes any reason to use them. To be able to revoke JWTs, your authentication service (the one issuing JWTs) would need to keep a log of all JWTs (or their JTIs) that were issued, when they'd expire, and whether they've been revoked. Then any service that uses your authentication service to provide authorisation control would make a request to your authentication service to check the validity of the JWT. If a token is missing, expired, or revoked then an error response would be returned and thus authorisation would be denied. But, to reiterate, if you do this, there is no real point in using JWTs at all. The data that would be stored in the JWT could be returned in the API call that checks token validity and the large JWT string could be replaced with a much more concise token instead,

**Comment by hanchiang** [comment]
You can implement this feature by storing the tokens in a blacklist, say in redis, which will expire on the expiration time `exp`.

As noted, such a feature will incur a performance penalty as every service that a request flows through will have to verify whether the token is revoked.

On the positive side, the storage requirement should not be large, since the tokens in the blacklist will be removed after its expiry.

**Comment by dhensby** [comment]
You can't blacklist tokens without knowing they were issued on the first place and to which subject (if you wanted to expire all tokens for a user on logout). So there is more storage required than just the blacklist. Making the use of JWTs unnecessary.

**Comment by hanchiang** [comment]
Blacklisting requires the storage of state in a data store. It seems like the same is true for server-side sessions.
Is there anything that I missed here?

Also, the impact of the performance penalty would be largely dependent on the scale of the traffic that the system is serving. In security-critical applications, the performance hit might be a worthy tradeoff.
