### ISSUE TITLE
JWS 2.0.0 security deprecation

### ISSUE THREAD

**Issue by designfrontier** [auth0/node-jsonwebtoken#79]
`npm WARN deprecated jws@2.0.0: Security update: Versions below 3.0.0 are deprecated.`

**Comment by dschenkelman** [comment]
We have just merged: https://github.com/auth0/node-jsonwebtoken/commit/634b8ed0ff5267dc25da5c808634208af109824e

We will release a new major version shortly.

**Comment by pose** [comment]
@designfrontier It should be fixed on `jsonwebtoken@5.0.0`. Feel free to re-open if you are getting the same error. Thanks!
