### ISSUE TITLE
Library is not able to decode token

### ISSUE THREAD

**Issue by AhsanAtGol** [auth0/node-jsonwebtoken#798]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

> Provide a clear and concise description of the issue, including what you expected to happen.

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment

> Please provide the following:

- **Version of this library used:**
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by AhsanAtGol** [comment]
Library fails to decode on below token:
`edyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6InN1cHBvcnRAYWxpdmU1LmNvbSIsInNjcmVlbl9uYW1lIjoiRHVzdGluIiwiaXNzIjoiYWxpdmU1X2FwaSIsIm9yZ19uYW1lIjoiYWxpdmU1ZGVtbyIsImFsaXZlX3BheSI6dHJ1ZSwidXNlcl9pZCI6ImI1N2I0MTNkLTY1YmUtNDRmYy1iZWU4LWJlOTQxOGU3OGVhYyIsInVzZXJfcm9sZSI6Im1hc3RlciIsInR5cGUiOiJ1c2VyIiwidmVyaWZpZWQiOnRydWUsImNoYXJnZWJlZV9wbGFuIjoiMTAwayIsIm1heF9jcmVkaXRzIjoyMDIwMDAwLCJwcm9maWxlX3VybCI6Imh0dHBzOi8vYWxpdmU1Y2RuLnMzLmFtYXpvbmF3cy5jb20vaW1hZ2VzL3VwbG9hZHMvYWxpdmU1bWUtMTYyMDcwMTk2MTk4OC1kdXN0aW4uanBnIiwic3Vic2NyaXB0aW9uX2VuZF9kYXRlIjoiIiwiY3JlZGl0c191c2VkIjoyMjU0OCwic3Vic2NyaXB0aW9uX2lkIjoiIiwic3Vic2NyaXB0aW9uX3N0YXJ0X2RhdGUiOiIiLCJwYXltZW50X21ldGhvZCI6ImNoYXJnZWJlZSIsImFsbG93X2J1bGtzbXMiOiJ0cnVlIiwiY2hhcmdlYmVlX3BsYW5fbGFiZWwiOiI2LDUwMCBUZXh0IE1lc3NhZ2VzIiwicGFydG5lcl9uYW1lIjoiYWxpdmU1IiwicGFydG5lcl9jb25maWciOiIiLCJmZWF0dXJlcyI6eyJQSVBMIjp0cnVlLCJTTVMiOnRydWV9LCJ2ZXJzaW9uXzYiOnRydWUsIm1sX21vZGVsIjoiYWxpdmUiLCJtZXJnZWRfbWVzc2FnaW5nIjoiIiwiY2hhdF9zaGFyaW5nIjoiZGlzYWJsZWQiLCJtYXhfY2hhdHMiOiIxMDAwMDAiLCJib3RfdXNlcl9pZCI6IjEzZWQyMWJhLTY5MTItNDU1NC1iMzRmLTgzMWZlZDExMTE0YyIsInBsYW5fcHJpY2UiOjAsInBvbGljeV9pZCI6IjdkZjFjNTIzLTMxMTUtNDdhZS04MmQ1LTJhYTEzZjRlM2QzZSIsInBvbGljeSI6eyJjcmVhdGVkX2F0IjoxNjI1MDQwNDI4MDA3LCJwb2xpY3lfbmFtZSI6IkFsbCBBcHBzIiwicG9saWN5X2ZlYXR1cmVzIjpbIlNNUyIsIlBJUEwiLCJUQVNLUyIsIkNhbXBhaWducyIsIkFsaXZlVmlkZW8iLCJCT1RTIiwiRmFjZWJvb2siLCJBbGl2ZVBheSIsImFsaXZlQ2hhdCIsIkNybUludGVncmF0aW9ucyJdLCJwb2xpY3lfaWQiOiI3ZGYxYzUyMy0zMTE1LTQ3YWUtODJkNS0yYWExM2Y0ZTNkM2UifSwicGlwbF9tYXhfY3JlZGl0cyI6NjAwLCJwaXBsX2NyZWRpdHNfdXNlZCI6MCwic2ZfYWNjZXNzX3Rva2VuIjowLCJpYXQiOjE2MzgzNzg1NDN9.uxNKMguTwtz7KMIx61yarcWcuOcpYatDvyiCuimOzFU`

**Comment by panva** [comment]
That is expected given the JWS Protected Header is not correctly base64url encoded JSON string.
