### ISSUE TITLE
jwt is always empty object

### ISSUE THREAD

**Issue by webcat12345** [auth0/node-jsonwebtoken#802]
### Description

I am using `jsonwebtoken` in my nx based meteor application and I imported library to use `sign` function. But jwt is always empty object because of that, I can't use the `jwt.sign` function.

### Reproduction

```
import jwt from 'jsonwebtoken';

console.log(jwt);

I20220109-22:22:11.551(-8)? {}
```
### Environment

- `"jsonwebtoken": "^8.5.1",`
- Meteor.js

**Comment by markxoe** [comment]
Have you tried `import * as jwt from "jsonwebtoken"`?

**Comment by webcat12345** [comment]
This was something related with Nx project configuration. No issue for this library. Sorry.
