### ISSUE TITLE
Decode documentation?

### ISSUE THREAD

**Issue by sarink** [auth0/node-jsonwebtoken#806]
Are there any docs explaining how `jwt.decode` works? What are the `options` and what do they do?

It's easy enough to read [the source](https://github.com/auth0/node-jsonwebtoken/blob/master/decode.js), but some official documentation would be nice.

**Comment by panva** [comment]
https://github.com/auth0/node-jsonwebtoken#user-content-jwtdecodetoken--options

**Comment by jketcham** [comment]
(The link should be: https://github.com/auth0/node-jsonwebtoken#jwtdecodetoken--options)
