### ISSUE TITLE
Upgrading to react-scripts 5.0.0.0 causes major issues 

### ISSUE THREAD

**Issue by Faziki** [auth0/node-jsonwebtoken#823]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

> Provide a clear and concise description of the issue, including what you expected to happen.

I was trying to upgrade my `react-scripts` to version `5.0.0` but when doing so I got a bunch of errors regarding `JWT`
it says that it requires the following packages:

1: `crypto-browserify`
2. `crypto`
3. `stream`
4. `stream-browserify`

and adding these packages with configuring webpack is just a pain and doesn't resolve the issue.

and removing `JWT` completely gets rid of all of the errors

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.

Its a consistent issue, create a new `create-react-app` and then try to install JWT and see what happens, or even go to a project that has version `4.0.3` of `react-scripts` installed and up the version to `5.0.0` and it will reproduce the exact same thing

>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
```
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }
assets by status 6.92 KiB [cached] 1 asset
assets by chunk 16.4 MiB (name: main)
  asset static/js/bundle.js 16.4 MiB [emitted] (name: main) 1 related asset
  asset main.51799c896d37526212c7.hot-update.js 357 bytes [emitted] [immutable] [hmr] (name: main) 1 related asset
assets by path *.json 611 bytes
  asset asset-manifest.json 583 bytes [emitted]
  asset main.51799c896d37526212c7.hot-update.json 28 bytes [emitted] [immutable] [hmr]
asset index.html 1.94 KiB [emitted]
Entrypoint main 16.4 MiB (14.7 MiB) = static/js/bundle.js 16.4 MiB main.51799c896d37526212c7.hot-update.js 357 bytes 2 auxiliary assets
cached modules 31 MiB [cached] 1357 modules
runtime modules 32.9 KiB 18 modules
```
```
ERROR in ./node_modules/jwa/index.js 5:13-30
Module not found: Error: Can't resolve 'crypto' in 'C:\dummy\my-app\node_modules\jwa'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }
 @ ./node_modules/jws/lib/sign-stream.js 6:10-24
 @ ./node_modules/jws/index.js 2:17-45
 @ ./node_modules/jsonwebtoken/decode.js 1:10-24
 @ ./node_modules/jsonwebtoken/index.js 2:10-29
 @ ./src/utils/api.js 10:0-36 23:9-13
 @ ./src/common/AppWrapper.jsx 12:0-44 16:15-27
 @ ./src/index.jsx 6:0-45 10:33-43
```
```
ERROR in ./node_modules/jws/lib/data-stream.js 4:13-30
Module not found: Error: Can't resolve 'stream' in 'C:\dummy\my-app\node_modules\jws\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
        - install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "stream": false }
 @ ./node_modules/jws/lib/sign-stream.js 4:17-41
 @ ./node_modules/jws/index.js 2:17-45
 @ ./node_modules/jsonwebtoken/decode.js 1:10-24
 @ ./node_modules/jsonwebtoken/index.js 2:10-29
 @ ./src/utils/api.js 10:0-36 23:9-13
 @ ./src/common/AppWrapper.jsx 12:0-44 16:15-27
 @ ./src/index.jsx 6:0-45 10:33-43
 ```

> - Application settings (redact/remove sensitive information)
same as a normal `create-react-app`
> - Screenshots

### Environment

> Please provide the following:

- **Version of this library used:**
` "jsonwebtoken": "^8.5.1",`

- **Version of the platform or framework used, if applicable:**
`react 17.0.2`
- **Other relevant versions (language, server software, OS, browser):**

`English`
`None`
`Windows 10`
`Firefox`
- **Other modules/plugins/libraries that might be involved:**

`Webpack 5.0`

**Comment by panva** [comment]
`jsonwebtoken` is a JWT implementation for Node.js. `jsonwebtoken` never officially catered to runtimes other than Node.js.

What you've been depending on up until now is webpack's automatic use of node module polyfills of questionable support, quality, security, and feature-parity with node's own modules. Those are not automatically applied in new versions of webpack, that is now used by the `create-react-app` resulting setup.

https://jwt.io/libraries?language=JavaScript lists a number of generic javascript jwt libraries that you could use for runtimes other than Node.js instead.

**Comment by lukaselmer** [comment]
> `jsonwebtoken` is a JWT implementation for Node.js. `jsonwebtoken` never officially catered to runtimes other than Node.js.
> 
> What you've been depending on up until now is webpack's automatic use of node module polyfills of questionable support, quality, security, and feature-parity with node's own modules. Those are not automatically applied in new versions of webpack, that is now used by the `create-react-app` resulting setup.
> 
> https://jwt.io/libraries?language=JavaScript lists a number of generic javascript jwt libraries that you could use for runtimes other than Node.js instead.

It's a pity that this isn't officially supported, because the code we used was working 🤔 as a result, we switched to a different library which supports nodejs as well as the browser. I would appreciate it if the browser could also be officially supported, at least for a subset of the functionality.
