### ISSUE TITLE
error in jwt.verify

### ISSUE THREAD

**Issue by shea256** [auth0/node-jsonwebtoken#83]
Hi there,

I'm working with jwt.verify and I'm getting an "invalid algorithm" error.

`Uncaught JsonWebTokenError {name: "JsonWebTokenError", message: "invalid algorithm"}`

*Note: I tried switching up my PEM encoding from PKCS8 to traditional OpenSSL, but then I get an "invalid signature" error instead, which leads me to believe that PKCS8 is required.*

Here is my code:

```python
var jwt = require('jsonwebtoken');
var payload = {foo: 'bar'};
var rsa_token = jwt.sign(payload, private_pem, {algorithms: 'RS256'});
jwt.verify(rsa_token, public_pem);
```

Is RS256 properly supported?

Also please note that I'm testing this in the browser with browserify.

Any guidance on this would be much appreciated. Thanks!

**Comment by jfromaniello** [comment]
You are doing it wrong, on the sign part. It is `algorithm`singular

Please check the documentation.

**Comment by shea256** [comment]
OK thank you. It now works for RSA PEMs with PKCS8 encoding, but I still get "invalid signature" when I use traditional OpenSSL encoding.

**Comment by bnolan** [comment]
I had this problem using `node-rsa` and the default `exportKey('private')`. You should note that the PEMs must be in PKCS8 encoding, otherwise you will get intermittent errors with randomly generated keys.

**Comment by jfromaniello** [comment]
@shea256 please open another issue with an example and I will have a look

**Comment by mike-aungsan** [comment]
@jfromaniello 
@shea256 

I am having the same issue. 
I sign payload with public key either in "pkcs1-private-pem" or "pkcs8" format.

Then verify with private key either in "pkcs8-public-pem" or "pkcs1-private-der"
None of these work.

@shea256 What encryptionScheme and signingScheme do you use in RSA key generation?

{
  encryptionScheme: {
    scheme: 'pkcs1_oaep',
    hash: 'sha512'
  },
  signingScheme: 'pss-sha512'
}
