### ISSUE TITLE
Problems with utf8 payload

### ISSUE THREAD

**Issue by antonioreyna** [auth0/node-jsonwebtoken#84]
hello im sending an utf8 payload for example containing the letter ```é```but when angular decodes it i get ```Ã©``` why is that? just with the token all the other responses done directly from nodejs i get the correct chars

**Comment by jfromaniello** [comment]
what are you using to decode in the client-side?

Try latest version of:
https://github.com/auth0/jwt-decode

**Comment by antonioreyna** [comment]
hello, i just figured out, i installed another package to decode utf8 base64 and now everything is ok thanks

**Comment by antonioreyna** [comment]
ill try the latest anyway thank you
