### ISSUE TITLE
Documentation uses payload when it should be claim

### ISSUE THREAD

**Issue by samholmes** [auth0/node-jsonwebtoken#85]
The JWT spec calls this _payload_ a _claim_. You're documentation should use this convention to not confuse the subject.

**Comment by jonrh** [comment]
Although I find *payload* to be a more descriptive word I agree that *claim* should be used for consistency with the spec. Two possible ways to address this:

* Refactor *payload* to *claim* in code and documentation.
* Add to the top of repository README.md: 
	* *payload is used interchangeabliy with claim*

**Comment by panva** [comment]
The `payload` would be the JWS payload, in JWT case a JSON formatted string with attributes being individual `claims`. I don't think the documentation needs updating. If anything than `payload` could be `claims`, but that becomes too darn hard to keep track of when reading - `claim(s)` everywhere, whats what?
