### ISSUE TITLE
can't decode token with empty payload

### ISSUE THREAD

**Issue by dopewevmond** [auth0/node-jsonwebtoken#854]
### Description

> i am trying to decode the header of a token (without verifying it) using the decode() method. it returns undefined for both the header and the payload when the token being decoded has an empty payload

### Reproduction
```
const verifyjwt = (token: string): void => {
  const decoded = jwt.decode(token, { json: true, complete: true })
  console.log(decoded?.header) // logs undefined when token has empty payload
  console.log(decoded?.payload) // logs undefined when token has empty payload
}
```
token with empty payload to reproduce the bug
`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9..wXswGZRZAob1kL_sWBaPDvE_Lq09TIxmxs1luyKYmd4`

### Environment

> jsonwebtoken: 8.5.1
node v16.18.0

**Comment by RenautMestdagh** [comment]
I'm experiencing the same problem.
Error message is "invalid token".
Were you able to solve this?

**Comment by dopewevmond** [comment]
yeah, resolved it by adding some data in the payload
