### ISSUE TITLE
Misplaced documentation line in README.md

### ISSUE THREAD

**Issue by samholmes** [auth0/node-jsonwebtoken#86]
"Setting ignoreExpiration to true will prevent expired tokens from generating an error." in the README.md file is placed under https://github.com/auth0/node-jsonwebtoken#jwtsignpayload-secretorprivatekey-options when it should be under https://github.com/auth0/node-jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback

**Comment by jfromaniello** [comment]
Good catch, thanks a bunch!
