### ISSUE TITLE
[Bug] Changes between `8.5.1` & `9.0.0` introduce a `circular dependency`

### ISSUE THREAD

**Issue by o-alexandrov** [auth0/node-jsonwebtoken#865]
### Description

Changes between `8.5.1` & `9.0.0` introduce a `circular dependency`

### Reproduction

Bundle w/ `rollup` `8.5.1` (previous version) & then `9.0.0`.
You'd see no issues w/ `8.5.1`.
And w/ `9.0.0` you'd see the following in your console:
```sh
Circular dependency:
../../node_modules/jsonwebtoken/node_modules/semver/classes/comparator.js ->
../../node_modules/jsonwebtoken/node_modules/semver/classes/range.js ->
../../node_modules/jsonwebtoken/node_modules/semver/classes/comparator.js
```

**Comment by rxuxr** [comment]
Hi,
I believe I am looking at a similar issue.
After I bumped from 8.5.1 to 9.0.0 in one of our packages bundled by Rollup, when importing from this package in our react app, I am seeing the following errors:
```TypeError: Cannot destructure property 'ANY' of 'Comparator$1' as it is undefined.```

**Comment by ricardasjak** [comment]
Same issue using Vite (Rollup under the hood), only with prod build.

**Comment by david-renaud-okta** [comment]
This is a bug in rollup and/or semver  See - https://github.com/npm/node-semver/issues/381

**Comment by kristoffer-hiddengem** [comment]
Taking a (non-dev-)dependency on a buggy package could be considered a bug 😅 Maybe we can check Node support in another way? I'm not entirely sure I understand the 9.0.0 PR, but it seems that on older versions of Node, the checks based on `asymmetricKeyDetails` is simply skipped, if the semver of process version matches something. How about just skipping the checks if `asymmetricKeyDetails` is not present?
