### ISSUE TITLE
"decode" function is not used for v9 in strict mode

### ISSUE THREAD

**Issue by kento-machida** [auth0/node-jsonwebtoken#866]
### Description
We upgraded from v8.5.1 to v9.0.0, but happend TypeError that "decode" is not a function in strict mode.
I think this issue cause is below change, define non-enum in this function.
https://github.com/auth0/node-jsonwebtoken/pull/741

This change point is not included in Migration note, so we did not notice.
I'm sure that many other users also have used this function.
How about mentioning this matter in the Migration note and Readme?

### Reproductiona
In strict mode, use "decode" function.

### Environment

jsonwebtoken : ^9.0.0

node : v16.16.0 (use strict mode)
Typescript : ^4.7.4
OS : windows10

**Comment by aperona-hai** [comment]
We are also hitting this

**Comment by arnoBruynseels** [comment]
We are hitting the following issue when we test and mock our code with jest.

```
import jwt from 'jsonwebtoken';

jest.spyOn(jwt, 'decode').mockImplementation(() => 'some token');
```

Results into the following error:

> Cannot assign to read only property 'decode' of object '[object Object]'

Which has the same root problem, meaning that the **decode** function now is read only due to it being defined in the `defineProperty` function which results it in being non-writable beacause the `writable` property value defaults to **false** of the  `defineProperty` function.
(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty)

You can find the source code here:

https://github.com/auth0/node-jsonwebtoken/blob/e1fa9dcc12054a8681db4e6373da1b30cf7016e3/index.js

Proporsed solution:

Added `writable: true` in the definition

**Comment by nippysaurus** [comment]
It looks like `decode` might have been removed quite a while ago.
https://github.com/auth0/node-jsonwebtoken/pull/741

**Comment by psyvision** [comment]
> It looks like `decode` might have been removed quite a while ago. #741

It's still there -> https://github.com/auth0/node-jsonwebtoken/blob/v9.0.0/decode.js

#741 was never merged.

We've encountered this too when upgrading to mitigate GHSA-8cf7-32gw-wr33 as we use `sinon` to stub it for testing.

**Comment by mark-strudwick** [comment]
We are hitting this same issue, even though the docs still mention that `decode` is a valid function.
https://github.com/auth0/node-jsonwebtoken#jwtdecodetoken--options

**Comment by blakejoy** [comment]
Also running into this issue using jest. There is an open vulnerability that v9 fixes.

**Comment by jirihofman** [comment]
> > It looks like `decode` might have been removed quite a while ago. #741
> 
> It's still there -> https://github.com/auth0/node-jsonwebtoken/blob/v9.0.0/decode.js
> 
> #741 was never merged.
> 
> We've encountered this too when upgrading to mitigate [GHSA-8cf7-32gw-wr33](https://github.com/advisories/GHSA-8cf7-32gw-wr33) as we use `sinon` to stub it for testing.

It seems this is the root cause: https://github.com/auth0/node-jsonwebtoken/commit/15a1bc449ab529d540eb9c2be4e093f9f5b0278d. We are also struggling with `sinon` stubbing after upgrade from 8.5.1 to 9.0.0.

```js
const jwt = require('jsonwebtoken');
sinon.stub(jwt, 'decode')
TypeError: Cannot redefine property: decode
```

**Comment by robertfines** [comment]
I am running into the same issue when trying to stub decode using sinon after upgrading from 8.5.1 to v9.0.0 to resolve the same vulnerability.
Versions prior to 9.0.0 worked fine doing:

```import * as faker from 'faker';
import jwt from 'jsonwebtoken';
import * as sinon from 'sinon';


chai.use(chaiAsPromised);

describe('getPrincipalIdentifier', () => {
  let sandbox: sinon.SinonSandbox;
  let decode: sinon.SinonStub;
  let token: string;
  
  beforeEach(() => {
    sandbox = sinon.createSandbox();
    decode = sandbox.stub(jwt, 'decode');
    token = faker.random.uuid();
  });

  afterEach(() => {
    sandbox.restore();
  });

  it(`should return the principal id from the decoded token`, async () => {
    const pid = faker.random.uuid();
    decode.returns({ payload: { principal_identifier: pid } });
    return chai.expect(getPrincipalIdentifier(token)).to.be.equal(pid);
  });
...
});
```

But I now receive:
```TypeError: Cannot redefine property: decode```

**Comment by frankyhun** [comment]
Instead of 


```
jest.spyOn(jwt, 'decode').mockImplementation(() => 'some token');
```

use

```
Object.defineProperty(jwt, 'decode', {
  writeable: true,  // necessary to for jest.restoreAllMocks()
  value: () => {return 'some token';},
});
```

**Comment by Doyler123** [comment]
Using `Object. defineProperty ` causes an error

`Object.defineProperty(jwt, 'decode', {
            writeable: true,  // necessary to for jest.restoreAllMocks()
            value: () => {return 'decoded';},
        });`

Error:
`Cannot redefine property: decode
TypeError: Cannot redefine property: decode`

**Comment by Drew-Kimberly** [comment]
We have legitimate use-cases for `decode` in production. Bumping to 9.x caused issues for us as well. I don't mind if `decode` is removed in favor of a more explicitly named method like `decodeUnsafe` as long as the functionality is available.

This is particularly pertinent since the 8->9 version bump mitigates a number of vulnerabilities in the package (meaning some consumers are somewhat forced to upgrade ASAP).

**Comment by kento-machida** [comment]
I think it should once revert back to defineProperty (delete settings) due to run `decode ` function normally and upgrade to v9 for all users.
Could you please consider the above ?
https://github.com/auth0/node-jsonwebtoken/blob/e1fa9dcc12054a8681db4e6373da1b30cf7016e3/index.js#L9-L12

**Comment by BenWildeman** [comment]
A better way of making this work in jest without mocking the whole lib is as follows:

```ts
import * as jwt from 'jsonwebtoken';

jest.mock('jsonwebtoken', () => {
    return {
        __esModule: true,
        ...jest.requireActual('jsonwebtoken'),
        decode: require('jsonwebtoken/decode')
    };
});
```
that way you're not mocking every function as suggested in https://github.com/auth0/node-jsonwebtoken/issues/866#issuecomment-1398270160, and still allows you stub decode

**Comment by kento-machida** [comment]
This issue already done to fix.
Close it,
