### ISSUE TITLE
Regression between v8 and v9 when used in a Single Page Application (the library is run in a web browser)

### ISSUE THREAD

**Issue by tbl0605** [auth0/node-jsonwebtoken#868]
### Description

Using v9.0.0 in a SPA (the code is run in a web browser) doesn't work anymore, the last working version was v8.5.1

In the web browser console I get following error:
```
TypeError: invalid 'instanceof' operand KeyObject
    exports verify.js:120
    getSecret verify.js:97
    exports verify.js:101
```

When using the debugger it tells me that KeyObject is undefined:
```
 if (secretOrPublicKey != null && !(secretOrPublicKey instanceof KeyObject)) {
```

The culprit is following import that returns undefined objects: 
```
const {KeyObject, createSecretKey, createPublicKey} = require("crypto");
```

I tried to force the integration of "cryto" in my package.json, but it didn't change anything.

Thank you by advance for your help!

### Environment

node-jsonwebtoken v9.0.0
webpack 4.46.0
vue-cli v4.5.19
Vue.js 2.7.14
Node.js v14.19.0

**Comment by panva** [comment]
`jsonwebtoken` is a Node.js module, always was, its use in a browser was never intended. Versions before 9.0.0 could use webpack's polyfill of the Node.js built-in modules. This most likely a) relied on slow js cryptography that isn't [maintained anymore](https://www.npmjs.com/package/crypto-browserify) and lacks feature parity with Node's crypto and b) increased your js bundle size considerably. FWIW webpack 5 also no longer defaults to using these questionable crypto polyfills anymore.

It is better to rely on JWT modules made to be consumed in browser environments. You can discover such modules on [jwt.io](https://jwt.io/libraries?language=JavaScript) under "JavaScript" libraries.
