### ISSUE TITLE
Missing documentation for expiresInMinutes and expiresInSeconds

### ISSUE THREAD

**Issue by samholmes** [auth0/node-jsonwebtoken#87]
Documentation should explain what possible values are valid for these options. Should the expiresInMinutes be the number of minutes from unix time or number of minutes from token generation?

**Comment by Zertz** [comment]
The name implies it is from token generation: [token] expires in x minutes

**Comment by jfromaniello** [comment]
Yes, it is from token generation and I don't like these parameters.

**Comment by knownasilya** [comment]
Please make only one, it's a big pain if exposing the config to users because it's confusing which one will have effect.. One option should be enough.

**Comment by jfromaniello** [comment]
These parameters are deprecated and will be removed on next major version.

**Comment by alexilyaev** [comment]
For those who stumble upon this, we should use `expiresIn` from this point on.
