### ISSUE TITLE
JWT malformed even if the token is present

### ISSUE THREAD

**Issue by formerskulk4** [auth0/node-jsonwebtoken#871]
### Description

I am creating a react application with an express backend.
For the token, I am generating and verifing with jwt library.
I have also created two stackoverflow question for more information on the issue:

1. [Question 1 ](https://stackoverflow.com/questions/75009542/jsonwebtokenerror-jwt-malformed-if-i-use-an-instance-of-axios-in-react
)

2.  [Question 2 ](https://stackoverflow.com/questions/74997610/jsonwebtokenerror-jwt-malformed-in-express-as-soon-as-the-user-logs-in-but-if)

### Reproduction

Frontend.

Here it works, but when I create a new instance of  axios, when I try to verify the request, says that token is null and gives me the error that jwt is malformed.

```
console.log(localStorage.getItem("token")) // ey.....
   const res = await axios.get(`${process.env.REACT_APP_API_URL}/admin/categories`, {
          headers: {
            token: `${localStorage.getItem("token")}`,
          },
        })
```

In this scenario, it does not work.

index.tsx

```
    import axios_auth from "../../../utils/axios/admin"
console.log(localStorage.getItem("token")) // ey.....
    const res = await axios_auth.get(`/admin/categories`) 

```
admin.ts
```
import axios from "axios";
export default axios.create({
  baseURL: `${process.env.REACT_APP_API_URL}`,
  headers: {
    token: `${localStorage.getItem("token")}`,
  },
});
```

### Environment

Windows 10
  "axios": "^0.27.2",
    "jwt-decode": "^3.1.2",
    "react": "^18.2.0",

**Comment by david-renaud-okta** [comment]
From what I can see on https://stackoverflow.com/a/75027383 this was a bug with your axios setup and not specific to the JWT library.
