### ISSUE TITLE
Version 9.0.0 Increased bundle size, probably due to lodash import

### ISSUE THREAD

**Issue by ahedenholm-bonn** [auth0/node-jsonwebtoken#878]
### Description

When trying to update to 9.0.0 we noticed that the bundle size of jsonwebtoken had increased quite a lot, making a small app of ours exceed a max size limit at a cloud platform.

It seems to us at least that it might be due to importing the whole lodash package in package.json instead of just the functions used, introduced in this commit: ecdf6cc6073ea13a7e71df5fad043550f08d0fa6

I realise this doesn't necessarily fit all that well under "bug", sorry in that case.

### Reproduction
Here's two screenshots from bundlephobia comparing 8.5.1 vs 9.0.0

**8.5.1:**
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/60604172/212004079-2f18004a-ee5d-4c90-a0a9-6eaaf300d0f4.png">
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/60604172/212007387-8743f1b5-b2a1-4da9-94c0-9c2541043ad5.png">

**9.0.0:**
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/60604172/212004161-d064d2d3-570f-40b6-9de6-a6bf1bc04272.png">
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/60604172/212007498-40ba0e54-a948-435c-b1d0-e834cee82781.png">

### Environment
- **Version of this library used:** 9.0.0

**Comment by mulfyx** [comment]
```js
const {includes, isBoolean, isInteger, isNumber, isPlainObject, isString, once} = require('lodash')
```

the guys really need lodash for `Array#includes` and `typeof` 💀💀💀

**Comment by Uzlopak** [comment]
Created a PR #879 which removes lodash with equivalent.

**Comment by Uzlopak** [comment]
Also created a PR for removing semver

So I guesstimate, that when those two PRs get merged the bundle size shrinks t 20%?

**Comment by BeenaCelin** [comment]
When can we expect this fix? As our app is impacted in bundled size due to this new version (9.0.0)[our app(edgelambda) is associated with cloudfront viewe request , and the viewer request quota limit is 1 MB for cloudfront. Kindly let us know the ETC for this fix and release

**Comment by Uzlopak** [comment]
@BeenaCelin 
When I see when the last release before v9 was, I assume that this project is basically unmaintained. Maybe it is worth to switch to fast-jwt?

**Comment by rajeev5rhyme** [comment]
@Uzlopak :Are going to release new version of jsonwebtoken with shrinked loadash size?  Is jsonwebtoken and fast-jwt has same feature?

**Comment by Uzlopak** [comment]
I am not a maintainer of jsonwebtoke and i dont want to fork and release a patched version.
