### ISSUE TITLE
I got an error 'TypeError: Right-hand side of 'instanceof' is not an object' when using the sign() function. Here is the code I am using:

### ISSUE THREAD

**Issue by gtrgeg** [auth0/node-jsonwebtoken#892]
const jwt = require('jsonwebtoken');

const payload = {
    resource: { question: 65  }, 
    params: {},
    exp: Math.floor(Date.now() / 1000) + (60 * 60) 
};

const secretKey = '9bd3717297e6ef69383e2f7999eb7131448e3333f74fa613a09677ca250408e2'; // Metabase的Secret Key

const token = jwt.sign(payload, secretKey);

This is the error message of the program：

"TypeError: Right-hand side of 'instanceof' is not an object"

How can I solve this problem? Looking forward to your reply💕

**Comment by miguelcastaneda82** [comment]
I have the same problem.

It seems to be version 9.0.0, at the moment I installed version 8.5.1 and it works fine

**Comment by gtrgeg** [comment]
thanks,Following your suggestion, I solved the problem😘

**Comment by ramiel** [comment]
Why is this closed? The solution is just a workaround

**Comment by hajjarjoseph** [comment]
I was also having the same issue using 9.0.0. Downgrading to 8.5.1 fixed it for me as well. However, this issue should still be open.

**Comment by avidianity** [comment]
Please reopen the issue. Downgrading is not a fix but just a workaround.

**Comment by Lythaeon** [comment]
Downgrading let me only use sign(). If I want to verify I still get the same error 

Also to note: On node the newest version works flawlessly but on bun only sign function works with jsonwebtoken version 8.5.1

**Comment by BRAVO68WEB** [comment]
Still facing the same issue on verify

**Comment by DatoKhojava** [comment]
> I have the same problem.
> 
> It seems to be version 9.0.0, at the moment I installed version 8.5.1 and it works fine

Its worked for me too thank you

**Comment by DiegoZumarragaLS** [comment]
I have the same issue. I installed version 8.5.1 and now it works. 

The Issue should be opened until the documentation gets clear on how to generate a token with the latest version

**Comment by aapolipponen** [comment]
Please reopen this!

**Comment by HyoilKim** [comment]
@gtrgeg Could you reopen this?

**Comment by spaceInvaders007** [comment]
I m having the same problem when using node 20, I tried downgrading to version 8.5.1 but it doesn't work for me

**Comment by chelugrasu** [comment]
> I m having the same problem when using node 20, I tried downgrading to version 8.5.1 but it doesn't work for me

Same here, i tried on 2 different node versions , 22.1.0 and 21.7.2

i get the same error.

**Comment by spaceInvaders007** [comment]
> > I m having the same problem when using node 20, I tried downgrading to version 8.5.1 but it doesn't work for me
> 
> Same here, i tried on 2 different node versions , 22.1.0 and 21.7.2
> 
> i get the same error.

I ended up replacing the library with jose. It fixed the issue

**Comment by BRAVO68WEB** [comment]
But, this library is very widely used. Can we expect a permanent solution?

**Comment by drxc00** [comment]
Still experiencing this issue. Any new fixes?
