### ISSUE TITLE
Error Message Not Clear in Token Expired and Token Invalid Signature when invoking verify method

### ISSUE THREAD

**Issue by kypertirost** [auth0/node-jsonwebtoken#908]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Problem statement : As a developer, I want to have a clearer error message in different cases for jwt token so that I can know what's wrong for my token. 

```
jwt.verify(expiredToken, pubKey, { algorithms: ['RS256'] }) 
```

This will return invalid signature error. However, signature that I provide is in fact a valid public key. It would be a great help for developer to know what exactly happen in the token verification steps so he or she can focus in fixing it by looking at the error message. 

### Describe the ideal solution

Ideal solution would be publishing several error cases corresponding to 
- invalid header (already have)
- invalid signature (already have)
- token expired
- invalid scope

## Alternatives and current work-arounds

Workaround that I have implemented to differentiate is by decode the jwt first and verify expiration time. Then verify token through verify message to populate more direct error message.

### Additional context

> Add any other context or screenshots about the feature request here.

**Comment by iuuukhueeee** [comment]
Try to invoke `jwt.verify(expiredToken, pubKey, { algorithms: ['RS256'] })` in a try-catch statement. That works for me.

**Comment by kypertirost** [comment]
@iuuukhueeee  Thanks. It looks like I'm using a long-term token and got myself mixed up. Thanks for the helps. I will close this ticket

**Comment by mdbiplob0175-ship-it** [comment]
{"detail":"Invalid signature or expired URL"}
