### ISSUE TITLE
Error with verifying access token

### ISSUE THREAD

**Issue by mutairibassam** [auth0/node-jsonwebtoken#915]
### Description
jwt.verify() function returns `invalid signature` although the signature is correct. The code was working 2 days ago with no changes, now it always returns `invalid signature`.

Token generation is working and it's valid based on https://jwt.io verification but verifying the token is throwing an error.

I debugged the issue and the cause from the below condition (package code, not my code).

```js
try {
  // jws.verify return false which let it throw JsonWebTokenError('invalid signature') in below condition.
  valid = jws.verify(jwtString, decodedToken.header.alg, secretOrPublicKey);
} catch (e) {
  return done(e);
}

if (!valid) {
  return done(new JsonWebTokenError('invalid signature'));
}
```
### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
1. create a profile and generate a new token for a specific user using the below function.
```js
function generateAccessToken(user) {
    // user == {username: 'mike'}
    // process.parsed.ACCESS_TOKEN_SECRET == test
    return jwt.sign(user, process.parsed.ACCESS_TOKEN_SECRET, {
        expiresIn: "7d",
    });
}
```
2. Verify the generated token.
```js
// process.parsed.ACCESS_TOKEN_SECRET == test
jwt.verify(token, process.parsed.ACCESS_TOKEN_SECRET, async (err, user) => {
    // err == Invalid Signature
    if (err) return res.status(403).send(Response.forbidden({}));

    // check database and compare the tokens
    const dbToken = await getTokenByUsername(user.username);
    // check tokens
    if(token === dbToken) {
        req.user = user;
        return next();
    }
    return res.status(403).send(
        Response.forbidden({})
    ); 
});
```
3. You should face invalid signature error.

- Log files (redact/remove sensitive information)
Error: JsonWebTokenError: invalid signature
- Screenshots
<img width="993" alt="image" src="https://github.com/auth0/node-jsonwebtoken/assets/54819958/b718c0d8-0a66-4bef-b75d-a26c0e2aeeb2">

### Environment

> Please provide the following:

- **Version of this library used: ^9.0.0**
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser): nodejs (v18.13.0) npm (8.19.3)**
- **Other modules/plugins/libraries that might be involved:**

**Comment by mutairibassam** [comment]
Issue has been fixed. The token was overridden by parent collection and there is no issue with the package.

**Comment by Harrylever** [comment]
Hi @mutairibassam. I am currently having an issue with this. Please, can you explain what you mean by the token being overridden by parent collection?

**Comment by RajyashreeTR006** [comment]
Im facing the issue with token.
Error verifying token: JsonWebTokenError: invalid signature
0|backend  |     at /home/azureuser/testingapp_backend/node_modules/jsonwebtoken/verify.js:171:19
0|backend  |     at getSecret (/home/azureuser/testingapp_backend/node_modules/jsonwebtoken/verify.js:97:14)
0|backend  |     at module.exports [as verify] (/home/azureuser/testingapp_backend/node_modules/jsonwebtoken/verify.js:101:10)
0|backend  |     at verifyToken (/home/azureuser/testingapp_backend/src/auth/token_middleware.js:23:9)
0|backend  |     at Layer.handle [as handle_request] (/home/azureuser/testingapp_backend/node_modules/express/lib/router/layer.js:95:5)
0|backend  |     at next (/home/azureuser/testingapp_backend/node_modules/express/lib/router/route.js:137:13)
0|backend  |     at Route.dispatch (/home/azureuser/testingapp_backend/node_modules/express/lib/router/route.js:112:3)
0|backend  |     at Layer.handle [as handle_request] (/home/azureuser/testingapp_backend/node_modules/express/lib/router/layer.js:95:5)
0|backend  |     at /home/azureuser/testingapp_backend/node_modules/express/lib/router/index.js:281:22
0|backend  |     at Function.process_params (/home/azureuser/testingapp_backend/node_modules/express/lib/router/index.js:335:12)
0|backend  | enter token verify block
0|backend  | error in jwt.JsonWebTokenError JsonWebTokenError: invalid signature
0|backend  |     at /home/azureuser/testingapp_backend/node_modules/jsonwebtoken/verify.js:171:19
0|backend  |     at getSecret (/home/azureuser/testingapp_backend/node_modules/jsonwebtoken/verify.js:97:14)
0|backend  |     at module.exports [as verify] (/home/azureuser/testingapp_backend/node_modules/jsonwebtoken/verify.js:101:10)
0|backend  |     at refreshToken (/home/azureuser/testingapp_backend/src/auth/auth_controllers.js:92:29)
0|backend  |     at Layer.handle [as handle_request] (/home/azureuser/testingapp_backend/node_modules/express/lib/router/layer.js:95:5)
0|backend  |     at next (/home/azureuser/testingapp_backend/node_modules/express/lib/router/route.js:137:13)
0|backend  |     at Route.dispatch (/home/azureuser/testingapp_backend/node_modules/express/lib/router/route.js:112:3)
0|backend  |     at Layer.handle [as handle_request] (/home/azureuser/testingapp_backend/node_modules/express/lib/router/layer.js:95:5)
0|backend  |     at /home/azureuser/testingapp_backend/node_modules/express/lib/router/index.js:281:22
0|backend  |     at Function.process_params (/home/azureuser/testingapp_backend/node_modules/express/lib/router/index.js:335:12)

**Comment by Harrylever** [comment]
Hi @RajyashreeTR006 , I was later able to observe the error on my end. My frontend was passing an old jwt token instead of passing the latest token and the jsonwebtoken package did not actually have a problem/bug.

I would ask you to go through your authentication flow again to see if you can find any misconfiguration or a mixup in your code.
