### ISSUE TITLE
Support PEM passphrase

### ISSUE THREAD

**Issue by tehsenaus** [auth0/node-jsonwebtoken#93]
I would expect the following to work with Node 0.12 (https://nodejs.org/api/crypto.html#crypto_sign_sign_private_key_output_format):

``` js
jwt.sign(payload, { key: privateKey, passphrase: '...' })
```

However, I get an exception:

```
TypeError: key must be a string or buffer]
   at typeError (c:\\Workspace\\hv\\gallifrey-types\\node_modules\\jsonwebtok
en\\node_modules\\jws\\node_modules\\jwa\\index.js:13:10)
```

**Comment by Signus** [comment]
I would like similar support for supporting the PEM passphrase as I know of no current methods for providing the passphrase as of the current version 5.0.1+.

I get the following:

```
var jsonsigned = jwt.sign({ foo: 'bar' }, privKey, { algorithm: 'RS256' });
Error: error:0906A068:PEM routines:PEM_do_header:bad password read
    at Error (native)
    at Sign.sign (crypto.js:327:26)
    at Object.sign (/Users/user/node_modules/jsonwebtoken/node_modules/jws/node_modules/jwa/index.js:52:47)
    at Object.jwsSign [as sign] (/Users/user/node_modules/jsonwebtoken/node_modules/jws/lib/sign-stream.js:23:26)
    at Object.module.exports.sign (/Users/user/node_modules/jsonwebtoken/index.js:79:20)
    at repl:1:22
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
```

**Comment by alexandrebodin** [comment]
I made a PR on brianloveswords/node-jwa that should fix the issue [here](https://github.com/brianloveswords/node-jwa/pull/7) for this lib

**Comment by omsmith** [comment]
Thanks to @alexandrebodin you should be able to pass `{ key: '...', passphrase: '...' }` for the `sign` call if you update your dependencies. Available in _jwa 1.1.0_ / _jws 3.1.0_ for node _0.11+_.

**Comment by MichielDeMey** [comment]
@omsmith Yup, that worked for me.
I believe we can we close this issue?

**Comment by Signus** [comment]
I have also verified this. I second the motion to close this issue.

**Comment by bhanuV** [comment]
Hello, I am using jsonwebtoken version 5.4.1 and trying the support for pem passphrase.

For the given script,
```javascript
var jwt = require('jsonwebtoken'),
	fs = require('fs');

function generateToken (cb){
  fs.readFile('private.pem', function (err, data){
    if(err){
      console.log('error reading the file', err);
    } else {
      jwt.sign({test:'skill'}, { key: data.toString(), passphrase:'passphrase' }, { algorithm: 'RS256' },function(token){
      (token) ? cb(null, token) : cb('no token', null);	
      });
    }
  });
}

generateToken(function(err, result){
	(err) ? console.log(err) : console.log(result);
});
```
The error is thrown as below.

buffer.js:167
  throw new TypeError('must start with number, buffer, array or string');
  ^

TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:167:9)
    at Buffer (buffer.js:58:10)
    at new DataStream (/home/banupriya/tryitout/tokenJson/node_modules/jsonwebtoken/node_modules/jws/lib/data-stream.js:7:17)
    at new SignStream (/home/banupriya/tryitout/tokenJson/node_modules/jsonwebtoken/node_modules/jws/lib/sign-stream.js:29:24)
    at Object.createSign (/home/banupriya/tryitout/tokenJson/node_modules/jsonwebtoken/node_modules/jws/index.js:17:10)
    at Object.JWT.sign (/home/banupriya/tryitout/tokenJson/node_modules/jsonwebtoken/index.js:106:9)
    at /home/banupriya/tryitout/tokenJson/index.js:9:8
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

Can you tell me what I am doing wrong here?

**Comment by MichielDeMey** [comment]
As far as I'm aware, your key can just be the buffer.

Try using `{key:data}` instead of `{key:data.toString()}` as I believe a `toString()` of `key` will result in `[Object object]`.

I don't believe this has anything to do with the passphrase support though.

**Comment by omsmith** [comment]
@bhanuV You're using the callback signature of `jsonwebtoken#sign`, which as of https://github.com/auth0/node-jsonwebtoken/commit/9414fbcb15a1f9cf4fe147d070e9424c547dabba, apparently uses a different codepath in _jws_ that does alternate transformations on the inputs.

I'll try to get to it in the next day or two to make it work through any method of using _jws_

If you use the `sign` signature without a callback (the "asynchronous" one isn't particularly asynchronous anyway) it will work, which is why it worked for @MichielDeMey (and why I was confused when you first commented this morning).

**Comment by bhanuV** [comment]
I am back to work after the weekend. Thanks for the reply guys.
@MichielDeMey I changed {key:data.toString()} to {key:data}, but the error remained unchanged.
@omsmith I will try to do as you suggested without a callback.

Cheers.

**Comment by bhanuV** [comment]
The jwt.sign() method works fine without the callback for me. Thanks.
