### ISSUE TITLE
why need two keys ？

### ISSUE THREAD

**Issue by guda-art** [auth0/node-jsonwebtoken#947]
I think signing with a private key and verifying with a public key is unnecessary because jwt only needs to maintain one key

**Comment by AbdullahSoomroOfficial** [comment]
@guda-art 
Yes it is confusing initially. But we can use both symmetric/asymmetric encryption algorithms to sign a JWT.
In case of symmetric algorithms we have 1 secret key.
In case of asymmetric algorithms we have 2 keys(Public/Private).

It depends on the use case for what you want to use JWT for.
Mostly we use asymmetric algorithms for authentication purposes with JWT.

**Comment by guda-art** [comment]
Thank you.
