### ISSUE TITLE
payload.exp is not getting added

### ISSUE THREAD

**Issue by rupamkhaitan** [auth0/node-jsonwebtoken#95]
jwt.sign returns object with token & iat only

But when i see the code

if (expiresInSeconds) {
    payload.exp = timestamp + expiresInSeconds;
  }

It should add exp also inside the object

**Comment by jfromaniello** [comment]
Can you show your code?

**Comment by rupamkhaitan** [comment]
sorry there was issue in my code and because of that it was not adding up exp
