### ISSUE TITLE
Signature generation fails for SM2 private keys with ES256 algorithm for node 18 version

### ISSUE THREAD

**Issue by balnenikhil** [auth0/node-jsonwebtoken#957]
### Description

`jwt.sign(<payload>, <utf8 encoded SM2 private key>, { algorithm: 'ES256' })` fails with `"error":{"code":"ERR_OSSL_INVALID_DIGEST","library":"Provider routines","reason":"invalid digest"}`  when using node 18.17.0.

The above command works fine with node version 16 but fails with node versions 18 and 20.

### Environment

- **Version of this library used:** jsonwebtoken 9.0.0  and 9.0.2
- **Version of the platform or framework used:** nodejs 18.17.0

**Comment by panva** [comment]
There is no registered JWS algorithm for SM2 keys[^iana] and ES256 requires the use of an EC key using the P-256 curve. Furthermore Node.js does not fully support SM2 keys.[^node]

Bottom line use of SM2 keys with JOSE is unsupported and out of scope.

[^iana]: https://www.iana.org/assignments/jose/jose.xhtml#web-signature-encryption-algorithms
[^node]: https://github.com/nodejs/node/pull/37066
