### ISSUE TITLE
iat and exp properties of decoded object are undefined

### ISSUE THREAD

**Issue by wilsonbalderrama** [auth0/node-jsonwebtoken#96]
var token = jwt.sign('hello', secret, expiration);
    var decoded = jwt.decode(token);

    console.log(decoded.iat); // undefined
    console.log(decoded.exp); // undefined

Not sure if iat and exp should display anything but undefined when a string payload is sent instead of an object.

**Comment by jfromaniello** [comment]
The signed token in this case will not have exp/iat because it is an string. Try signing a JSON instead

**Comment by abhinav76** [comment]
@jfromaniello 
<code>
var token=jwt.sign(members,app.get('superSecret'),{
					expiresInMinutes:40
				});
</code>
I am using this code to generate a token. members is the data from the database. and the token does not have iat and exp. what is wrong?

**Comment by jfromaniello** [comment]
@abhinav76 please send me an example token

**Comment by jfromaniello** [comment]
I added a note.
