### ISSUE TITLE
examples & tests for ES256

### ISSUE THREAD

**Issue by shea256** [auth0/node-jsonwebtoken#97]
Hi, are there any examples and/or tests for ES256?

I'm trying to sign a message with jwt.sign() and I would like to be able to pass in a plain hex private key, but in the example with RS256, a PEM is required.

Could you please advise? Thanks!

**Comment by omsmith** [comment]
ES* also requires a PEM key (like RS*, it is calling into `crypto`/openssl).

ES* interoperability is currently broken thoug - see https://github.com/brianloveswords/node-jwa/issues/3 and https://github.com/brianloveswords/node-jws/issues/20

**Comment by omsmith** [comment]
The interop issue I mention is fixed at this point, btdubs

**Comment by shea256** [comment]
OK great thanks @omsmith. Recent commit / PR? And will the example be identical to RS256?

**Comment by omsmith** [comment]
https://github.com/brianloveswords/node-jwa/pull/5 released in _node-jwa@1.0.1_ which is a indirect dependency of _jsonwebtoken_.

It works identically to RS256 yep, just pass in a PEM for EC instead. secp256r1 for ES256, secp384r1 for ES384, and secp521r1 for ES512.

**Comment by shea256** [comment]
Oh wait, secp256k1 is not supported?

**Comment by omsmith** [comment]
The [JWA spec](https://tools.ietf.org/html/rfc7518#section-3.4) defines _ES256_ as _ECDSA using P-256 and SHA-256_ where _P-256_ is another name for _secp256r1_

**Comment by shea256** [comment]
Oh that's a pain. I actually think I've been using JWT libraries with SECP256K1. Not sure if there's something wrong there or they are actually going to both work. I'll experiment with it.

**Comment by omsmith** [comment]
_jsonwebtoken_ and it's dependencies don't decode the keys and verify the correct one is being used, which means you could use a different curve, but it would be incorrect to call it "ES256" at that point. There's also the trouble that other libraries may not be so lenient, and this set of libraries may not be so lenient in the future, which means you're risking interop issues.

The set of specs that _JWT_ uses allows you to define your own "alg" for usage in your applications, but I don't know of any libraries across the different languages which support that case very well, which means you're on your own at that point.

**Comment by ChristopherA** [comment]
Any progress on the question of a new alg=???? for keys using bitcoin's secp256k1?

**Comment by gillesdemey** [comment]
The following works fine for me:

```
openssl ecparam -genkey -name secp256k1 -noout -out private.pem
openssl ec -in private.pem -pubout -out public.pem
```

```javascript
var fs = require('fs')
var jwt = require('jsonwebtoken')

var priv = fs.readFileSync('./private.pem')
var token = jwt.sign({ foo: 'bar' }, priv, { algorithm: 'ES256' })

console.log(token)

var pub = fs.readFileSync('./public.pem')
var decoded = jwt.verify(token, pub, { algorithms: ['ES256'] })

console.log(decoded)
```

**Comment by omsmith** [comment]
@gillesdemey if that's what you choose to do, great. Keep it mind that you're out-of-spec at that point. _ES256_ is for _secp256r1_ and nothing else. It may, today, work for this set of libraries, but it may not for others, or for this one in the future. Definitely _not_ supported.

**Comment by gillesdemey** [comment]
@omsmith  Understood, would it make sense to clarify in the README that Koblitz curves aren't supported? 

Or some other way to be more specific on what openssl curves are supported? Maybe as a third column in the table?

**Comment by omsmith** [comment]
@gillesdemey Very clearly listed in the spec: [3.4.  Digital Signature with ECDSA](https://tools.ietf.org/html/rfc7518#section-3.4)
