### ISSUE TITLE
JWT Token Not Stored in Safari Browser (iOS and macOS) Due to Cross-Site Tracking Prevention

### ISSUE THREAD

**Issue by Sahil-Sevda** [auth0/node-jsonwebtoken#975]
### Description

The issue is that JWT tokens stored in cookies are not being saved in Safari (both iOS and macOS) when the "Prevent cross-site tracking" setting is enabled. The expected behavior is for the JWT token to be stored in a cookie regardless of this setting, as it works in other browsers like Chrome, Edge, and Opera. This issue causes the login functionality to fail in Safari unless the user manually disables "Prevent cross-site tracking" in their browser settings, which is not user-friendly.

### Reproduction

Deploy a MERN stack application with a frontend as a static site and a backend serving the API.
Use Render.com for deployment, with the frontend and backend hosted on separate subdomains.
Configure the backend to set a JWT token in a cookie upon user login.

Example code for setting the cookie in the backend:

const token = jwt.sign(
  { email: user.email, role: user.role, userID: user._id },
  process.env.JWT_SECRET,
  {
    expiresIn: "1d",
  }
);

res.cookie("token", token, {
  httpOnly: true,
  secure: true,
  sameSite: "None",
  maxAge: 86400000, // 1 day
});

Attempt to log in using Safari on iOS or macOS with "Prevent cross-site tracking" enabled.
Observe that the JWT token is not stored in the cookie, and the login fails.
Disable "Prevent cross-site tracking" in Safari settings and observe that the login works as expected.

### Environment

Version of this library used: [^9.0.2]
framework used: MERN Stack (MongoDB, Express, React, Node.js)

Additional Context
This issue affects user experience significantly on Safari browsers as it prevents seamless authentication flow without requiring users to change their privacy settings. Ensuring compatibility and proper handling of cookies across all major browsers is crucial for web applications.

**Comment by Sahil-Sevda** [comment]
@palash-cj Could you please take a look at this issue and provide any insights or potential solutions? Your expertise on this matter would be greatly appreciated.

**Comment by panva** [comment]
Hello @Sahil-Sevda 

This is not the correct forum to discuss browser behaviours, there's nothing the module can change or do to influence them.
