### ISSUE TITLE
How to forcefully expire any token ?

### ISSUE THREAD

**Issue by fahimbabarpatel** [auth0/node-jsonwebtoken#99]
Hello,

I am building api for phone devices. I am using token to authenticate and accessing  other resources successfully. Once user click on logout I want to expire this token. 

Note -  I am not saving token in database.

Waiting for input.

Thanks!

**Comment by omsmith** [comment]
One option in this case would be to add a "jti" (uuid) claim, and then maintain a list of blacklisted ids (they can be removed from the blacklist when the token would naturally expire). At this point, you lose much of the benefit of the offline verifiable tokens, as you'd need to do a lookup against your blacklist on each request.

Alternatively, using relatively short-lived tokens means you might just throw the token away on logout and not worry about it to much.

**Comment by jfromaniello** [comment]
@dschenkelman wrote about this:
https://auth0.com/blog/2015/03/10/blacklist-json-web-token-api-keys/
